# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_image_selection_list_form.ui'
#
# Created: Wed Sep 16 15:36:54 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisImageSelectionListDialog(object):
    def setupUi(self, apisImageSelectionListDialog):
        apisImageSelectionListDialog.setObjectName(_fromUtf8("apisImageSelectionListDialog"))
        apisImageSelectionListDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisImageSelectionListDialog.resize(751, 659)
        self.uiImageListTableV = QtGui.QTableView(apisImageSelectionListDialog)
        self.uiImageListTableV.setGeometry(QtCore.QRect(10, 60, 731, 451))
        self.uiImageListTableV.setObjectName(_fromUtf8("uiImageListTableV"))
        self.horizontalLayoutWidget = QtGui.QWidget(apisImageSelectionListDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiImageThumbsBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiImageThumbsBtn.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiImageThumbsBtn.setIcon(icon)
        self.uiImageThumbsBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiImageThumbsBtn.setAutoDefault(False)
        self.uiImageThumbsBtn.setObjectName(_fromUtf8("uiImageThumbsBtn"))
        self.horizontalLayout.addWidget(self.uiImageThumbsBtn)
        self.uiLoadOrthoBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiLoadOrthoBtn.setEnabled(False)
        self.uiLoadOrthoBtn.setIcon(icon)
        self.uiLoadOrthoBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiLoadOrthoBtn.setAutoDefault(False)
        self.uiLoadOrthoBtn.setObjectName(_fromUtf8("uiLoadOrthoBtn"))
        self.horizontalLayout.addWidget(self.uiLoadOrthoBtn)
        self.uiExportFootprintsBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiExportFootprintsBtn.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/extractgps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportFootprintsBtn.setIcon(icon1)
        self.uiExportFootprintsBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiExportFootprintsBtn.setAutoDefault(False)
        self.uiExportFootprintsBtn.setObjectName(_fromUtf8("uiExportFootprintsBtn"))
        self.horizontalLayout.addWidget(self.uiExportFootprintsBtn)
        self.uiCopyImagesBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiCopyImagesBtn.setEnabled(True)
        self.uiCopyImagesBtn.setIcon(icon1)
        self.uiCopyImagesBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiCopyImagesBtn.setAutoDefault(False)
        self.uiCopyImagesBtn.setObjectName(_fromUtf8("uiCopyImagesBtn"))
        self.horizontalLayout.addWidget(self.uiCopyImagesBtn)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.uiExportListAsPdfBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportListAsPdfBtn.setIcon(icon2)
        self.uiExportListAsPdfBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiExportListAsPdfBtn.setAutoDefault(False)
        self.uiExportListAsPdfBtn.setObjectName(_fromUtf8("uiExportListAsPdfBtn"))
        self.horizontalLayout.addWidget(self.uiExportListAsPdfBtn)
        self.uiFilterGrp = QtGui.QGroupBox(apisImageSelectionListDialog)
        self.uiFilterGrp.setGeometry(QtCore.QRect(10, 560, 731, 91))
        self.uiFilterGrp.setCheckable(True)
        self.uiFilterGrp.setChecked(False)
        self.uiFilterGrp.setObjectName(_fromUtf8("uiFilterGrp"))
        self.gridLayoutWidget = QtGui.QWidget(self.uiFilterGrp)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 711, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiFilterScaleOperatorCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiFilterScaleOperatorCombo.setObjectName(_fromUtf8("uiFilterScaleOperatorCombo"))
        self.uiFilterScaleOperatorCombo.addItem(_fromUtf8(""))
        self.uiFilterScaleOperatorCombo.addItem(_fromUtf8(""))
        self.uiFilterScaleOperatorCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiFilterScaleOperatorCombo, 1, 3, 1, 1)
        self.uiFilterScaleLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiFilterScaleLbl.setObjectName(_fromUtf8("uiFilterScaleLbl"))
        self.gridLayout.addWidget(self.uiFilterScaleLbl, 0, 3, 1, 2)
        self.uiFilterFilmKindCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiFilterFilmKindCombo.setObjectName(_fromUtf8("uiFilterFilmKindCombo"))
        self.gridLayout.addWidget(self.uiFilterFilmKindCombo, 1, 6, 1, 1)
        self.uiFilterObliqueChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterObliqueChk.setChecked(True)
        self.uiFilterObliqueChk.setObjectName(_fromUtf8("uiFilterObliqueChk"))
        self.gridLayout.addWidget(self.uiFilterObliqueChk, 0, 1, 2, 1)
        self.uiFilterVerticalChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterVerticalChk.setChecked(True)
        self.uiFilterVerticalChk.setObjectName(_fromUtf8("uiFilterVerticalChk"))
        self.gridLayout.addWidget(self.uiFilterVerticalChk, 0, 0, 2, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 2, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 2, 1)
        self.uiFilterScaleEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiFilterScaleEdit.setObjectName(_fromUtf8("uiFilterScaleEdit"))
        self.gridLayout.addWidget(self.uiFilterScaleEdit, 1, 4, 1, 1)
        self.uiFilterScanCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiFilterScanCombo.setObjectName(_fromUtf8("uiFilterScanCombo"))
        self.uiFilterScanCombo.addItem(_fromUtf8(""))
        self.uiFilterScanCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiFilterScanCombo, 1, 8, 1, 1)
        self.uiFilterOrthoCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiFilterOrthoCombo.setObjectName(_fromUtf8("uiFilterOrthoCombo"))
        self.uiFilterOrthoCombo.addItem(_fromUtf8(""))
        self.uiFilterOrthoCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiFilterOrthoCombo, 1, 10, 1, 1)
        self.uiFilterScanChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterScanChk.setTristate(False)
        self.uiFilterScanChk.setObjectName(_fromUtf8("uiFilterScanChk"))
        self.gridLayout.addWidget(self.uiFilterScanChk, 0, 8, 1, 1)
        self.uiFilterHiResChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterHiResChk.setTristate(False)
        self.uiFilterHiResChk.setObjectName(_fromUtf8("uiFilterHiResChk"))
        self.gridLayout.addWidget(self.uiFilterHiResChk, 0, 9, 1, 1)
        self.uiFilterHiResCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiFilterHiResCombo.setObjectName(_fromUtf8("uiFilterHiResCombo"))
        self.uiFilterHiResCombo.addItem(_fromUtf8(""))
        self.uiFilterHiResCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiFilterHiResCombo, 1, 9, 1, 1)
        self.uiFilterFilmKindChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterFilmKindChk.setObjectName(_fromUtf8("uiFilterFilmKindChk"))
        self.gridLayout.addWidget(self.uiFilterFilmKindChk, 0, 6, 1, 1)
        self.uiFilterOrthoChk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.uiFilterOrthoChk.setTristate(False)
        self.uiFilterOrthoChk.setObjectName(_fromUtf8("uiFilterOrthoChk"))
        self.gridLayout.addWidget(self.uiFilterOrthoChk, 0, 10, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 2, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(apisImageSelectionListDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 520, 711, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.uiImageCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiImageCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiImageCountLbl.setObjectName(_fromUtf8("uiImageCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiImageCountLbl)
        self.uiImageFilterCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiImageFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiImageFilterCountLbl.setObjectName(_fromUtf8("uiImageFilterCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiImageFilterCountLbl)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.uiScanCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiScanCountLbl.setLineWidth(1)
        self.uiScanCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiScanCountLbl.setObjectName(_fromUtf8("uiScanCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiScanCountLbl)
        self.uiScanFilterCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiScanFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiScanFilterCountLbl.setObjectName(_fromUtf8("uiScanFilterCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiScanFilterCountLbl)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.uiHiResCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiHiResCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiHiResCountLbl.setObjectName(_fromUtf8("uiHiResCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiHiResCountLbl)
        self.uiHiResFilterCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiHiResFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiHiResFilterCountLbl.setObjectName(_fromUtf8("uiHiResFilterCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiHiResFilterCountLbl)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.uiOrthoCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiOrthoCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiOrthoCountLbl.setObjectName(_fromUtf8("uiOrthoCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiOrthoCountLbl)
        self.uiOrthoFilterCountLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiOrthoFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiOrthoFilterCountLbl.setObjectName(_fromUtf8("uiOrthoFilterCountLbl"))
        self.horizontalLayout_2.addWidget(self.uiOrthoFilterCountLbl)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.uiImageCountLabelLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiImageCountLabelLbl.setObjectName(_fromUtf8("uiImageCountLabelLbl"))
        self.horizontalLayout_2.addWidget(self.uiImageCountLabelLbl)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)

        self.retranslateUi(apisImageSelectionListDialog)
        QtCore.QMetaObject.connectSlotsByName(apisImageSelectionListDialog)

    def retranslateUi(self, apisImageSelectionListDialog):
        apisImageSelectionListDialog.setWindowTitle(_translate("apisImageSelectionListDialog", "Bild Auswahl", None))
        self.uiImageThumbsBtn.setText(_translate("apisImageSelectionListDialog", "Vorschau", None))
        self.uiLoadOrthoBtn.setText(_translate("apisImageSelectionListDialog", "Ortho Laden", None))
        self.uiExportFootprintsBtn.setText(_translate("apisImageSelectionListDialog", "Footprints Export", None))
        self.uiCopyImagesBtn.setText(_translate("apisImageSelectionListDialog", "Bilder Kopieren", None))
        self.pushButton.setText(_translate("apisImageSelectionListDialog", "EXIF/IPTC Export", None))
        self.uiExportListAsPdfBtn.setText(_translate("apisImageSelectionListDialog", "PDF Export", None))
        self.uiFilterGrp.setTitle(_translate("apisImageSelectionListDialog", "Filter", None))
        self.uiFilterScaleOperatorCombo.setItemText(0, _translate("apisImageSelectionListDialog", ">=", None))
        self.uiFilterScaleOperatorCombo.setItemText(1, _translate("apisImageSelectionListDialog", "=", None))
        self.uiFilterScaleOperatorCombo.setItemText(2, _translate("apisImageSelectionListDialog", "<=", None))
        self.uiFilterScaleLbl.setText(_translate("apisImageSelectionListDialog", "Maßstab/Radius", None))
        self.uiFilterObliqueChk.setText(_translate("apisImageSelectionListDialog", "schräg", None))
        self.uiFilterVerticalChk.setText(_translate("apisImageSelectionListDialog", "senkrecht", None))
        self.uiFilterScanCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja", None))
        self.uiFilterScanCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein", None))
        self.uiFilterOrthoCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja", None))
        self.uiFilterOrthoCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein", None))
        self.uiFilterScanChk.setText(_translate("apisImageSelectionListDialog", "Scan", None))
        self.uiFilterHiResChk.setText(_translate("apisImageSelectionListDialog", "HiRes", None))
        self.uiFilterHiResCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja", None))
        self.uiFilterHiResCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein", None))
        self.uiFilterFilmKindChk.setText(_translate("apisImageSelectionListDialog", "Filmart", None))
        self.uiFilterOrthoChk.setText(_translate("apisImageSelectionListDialog", "Ortho", None))
        self.label.setText(_translate("apisImageSelectionListDialog", "Kartiert:", None))
        self.uiImageCountLbl.setText(_translate("apisImageSelectionListDialog", "0", None))
        self.uiImageFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "(-)", None))
        self.label_2.setText(_translate("apisImageSelectionListDialog", "Scan:", None))
        self.uiScanCountLbl.setText(_translate("apisImageSelectionListDialog", "0", None))
        self.uiScanFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "(-)", None))
        self.label_3.setText(_translate("apisImageSelectionListDialog", "HiRes:", None))
        self.uiHiResCountLbl.setText(_translate("apisImageSelectionListDialog", "0", None))
        self.uiHiResFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "(-)", None))
        self.label_4.setText(_translate("apisImageSelectionListDialog", "Ortho:", None))
        self.uiOrthoCountLbl.setText(_translate("apisImageSelectionListDialog", "0", None))
        self.uiOrthoFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "(-)", None))
        self.uiImageCountLabelLbl.setText(_translate("apisImageSelectionListDialog", "Gesamt (Filter)", None))

import resource_rc
