# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_sharding_form.ui'
#
# Created: Mon Mar 28 15:31:12 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisShardingDialog(object):
    def setupUi(self, apisShardingDialog):
        apisShardingDialog.setObjectName(_fromUtf8("apisShardingDialog"))
        apisShardingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisShardingDialog.resize(750, 430)
        self.gridLayout_2 = QtGui.QGridLayout(apisShardingDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiSaveBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiSaveBtn.setEnabled(False)
        self.uiSaveBtn.setAutoDefault(False)
        self.uiSaveBtn.setObjectName(_fromUtf8("uiSaveBtn"))
        self.horizontalLayout.addWidget(self.uiSaveBtn)
        self.uiCancelBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiCancelBtn.setEnabled(False)
        self.uiCancelBtn.setAutoDefault(False)
        self.uiCancelBtn.setObjectName(_fromUtf8("uiCancelBtn"))
        self.horizontalLayout.addWidget(self.uiCancelBtn)
        self.uiOkBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiOkBtn.setAutoDefault(False)
        self.uiOkBtn.setObjectName(_fromUtf8("uiOkBtn"))
        self.horizontalLayout.addWidget(self.uiOkBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.uiBottomHorizontalLayout = QtGui.QHBoxLayout()
        self.uiBottomHorizontalLayout.setObjectName(_fromUtf8("uiBottomHorizontalLayout"))
        self.uiPicturesBtn = QtGui.QPushButton(apisShardingDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sites.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPicturesBtn.setIcon(icon)
        self.uiPicturesBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiPicturesBtn.setAutoDefault(False)
        self.uiPicturesBtn.setObjectName(_fromUtf8("uiPicturesBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiPicturesBtn)
        self.uiSketchesBtn = QtGui.QPushButton(apisShardingDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSketchesBtn.setIcon(icon1)
        self.uiSketchesBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiSketchesBtn.setAutoDefault(False)
        self.uiSketchesBtn.setObjectName(_fromUtf8("uiSketchesBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiSketchesBtn)
        self.gridLayout_2.addLayout(self.uiBottomHorizontalLayout, 2, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(apisShardingDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.uiFindsPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiFindsPTxt.setObjectName(_fromUtf8("uiFindsPTxt"))
        self.verticalLayout_4.addWidget(self.uiFindsPTxt)
        self.label_9 = QtGui.QLabel(apisShardingDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.uiMorphologyPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiMorphologyPTxt.setObjectName(_fromUtf8("uiMorphologyPTxt"))
        self.verticalLayout_4.addWidget(self.uiMorphologyPTxt)
        self.label_10 = QtGui.QLabel(apisShardingDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.uiMiscellaneousPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiMiscellaneousPTxt.setObjectName(_fromUtf8("uiMiscellaneousPTxt"))
        self.verticalLayout_4.addWidget(self.uiMiscellaneousPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 3, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiShardingDate = QtGui.QDateEdit(apisShardingDialog)
        self.uiShardingDate.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.uiShardingDate.setCalendarPopup(True)
        self.uiShardingDate.setObjectName(_fromUtf8("uiShardingDate"))
        self.gridLayout.addWidget(self.uiShardingDate, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(apisShardingDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.uiShardingTypeCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiShardingTypeCombo.setEditable(True)
        self.uiShardingTypeCombo.setObjectName(_fromUtf8("uiShardingTypeCombo"))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiShardingTypeCombo, 5, 1, 1, 1)
        self.label = QtGui.QLabel(apisShardingDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiPlotPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiPlotPTxt.setObjectName(_fromUtf8("uiPlotPTxt"))
        self.gridLayout.addWidget(self.uiPlotPTxt, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(apisShardingDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(apisShardingDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.uiWhereaboutsEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiWhereaboutsEdit.setObjectName(_fromUtf8("uiWhereaboutsEdit"))
        self.gridLayout.addWidget(self.uiWhereaboutsEdit, 7, 1, 1, 1)
        self.uiSiteNumberEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiSiteNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiSiteNumberEdit.setReadOnly(True)
        self.uiSiteNumberEdit.setObjectName(_fromUtf8("uiSiteNumberEdit"))
        self.gridLayout.addWidget(self.uiSiteNumberEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(apisShardingDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(apisShardingDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(apisShardingDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.uiVisibilityEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiVisibilityEdit.setObjectName(_fromUtf8("uiVisibilityEdit"))
        self.gridLayout.addWidget(self.uiVisibilityEdit, 6, 1, 1, 1)
        self.uiNameEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiNameEdit.setObjectName(_fromUtf8("uiNameEdit"))
        self.gridLayout.addWidget(self.uiNameEdit, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(apisShardingDialog)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(apisShardingDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.uiShardingNumberEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiShardingNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiShardingNumberEdit.setReadOnly(True)
        self.uiShardingNumberEdit.setObjectName(_fromUtf8("uiShardingNumberEdit"))
        self.gridLayout.addWidget(self.uiShardingNumberEdit, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiConditionBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiConditionBtn.setObjectName(_fromUtf8("uiConditionBtn"))
        self.horizontalLayout_3.addWidget(self.uiConditionBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.uiConditionPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiConditionPTxt.setObjectName(_fromUtf8("uiConditionPTxt"))
        self.verticalLayout.addWidget(self.uiConditionPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(apisShardingDialog)
        self.uiShardingTypeCombo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(apisShardingDialog)

    def retranslateUi(self, apisShardingDialog):
        apisShardingDialog.setWindowTitle(_translate("apisShardingDialog", "APIS Begehung", None))
        self.uiSaveBtn.setText(_translate("apisShardingDialog", "Speichern", None))
        self.uiCancelBtn.setText(_translate("apisShardingDialog", "Abbrechen", None))
        self.uiOkBtn.setText(_translate("apisShardingDialog", "OK", None))
        self.uiPicturesBtn.setText(_translate("apisShardingDialog", "Fotos Anzeigen", None))
        self.uiSketchesBtn.setText(_translate("apisShardingDialog", "Skizzen Anzeigen", None))
        self.label_8.setText(_translate("apisShardingDialog", "Funde:", None))
        self.label_9.setText(_translate("apisShardingDialog", "Morphologie:", None))
        self.label_10.setText(_translate("apisShardingDialog", "Sonstiges:", None))
        self.uiShardingDate.setDisplayFormat(_translate("apisShardingDialog", "dd.MM.yyyy", None))
        self.label_2.setText(_translate("apisShardingDialog", "Datum der Begehung:", None))
        self.uiShardingTypeCombo.setItemText(0, _translate("apisShardingDialog", "unsystematisch", None))
        self.uiShardingTypeCombo.setItemText(1, _translate("apisShardingDialog", "intensiver Survey", None))
        self.uiShardingTypeCombo.setItemText(2, _translate("apisShardingDialog", "extensiver Survey", None))
        self.uiShardingTypeCombo.setItemText(3, _translate("apisShardingDialog", "keine Angabe", None))
        self.label.setText(_translate("apisShardingDialog", "Fundort Nummer:", None))
        self.label_3.setText(_translate("apisShardingDialog", "Name BearbeiterIn:", None))
        self.label_4.setText(_translate("apisShardingDialog", "Parzelle:", None))
        self.label_7.setText(_translate("apisShardingDialog", "Verbleib:", None))
        self.label_6.setText(_translate("apisShardingDialog", "Sichtbarkeit:", None))
        self.label_5.setText(_translate("apisShardingDialog", "Begehtyp:", None))
        self.label_16.setText(_translate("apisShardingDialog", "*", None))
        self.label_11.setText(_translate("apisShardingDialog", "Begehung:", None))
        self.uiConditionBtn.setText(_translate("apisShardingDialog", "Zustand:", None))

import resource_rc
