# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_search_film_form.ui'
#
# Created: Fri Jun 12 13:56:05 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSearchFilmDialog(object):
    def setupUi(self, apisSearchFilmDialog):
        apisSearchFilmDialog.setObjectName(_fromUtf8("apisSearchFilmDialog"))
        apisSearchFilmDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisSearchFilmDialog.resize(470, 160)
        apisSearchFilmDialog.setMinimumSize(QtCore.QSize(470, 160))
        apisSearchFilmDialog.setMaximumSize(QtCore.QSize(470, 160))
        apisSearchFilmDialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(apisSearchFilmDialog)
        self.buttonBox.setGeometry(QtCore.QRect(380, 100, 81, 52))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.uiSearchModeTBox = QtGui.QToolBox(apisSearchFilmDialog)
        self.uiSearchModeTBox.setEnabled(True)
        self.uiSearchModeTBox.setGeometry(QtCore.QRect(10, 10, 361, 141))
        self.uiSearchModeTBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiSearchModeTBox.setFrameShadow(QtGui.QFrame.Plain)
        self.uiSearchModeTBox.setObjectName(_fromUtf8("uiSearchModeTBox"))
        self.uiSearchByDate = QtGui.QWidget()
        self.uiSearchByDate.setGeometry(QtCore.QRect(0, 0, 359, 76))
        self.uiSearchByDate.setObjectName(_fromUtf8("uiSearchByDate"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.uiSearchByDate)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiSearchDate = QtGui.QDateEdit(self.horizontalLayoutWidget)
        self.uiSearchDate.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.uiSearchDate.setCalendarPopup(True)
        self.uiSearchDate.setObjectName(_fromUtf8("uiSearchDate"))
        self.horizontalLayout_2.addWidget(self.uiSearchDate)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiYearOnlyRBtn = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.uiYearOnlyRBtn.setObjectName(_fromUtf8("uiYearOnlyRBtn"))
        self.gridLayout.addWidget(self.uiYearOnlyRBtn, 0, 0, 1, 1)
        self.uiMonthOnlyRBtn = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.uiMonthOnlyRBtn.setChecked(False)
        self.uiMonthOnlyRBtn.setObjectName(_fromUtf8("uiMonthOnlyRBtn"))
        self.gridLayout.addWidget(self.uiMonthOnlyRBtn, 1, 0, 1, 1)
        self.uiYearMonthRBtn = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.uiYearMonthRBtn.setObjectName(_fromUtf8("uiYearMonthRBtn"))
        self.gridLayout.addWidget(self.uiYearMonthRBtn, 0, 1, 1, 1)
        self.uiDateRBtn = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.uiDateRBtn.setChecked(True)
        self.uiDateRBtn.setObjectName(_fromUtf8("uiDateRBtn"))
        self.gridLayout.addWidget(self.uiDateRBtn, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.uiSearchModeTBox.addItem(self.uiSearchByDate, _fromUtf8(""))
        self.uiSearchByMilitaryNumber = QtGui.QWidget()
        self.uiSearchByMilitaryNumber.setGeometry(QtCore.QRect(0, 0, 359, 76))
        self.uiSearchByMilitaryNumber.setObjectName(_fromUtf8("uiSearchByMilitaryNumber"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.uiSearchByMilitaryNumber)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 341, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiMilitaryNumberLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiMilitaryNumberLbl.setObjectName(_fromUtf8("uiMilitaryNumberLbl"))
        self.horizontalLayout_3.addWidget(self.uiMilitaryNumberLbl)
        self.uiMilitaryNumberEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.uiMilitaryNumberEdit.setObjectName(_fromUtf8("uiMilitaryNumberEdit"))
        self.horizontalLayout_3.addWidget(self.uiMilitaryNumberEdit)
        self.uiSearchModeTBox.addItem(self.uiSearchByMilitaryNumber, _fromUtf8(""))
        self.uiSearchByTimeSpan = QtGui.QWidget()
        self.uiSearchByTimeSpan.setGeometry(QtCore.QRect(0, 0, 359, 76))
        self.uiSearchByTimeSpan.setObjectName(_fromUtf8("uiSearchByTimeSpan"))
        self.layoutWidget = QtGui.QWidget(self.uiSearchByTimeSpan)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 341, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiFromLbl = QtGui.QLabel(self.layoutWidget)
        self.uiFromLbl.setObjectName(_fromUtf8("uiFromLbl"))
        self.horizontalLayout.addWidget(self.uiFromLbl)
        self.uiFromChk = QtGui.QCheckBox(self.layoutWidget)
        self.uiFromChk.setText(_fromUtf8(""))
        self.uiFromChk.setChecked(True)
        self.uiFromChk.setObjectName(_fromUtf8("uiFromChk"))
        self.horizontalLayout.addWidget(self.uiFromChk)
        self.uiFromDate = QtGui.QDateEdit(self.layoutWidget)
        self.uiFromDate.setDate(QtCore.QDate(1900, 1, 1))
        self.uiFromDate.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.uiFromDate.setCalendarPopup(True)
        self.uiFromDate.setObjectName(_fromUtf8("uiFromDate"))
        self.horizontalLayout.addWidget(self.uiFromDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiToLbl = QtGui.QLabel(self.layoutWidget)
        self.uiToLbl.setObjectName(_fromUtf8("uiToLbl"))
        self.horizontalLayout.addWidget(self.uiToLbl)
        self.uiToChk = QtGui.QCheckBox(self.layoutWidget)
        self.uiToChk.setText(_fromUtf8(""))
        self.uiToChk.setChecked(True)
        self.uiToChk.setObjectName(_fromUtf8("uiToChk"))
        self.horizontalLayout.addWidget(self.uiToChk)
        self.uiToDate = QtGui.QDateEdit(self.layoutWidget)
        self.uiToDate.setDate(QtCore.QDate(2000, 2, 1))
        self.uiToDate.setCalendarPopup(True)
        self.uiToDate.setObjectName(_fromUtf8("uiToDate"))
        self.horizontalLayout.addWidget(self.uiToDate)
        self.uiSearchModeTBox.addItem(self.uiSearchByTimeSpan, _fromUtf8(""))
        self.uiVerticalChk = QtGui.QCheckBox(apisSearchFilmDialog)
        self.uiVerticalChk.setEnabled(True)
        self.uiVerticalChk.setGeometry(QtCore.QRect(390, 30, 70, 17))
        self.uiVerticalChk.setChecked(False)
        self.uiVerticalChk.setTristate(True)
        self.uiVerticalChk.setObjectName(_fromUtf8("uiVerticalChk"))
        self.uiObliqueChk = QtGui.QCheckBox(apisSearchFilmDialog)
        self.uiObliqueChk.setGeometry(QtCore.QRect(390, 50, 70, 21))
        self.uiObliqueChk.setChecked(False)
        self.uiObliqueChk.setTristate(True)
        self.uiObliqueChk.setObjectName(_fromUtf8("uiObliqueChk"))
        self.uiFilmModeLbl = QtGui.QLabel(apisSearchFilmDialog)
        self.uiFilmModeLbl.setGeometry(QtCore.QRect(380, 10, 46, 13))
        self.uiFilmModeLbl.setObjectName(_fromUtf8("uiFilmModeLbl"))

        self.retranslateUi(apisSearchFilmDialog)
        self.uiSearchModeTBox.setCurrentIndex(2)
        self.uiSearchModeTBox.layout().setSpacing(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), apisSearchFilmDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), apisSearchFilmDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(apisSearchFilmDialog)

    def retranslateUi(self, apisSearchFilmDialog):
        apisSearchFilmDialog.setWindowTitle(_translate("apisSearchFilmDialog", "Film Suche", None))
        self.uiSearchDate.setDisplayFormat(_translate("apisSearchFilmDialog", "dd.MM.yyyy", None))
        self.uiYearOnlyRBtn.setText(_translate("apisSearchFilmDialog", "nur Jahr", None))
        self.uiMonthOnlyRBtn.setText(_translate("apisSearchFilmDialog", "nur Monat", None))
        self.uiYearMonthRBtn.setText(_translate("apisSearchFilmDialog", "Jahr und Monat", None))
        self.uiDateRBtn.setText(_translate("apisSearchFilmDialog", "Datum", None))
        self.uiSearchModeTBox.setItemText(self.uiSearchModeTBox.indexOf(self.uiSearchByDate), _translate("apisSearchFilmDialog", "Datum", None))
        self.uiMilitaryNumberLbl.setText(_translate("apisSearchFilmDialog", "Neue oder Alte Militär Nr.:", None))
        self.uiSearchModeTBox.setItemText(self.uiSearchModeTBox.indexOf(self.uiSearchByMilitaryNumber), _translate("apisSearchFilmDialog", "Militär Nummer", None))
        self.uiFromLbl.setText(_translate("apisSearchFilmDialog", "von:", None))
        self.uiFromDate.setDisplayFormat(_translate("apisSearchFilmDialog", "dd.MM.yyyy", None))
        self.uiToLbl.setText(_translate("apisSearchFilmDialog", "bis:", None))
        self.uiToDate.setDisplayFormat(_translate("apisSearchFilmDialog", "dd.MM.yyyy", None))
        self.uiSearchModeTBox.setItemText(self.uiSearchModeTBox.indexOf(self.uiSearchByTimeSpan), _translate("apisSearchFilmDialog", "Zeitspanne", None))
        self.uiVerticalChk.setText(_translate("apisSearchFilmDialog", "senkrecht", None))
        self.uiObliqueChk.setText(_translate("apisSearchFilmDialog", "schräg", None))
        self.uiFilmModeLbl.setText(_translate("apisSearchFilmDialog", "Weise:", None))

