# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_site_mapping_form.ui'
#
# Created: Wed Jan 06 12:16:42 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSiteMappingDialog(object):
    def setupUi(self, apisSiteMappingDialog):
        apisSiteMappingDialog.setObjectName(_fromUtf8("apisSiteMappingDialog"))
        apisSiteMappingDialog.resize(316, 816)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiNewSiteGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiNewSiteGrp.setObjectName(_fromUtf8("uiNewSiteGrp"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.uiNewSiteGrp)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiNewSiteYesRBtn = QtGui.QRadioButton(self.uiNewSiteGrp)
        self.uiNewSiteYesRBtn.setChecked(True)
        self.uiNewSiteYesRBtn.setObjectName(_fromUtf8("uiNewSiteYesRBtn"))
        self.horizontalLayout.addWidget(self.uiNewSiteYesRBtn)
        self.uiNewSiteNoRBtn = QtGui.QRadioButton(self.uiNewSiteGrp)
        self.uiNewSiteNoRBtn.setObjectName(_fromUtf8("uiNewSiteNoRBtn"))
        self.horizontalLayout.addWidget(self.uiNewSiteNoRBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.uiNewSiteGrp)
        self.uiNewSiteInterpretationGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiNewSiteInterpretationGrp.setObjectName(_fromUtf8("uiNewSiteInterpretationGrp"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiNewSiteInterpretationGrp)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.uiNewSiteInterpretationGrp)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox = QtGui.QComboBox(self.uiNewSiteInterpretationGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton = QtGui.QPushButton(self.uiNewSiteInterpretationGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.uiNewSiteInterpretationGrp)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.uiNewSiteInterpretationGrp)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.uiNewSiteInterpretationGrp)
        self.uiSiteMappingModesGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiSiteMappingModesGrp.setObjectName(_fromUtf8("uiSiteMappingModesGrp"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.uiSiteMappingModesGrp)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_2 = QtGui.QPushButton(self.uiSiteMappingModesGrp)
        self.pushButton_2.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sites.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.label_4 = QtGui.QLabel(self.uiSiteMappingModesGrp)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.uiSiteMappingModesGrp)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_3 = QtGui.QPushButton(self.uiSiteMappingModesGrp)
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.label_5 = QtGui.QLabel(self.uiSiteMappingModesGrp)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.uiSiteMappingModesGrp)
        self.uiAddToSiteManuallyGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiAddToSiteManuallyGrp.setEnabled(True)
        self.uiAddToSiteManuallyGrp.setObjectName(_fromUtf8("uiAddToSiteManuallyGrp"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.uiAddToSiteManuallyGrp)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.uiAddToSiteManuallyGrp)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineEdit_3 = QtGui.QLineEdit(self.uiAddToSiteManuallyGrp)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_4 = QtGui.QPushButton(self.uiAddToSiteManuallyGrp)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.pushButton_8 = QtGui.QPushButton(self.uiAddToSiteManuallyGrp)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.uiAddToSiteManuallyGrp)
        self.uiAddToSiteByIntersectionGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiAddToSiteByIntersectionGrp.setObjectName(_fromUtf8("uiAddToSiteByIntersectionGrp"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiAddToSiteByIntersectionGrp)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.uiAddToSiteByIntersectionGrp)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_2 = QtGui.QComboBox(self.uiAddToSiteByIntersectionGrp)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_5 = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.uiAddToSiteByIntersectionGrp)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        apisSiteMappingDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(apisSiteMappingDialog)
        QtCore.QMetaObject.connectSlotsByName(apisSiteMappingDialog)

    def retranslateUi(self, apisSiteMappingDialog):
        apisSiteMappingDialog.setWindowTitle(_translate("apisSiteMappingDialog", "APIS Fundort Kartierung", None))
        self.uiNewSiteGrp.setTitle(_translate("apisSiteMappingDialog", "Neuer Fundort", None))
        self.uiNewSiteYesRBtn.setText(_translate("apisSiteMappingDialog", "ja", None))
        self.uiNewSiteNoRBtn.setText(_translate("apisSiteMappingDialog", "nein", None))
        self.uiNewSiteInterpretationGrp.setTitle(_translate("apisSiteMappingDialog", "Interpretation", None))
        self.label_2.setText(_translate("apisSiteMappingDialog", "Filmnummer oder Projektbezeichnung:", None))
        self.pushButton.setText(_translate("apisSiteMappingDialog", "Check", None))
        self.label_3.setText(_translate("apisSiteMappingDialog", "Bildnummer(n) (-1 für kein Bild):", None))
        self.uiSiteMappingModesGrp.setTitle(_translate("apisSiteMappingDialog", "Kartierung", None))
        self.label_4.setText(_translate("apisSiteMappingDialog", "Quadrat mit Diagonale [m]:", None))
        self.lineEdit_2.setText(_translate("apisSiteMappingDialog", "200", None))
        self.label_5.setText(_translate("apisSiteMappingDialog", "Polygon", None))
        self.uiAddToSiteManuallyGrp.setTitle(_translate("apisSiteMappingDialog", "Fundort Manuell Angeben", None))
        self.label_7.setText(_translate("apisSiteMappingDialog", "Bestehende Fundortnummer (z.B. AUT.12):", None))
        self.pushButton_4.setText(_translate("apisSiteMappingDialog", "Hinzufügen", None))
        self.pushButton_8.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))
        self.uiAddToSiteByIntersectionGrp.setTitle(_translate("apisSiteMappingDialog", "Besehende Fundorte im kartierten Bereich", None))
        self.label_6.setText(_translate("apisSiteMappingDialog", "Kartierung zu Fundort hinzufügen:", None))
        self.pushButton_5.setText(_translate("apisSiteMappingDialog", "Hinzufügen", None))
        self.pushButton_6.setText(_translate("apisSiteMappingDialog", "Manuelle Eingabe", None))
        self.pushButton_7.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))

import resource_rc
