# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_site_form.ui'
#
# Created: Wed Apr 27 09:52:17 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSiteDialog(object):
    def setupUi(self, apisSiteDialog):
        apisSiteDialog.setObjectName(_fromUtf8("apisSiteDialog"))
        apisSiteDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisSiteDialog.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisSiteDialog.setWindowIcon(icon)
        apisSiteDialog.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(apisSiteDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(apisSiteDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiSiteNumberEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiSiteNumberEdit.setAutoFillBackground(False)
        self.uiSiteNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiSiteNumberEdit.setReadOnly(True)
        self.uiSiteNumberEdit.setObjectName(_fromUtf8("uiSiteNumberEdit"))
        self.gridLayout.addWidget(self.uiSiteNumberEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(apisSiteDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.uiCountryEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiCountryEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCountryEdit.setReadOnly(True)
        self.uiCountryEdit.setObjectName(_fromUtf8("uiCountryEdit"))
        self.gridLayout.addWidget(self.uiCountryEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(apisSiteDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.uiCadastralCommunityEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiCadastralCommunityEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCadastralCommunityEdit.setReadOnly(True)
        self.uiCadastralCommunityEdit.setObjectName(_fromUtf8("uiCadastralCommunityEdit"))
        self.gridLayout.addWidget(self.uiCadastralCommunityEdit, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(apisSiteDialog)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 3, 0, 1, 1)
        self.uiCadastralCommunityNumberEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiCadastralCommunityNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCadastralCommunityNumberEdit.setReadOnly(True)
        self.uiCadastralCommunityNumberEdit.setObjectName(_fromUtf8("uiCadastralCommunityNumberEdit"))
        self.gridLayout.addWidget(self.uiCadastralCommunityNumberEdit, 3, 1, 1, 1)
        self.label_22 = QtGui.QLabel(apisSiteDialog)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.uiProjectOrFilmEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiProjectOrFilmEdit.setStyleSheet(_fromUtf8(""))
        self.uiProjectOrFilmEdit.setReadOnly(False)
        self.uiProjectOrFilmEdit.setObjectName(_fromUtf8("uiProjectOrFilmEdit"))
        self.gridLayout.addWidget(self.uiProjectOrFilmEdit, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(apisSiteDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.uiSiteDiscoveryCombo = QtGui.QComboBox(apisSiteDialog)
        self.uiSiteDiscoveryCombo.setEditable(True)
        self.uiSiteDiscoveryCombo.setObjectName(_fromUtf8("uiSiteDiscoveryCombo"))
        self.gridLayout.addWidget(self.uiSiteDiscoveryCombo, 5, 1, 1, 1)
        self.label_17 = QtGui.QLabel(apisSiteDialog)
        self.label_17.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 5, 2, 1, 1)
        self.label_20 = QtGui.QLabel(apisSiteDialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 6, 0, 1, 1)
        self.uiSiteCreationCombo = QtGui.QComboBox(apisSiteDialog)
        self.uiSiteCreationCombo.setEditable(True)
        self.uiSiteCreationCombo.setObjectName(_fromUtf8("uiSiteCreationCombo"))
        self.gridLayout.addWidget(self.uiSiteCreationCombo, 6, 1, 1, 1)
        self.label_18 = QtGui.QLabel(apisSiteDialog)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 6, 2, 1, 1)
        self.label_5 = QtGui.QLabel(apisSiteDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.uiFirstReportYearEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiFirstReportYearEdit.setMaxLength(4)
        self.uiFirstReportYearEdit.setPlaceholderText(_fromUtf8(""))
        self.uiFirstReportYearEdit.setObjectName(_fromUtf8("uiFirstReportYearEdit"))
        self.gridLayout.addWidget(self.uiFirstReportYearEdit, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(apisSiteDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.uiImagesEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiImagesEdit.setObjectName(_fromUtf8("uiImagesEdit"))
        self.gridLayout.addWidget(self.uiImagesEdit, 8, 1, 1, 1)
        self.label_10 = QtGui.QLabel(apisSiteDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.uiRasterEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiRasterEdit.setObjectName(_fromUtf8("uiRasterEdit"))
        self.gridLayout.addWidget(self.uiRasterEdit, 9, 1, 1, 1)
        self.label_11 = QtGui.QLabel(apisSiteDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.uiAreaEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiAreaEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiAreaEdit.setReadOnly(True)
        self.uiAreaEdit.setObjectName(_fromUtf8("uiAreaEdit"))
        self.gridLayout.addWidget(self.uiAreaEdit, 10, 1, 1, 1)
        self.label_12 = QtGui.QLabel(apisSiteDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.uiSiteReliabilityCombo = QtGui.QComboBox(apisSiteDialog)
        self.uiSiteReliabilityCombo.setEditable(True)
        self.uiSiteReliabilityCombo.setModelColumn(0)
        self.uiSiteReliabilityCombo.setObjectName(_fromUtf8("uiSiteReliabilityCombo"))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiSiteReliabilityCombo, 11, 1, 1, 1)
        self.label_19 = QtGui.QLabel(apisSiteDialog)
        self.label_19.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 11, 2, 1, 1)
        self.label_13 = QtGui.QLabel(apisSiteDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.uiFieldNameEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiFieldNameEdit.setObjectName(_fromUtf8("uiFieldNameEdit"))
        self.gridLayout.addWidget(self.uiFieldNameEdit, 12, 1, 1, 1)
        self.uiPlotNumberBtn = QtGui.QPushButton(apisSiteDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sketch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPlotNumberBtn.setIcon(icon1)
        self.uiPlotNumberBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiPlotNumberBtn.setAutoDefault(False)
        self.uiPlotNumberBtn.setObjectName(_fromUtf8("uiPlotNumberBtn"))
        self.gridLayout.addWidget(self.uiPlotNumberBtn, 13, 0, 1, 1)
        self.uiPlotNumberEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiPlotNumberEdit.setObjectName(_fromUtf8("uiPlotNumberEdit"))
        self.gridLayout.addWidget(self.uiPlotNumberEdit, 13, 1, 1, 1)
        self.uiCommentBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiCommentBtn.setIcon(icon1)
        self.uiCommentBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCommentBtn.setAutoDefault(False)
        self.uiCommentBtn.setObjectName(_fromUtf8("uiCommentBtn"))
        self.gridLayout.addWidget(self.uiCommentBtn, 14, 0, 1, 1)
        self.uiCommentEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiCommentEdit.setObjectName(_fromUtf8("uiCommentEdit"))
        self.gridLayout.addWidget(self.uiCommentEdit, 14, 1, 1, 1)
        self.label_14 = QtGui.QLabel(apisSiteDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 15, 0, 1, 1)
        self.uiElevationEdit = QtGui.QLineEdit(apisSiteDialog)
        self.uiElevationEdit.setObjectName(_fromUtf8("uiElevationEdit"))
        self.gridLayout.addWidget(self.uiElevationEdit, 15, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(apisSiteDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.uiDetailinterpretationPTxt = QtGui.QPlainTextEdit(apisSiteDialog)
        self.uiDetailinterpretationPTxt.setObjectName(_fromUtf8("uiDetailinterpretationPTxt"))
        self.verticalLayout.addWidget(self.uiDetailinterpretationPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(apisSiteDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.uiFindingsPTxt = QtGui.QPlainTextEdit(apisSiteDialog)
        self.uiFindingsPTxt.setObjectName(_fromUtf8("uiFindingsPTxt"))
        self.verticalLayout_2.addWidget(self.uiFindingsPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(apisSiteDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.uiLiteraturePTxt = QtGui.QPlainTextEdit(apisSiteDialog)
        self.uiLiteraturePTxt.setObjectName(_fromUtf8("uiLiteraturePTxt"))
        self.verticalLayout_3.addWidget(self.uiLiteraturePTxt)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.uiFindSpotGrp = QtGui.QGroupBox(apisSiteDialog)
        self.uiFindSpotGrp.setObjectName(_fromUtf8("uiFindSpotGrp"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiFindSpotGrp)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiAddNewFindSpotBtn = QtGui.QPushButton(self.uiFindSpotGrp)
        self.uiAddNewFindSpotBtn.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAddNewFindSpotBtn.setIcon(icon2)
        self.uiAddNewFindSpotBtn.setAutoDefault(False)
        self.uiAddNewFindSpotBtn.setObjectName(_fromUtf8("uiAddNewFindSpotBtn"))
        self.horizontalLayout.addWidget(self.uiAddNewFindSpotBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.uiFindSpotListTableV = QtGui.QTableView(self.uiFindSpotGrp)
        self.uiFindSpotListTableV.setGridStyle(QtCore.Qt.DotLine)
        self.uiFindSpotListTableV.setSortingEnabled(True)
        self.uiFindSpotListTableV.setObjectName(_fromUtf8("uiFindSpotListTableV"))
        self.uiFindSpotListTableV.horizontalHeader().setHighlightSections(False)
        self.uiFindSpotListTableV.horizontalHeader().setSortIndicatorShown(True)
        self.uiFindSpotListTableV.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.uiFindSpotListTableV)
        self.gridLayout_2.addWidget(self.uiFindSpotGrp, 1, 0, 1, 2)
        self.uiMapCanvasVLayout = QtGui.QVBoxLayout()
        self.uiMapCanvasVLayout.setObjectName(_fromUtf8("uiMapCanvasVLayout"))
        self.label_15 = QtGui.QLabel(apisSiteDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.uiMapCanvasVLayout.addWidget(self.label_15)
        self.uiSiteMapCanvas = QgsMapCanvas(apisSiteDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSiteMapCanvas.sizePolicy().hasHeightForWidth())
        self.uiSiteMapCanvas.setSizePolicy(sizePolicy)
        self.uiSiteMapCanvas.setObjectName(_fromUtf8("uiSiteMapCanvas"))
        self.uiMapCanvasVLayout.addWidget(self.uiSiteMapCanvas)
        self.gridLayout_2.addLayout(self.uiMapCanvasVLayout, 1, 2, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_16 = QtGui.QLabel(apisSiteDialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_6.addWidget(self.label_16)
        self.uiSiteImageView = QtGui.QGraphicsView(apisSiteDialog)
        self.uiSiteImageView.setObjectName(_fromUtf8("uiSiteImageView"))
        self.verticalLayout_6.addWidget(self.uiSiteImageView)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 3, 1, 1)
        self.uiBottomHorizontalLayout = QtGui.QHBoxLayout()
        self.uiBottomHorizontalLayout.setObjectName(_fromUtf8("uiBottomHorizontalLayout"))
        self.uiShowInterpretationBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiShowInterpretationBtn.setWhatsThis(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/layer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiShowInterpretationBtn.setIcon(icon3)
        self.uiShowInterpretationBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiShowInterpretationBtn.setAutoDefault(False)
        self.uiShowInterpretationBtn.setObjectName(_fromUtf8("uiShowInterpretationBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiShowInterpretationBtn)
        self.uiLoadSiteInQGisBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiLoadSiteInQGisBtn.setIcon(icon3)
        self.uiLoadSiteInQGisBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiLoadSiteInQGisBtn.setObjectName(_fromUtf8("uiLoadSiteInQGisBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiLoadSiteInQGisBtn)
        self.uiListImagesOfSiteBtn = QtGui.QPushButton(apisSiteDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListImagesOfSiteBtn.setIcon(icon4)
        self.uiListImagesOfSiteBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListImagesOfSiteBtn.setAutoDefault(False)
        self.uiListImagesOfSiteBtn.setObjectName(_fromUtf8("uiListImagesOfSiteBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListImagesOfSiteBtn)
        self.uiListShardingsOfSiteBtn = QtGui.QPushButton(apisSiteDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/footprints.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListShardingsOfSiteBtn.setIcon(icon5)
        self.uiListShardingsOfSiteBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListShardingsOfSiteBtn.setAutoDefault(False)
        self.uiListShardingsOfSiteBtn.setObjectName(_fromUtf8("uiListShardingsOfSiteBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListShardingsOfSiteBtn)
        self.uiExportPdfBtn = QtGui.QPushButton(apisSiteDialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/pdf_export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportPdfBtn.setIcon(icon6)
        self.uiExportPdfBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExportPdfBtn.setAutoDefault(False)
        self.uiExportPdfBtn.setObjectName(_fromUtf8("uiExportPdfBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiExportPdfBtn)
        self.uiDeleteSiteBtn = QtGui.QPushButton(apisSiteDialog)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/site_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDeleteSiteBtn.setIcon(icon7)
        self.uiDeleteSiteBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiDeleteSiteBtn.setAutoDefault(False)
        self.uiDeleteSiteBtn.setObjectName(_fromUtf8("uiDeleteSiteBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiDeleteSiteBtn)
        self.gridLayout_2.addLayout(self.uiBottomHorizontalLayout, 2, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiInitalEntryLbl = QtGui.QLabel(apisSiteDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiInitalEntryLbl.sizePolicy().hasHeightForWidth())
        self.uiInitalEntryLbl.setSizePolicy(sizePolicy)
        self.uiInitalEntryLbl.setObjectName(_fromUtf8("uiInitalEntryLbl"))
        self.horizontalLayout_2.addWidget(self.uiInitalEntryLbl)
        self.uiInitalEntryDate = QtGui.QDateEdit(apisSiteDialog)
        self.uiInitalEntryDate.setEnabled(True)
        self.uiInitalEntryDate.setAutoFillBackground(False)
        self.uiInitalEntryDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiInitalEntryDate.setReadOnly(True)
        self.uiInitalEntryDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiInitalEntryDate.setObjectName(_fromUtf8("uiInitalEntryDate"))
        self.horizontalLayout_2.addWidget(self.uiInitalEntryDate)
        self.uiLastChangesLbl = QtGui.QLabel(apisSiteDialog)
        self.uiLastChangesLbl.setObjectName(_fromUtf8("uiLastChangesLbl"))
        self.horizontalLayout_2.addWidget(self.uiLastChangesLbl)
        self.uiLastChangesDate = QtGui.QDateEdit(apisSiteDialog)
        self.uiLastChangesDate.setEnabled(True)
        self.uiLastChangesDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiLastChangesDate.setReadOnly(True)
        self.uiLastChangesDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiLastChangesDate.setObjectName(_fromUtf8("uiLastChangesDate"))
        self.horizontalLayout_2.addWidget(self.uiLastChangesDate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.uiSaveBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiSaveBtn.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSaveBtn.setIcon(icon8)
        self.uiSaveBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiSaveBtn.setAutoDefault(False)
        self.uiSaveBtn.setObjectName(_fromUtf8("uiSaveBtn"))
        self.horizontalLayout_2.addWidget(self.uiSaveBtn)
        self.uiCancelBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiCancelBtn.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCancelBtn.setIcon(icon9)
        self.uiCancelBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelBtn.setAutoDefault(False)
        self.uiCancelBtn.setObjectName(_fromUtf8("uiCancelBtn"))
        self.horizontalLayout_2.addWidget(self.uiCancelBtn)
        self.uiOkBtn = QtGui.QPushButton(apisSiteDialog)
        self.uiOkBtn.setIcon(icon8)
        self.uiOkBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiOkBtn.setAutoDefault(False)
        self.uiOkBtn.setObjectName(_fromUtf8("uiOkBtn"))
        self.horizontalLayout_2.addWidget(self.uiOkBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 4)

        self.retranslateUi(apisSiteDialog)
        self.uiSiteReliabilityCombo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(apisSiteDialog)
        apisSiteDialog.setTabOrder(self.uiSiteNumberEdit, self.uiCountryEdit)
        apisSiteDialog.setTabOrder(self.uiCountryEdit, self.uiCadastralCommunityEdit)
        apisSiteDialog.setTabOrder(self.uiCadastralCommunityEdit, self.uiCadastralCommunityNumberEdit)
        apisSiteDialog.setTabOrder(self.uiCadastralCommunityNumberEdit, self.uiProjectOrFilmEdit)
        apisSiteDialog.setTabOrder(self.uiProjectOrFilmEdit, self.uiSiteDiscoveryCombo)
        apisSiteDialog.setTabOrder(self.uiSiteDiscoveryCombo, self.uiSiteCreationCombo)
        apisSiteDialog.setTabOrder(self.uiSiteCreationCombo, self.uiFirstReportYearEdit)
        apisSiteDialog.setTabOrder(self.uiFirstReportYearEdit, self.uiImagesEdit)
        apisSiteDialog.setTabOrder(self.uiImagesEdit, self.uiRasterEdit)
        apisSiteDialog.setTabOrder(self.uiRasterEdit, self.uiAreaEdit)
        apisSiteDialog.setTabOrder(self.uiAreaEdit, self.uiSiteReliabilityCombo)
        apisSiteDialog.setTabOrder(self.uiSiteReliabilityCombo, self.uiFieldNameEdit)
        apisSiteDialog.setTabOrder(self.uiFieldNameEdit, self.uiPlotNumberBtn)
        apisSiteDialog.setTabOrder(self.uiPlotNumberBtn, self.uiPlotNumberEdit)
        apisSiteDialog.setTabOrder(self.uiPlotNumberEdit, self.uiCommentBtn)
        apisSiteDialog.setTabOrder(self.uiCommentBtn, self.uiCommentEdit)
        apisSiteDialog.setTabOrder(self.uiCommentEdit, self.uiElevationEdit)
        apisSiteDialog.setTabOrder(self.uiElevationEdit, self.uiDetailinterpretationPTxt)
        apisSiteDialog.setTabOrder(self.uiDetailinterpretationPTxt, self.uiFindingsPTxt)
        apisSiteDialog.setTabOrder(self.uiFindingsPTxt, self.uiLiteraturePTxt)
        apisSiteDialog.setTabOrder(self.uiLiteraturePTxt, self.uiAddNewFindSpotBtn)
        apisSiteDialog.setTabOrder(self.uiAddNewFindSpotBtn, self.uiFindSpotListTableV)
        apisSiteDialog.setTabOrder(self.uiFindSpotListTableV, self.uiSiteImageView)
        apisSiteDialog.setTabOrder(self.uiSiteImageView, self.uiShowInterpretationBtn)
        apisSiteDialog.setTabOrder(self.uiShowInterpretationBtn, self.uiLoadSiteInQGisBtn)
        apisSiteDialog.setTabOrder(self.uiLoadSiteInQGisBtn, self.uiListImagesOfSiteBtn)
        apisSiteDialog.setTabOrder(self.uiListImagesOfSiteBtn, self.uiListShardingsOfSiteBtn)
        apisSiteDialog.setTabOrder(self.uiListShardingsOfSiteBtn, self.uiExportPdfBtn)
        apisSiteDialog.setTabOrder(self.uiExportPdfBtn, self.uiDeleteSiteBtn)
        apisSiteDialog.setTabOrder(self.uiDeleteSiteBtn, self.uiInitalEntryDate)
        apisSiteDialog.setTabOrder(self.uiInitalEntryDate, self.uiLastChangesDate)
        apisSiteDialog.setTabOrder(self.uiLastChangesDate, self.uiSaveBtn)
        apisSiteDialog.setTabOrder(self.uiSaveBtn, self.uiCancelBtn)
        apisSiteDialog.setTabOrder(self.uiCancelBtn, self.uiOkBtn)

    def retranslateUi(self, apisSiteDialog):
        apisSiteDialog.setWindowTitle(_translate("apisSiteDialog", "APIS Fundort", None))
        self.label.setText(_translate("apisSiteDialog", "Fundort Nummer:", None))
        self.label_2.setText(_translate("apisSiteDialog", "Land:", None))
        self.label_3.setText(_translate("apisSiteDialog", "Katastralgemeinde:", None))
        self.label_21.setText(_translate("apisSiteDialog", "KG Nummer:", None))
        self.label_22.setText(_translate("apisSiteDialog", "Film/Projekt:", None))
        self.label_4.setText(_translate("apisSiteDialog", "FO entdeckt durch:", None))
        self.label_17.setText(_translate("apisSiteDialog", "*", None))
        self.label_20.setText(_translate("apisSiteDialog", "Erstellt nach:", None))
        self.label_18.setText(_translate("apisSiteDialog", "*", None))
        self.label_5.setText(_translate("apisSiteDialog", "Erstmeldung:", None))
        self.label_6.setText(_translate("apisSiteDialog", "Bild(er):", None))
        self.label_10.setText(_translate("apisSiteDialog", "Raster:", None))
        self.label_11.setText(_translate("apisSiteDialog", "Fläche (ha):", None))
        self.label_12.setText(_translate("apisSiteDialog", "Fundort ist:", None))
        self.uiSiteReliabilityCombo.setItemText(0, _translate("apisSiteDialog", "sicher", None))
        self.uiSiteReliabilityCombo.setItemText(1, _translate("apisSiteDialog", "wahrscheinlich", None))
        self.uiSiteReliabilityCombo.setItemText(2, _translate("apisSiteDialog", "fraglich", None))
        self.uiSiteReliabilityCombo.setItemText(3, _translate("apisSiteDialog", "kein Fundort", None))
        self.label_19.setText(_translate("apisSiteDialog", "*", None))
        self.label_13.setText(_translate("apisSiteDialog", "Flurname:", None))
        self.uiPlotNumberBtn.setText(_translate("apisSiteDialog", "Parz. Nr:", None))
        self.uiCommentBtn.setText(_translate("apisSiteDialog", "Bemerkung:", None))
        self.label_14.setText(_translate("apisSiteDialog", "Ortshöhe:", None))
        self.label_7.setText(_translate("apisSiteDialog", "Detailinterpretation:", None))
        self.label_8.setText(_translate("apisSiteDialog", "Befund:", None))
        self.label_9.setText(_translate("apisSiteDialog", "Literatur:", None))
        self.uiFindSpotGrp.setTitle(_translate("apisSiteDialog", "Fundstellen", None))
        self.uiAddNewFindSpotBtn.setText(_translate("apisSiteDialog", "Neue Fundstelle", None))
        self.label_15.setText(_translate("apisSiteDialog", "Kartenausschnitt:", None))
        self.label_16.setText(_translate("apisSiteDialog", "Repräsentatives Luftbild:", None))
        self.uiShowInterpretationBtn.setToolTip(_translate("apisSiteDialog", "Flugweg des Filmes in QGIS anzeigen", None))
        self.uiShowInterpretationBtn.setText(_translate("apisSiteDialog", "Interpretation in QGIS laden", None))
        self.uiLoadSiteInQGisBtn.setText(_translate("apisSiteDialog", "Fundort in QGIS laden", None))
        self.uiListImagesOfSiteBtn.setText(_translate("apisSiteDialog", "Luftbilder", None))
        self.uiListShardingsOfSiteBtn.setText(_translate("apisSiteDialog", "Begehung", None))
        self.uiExportPdfBtn.setText(_translate("apisSiteDialog", "PDF exportieren", None))
        self.uiDeleteSiteBtn.setText(_translate("apisSiteDialog", "Fundort löschen", None))
        self.uiInitalEntryLbl.setText(_translate("apisSiteDialog", "Ersteintrag:", None))
        self.uiInitalEntryDate.setDisplayFormat(_translate("apisSiteDialog", "dd.MM.yyyy", None))
        self.uiLastChangesLbl.setText(_translate("apisSiteDialog", "Letzte Bearbeitung:", None))
        self.uiLastChangesDate.setDisplayFormat(_translate("apisSiteDialog", "dd.MM.yyyy", None))
        self.uiSaveBtn.setText(_translate("apisSiteDialog", "Speichern", None))
        self.uiCancelBtn.setText(_translate("apisSiteDialog", "Abbrechen", None))
        self.uiOkBtn.setText(_translate("apisSiteDialog", "OK", None))

from qgis.gui import QgsMapCanvas
import resource_rc
