# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_film_form.ui'
#
# Created: Wed Jun 10 11:40:51 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisFilmDialog(object):
    def setupUi(self, apisFilmDialog):
        apisFilmDialog.setObjectName(_fromUtf8("apisFilmDialog"))
        apisFilmDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisFilmDialog.setEnabled(True)
        apisFilmDialog.resize(870, 520)
        apisFilmDialog.setMinimumSize(QtCore.QSize(870, 490))
        apisFilmDialog.setMaximumSize(QtCore.QSize(870, 520))
        apisFilmDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        apisFilmDialog.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Austria))
        apisFilmDialog.setModal(True)
        self.horizontalLayoutWidget = QtGui.QWidget(apisFilmDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 851, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.uiTopHorizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.uiTopHorizontalLayout.setMargin(0)
        self.uiTopHorizontalLayout.setObjectName(_fromUtf8("uiTopHorizontalLayout"))
        self.uiFilmSelectionBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/filmselection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFilmSelectionBtn.setIcon(icon)
        self.uiFilmSelectionBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiFilmSelectionBtn.setAutoDefault(False)
        self.uiFilmSelectionBtn.setObjectName(_fromUtf8("uiFilmSelectionBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiFilmSelectionBtn)
        self.uiCurrentFilmNumberEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.uiCurrentFilmNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCurrentFilmNumberEdit.setFrame(True)
        self.uiCurrentFilmNumberEdit.setReadOnly(True)
        self.uiCurrentFilmNumberEdit.setObjectName(_fromUtf8("uiCurrentFilmNumberEdit"))
        self.uiTopHorizontalLayout.addWidget(self.uiCurrentFilmNumberEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uiTopHorizontalLayout.addItem(spacerItem)
        self.uiFirstFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiFirstFilmBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFirstFilmBtn.setIcon(icon1)
        self.uiFirstFilmBtn.setAutoDefault(False)
        self.uiFirstFilmBtn.setObjectName(_fromUtf8("uiFirstFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiFirstFilmBtn)
        self.uiPreviousFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiPreviousFilmBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPreviousFilmBtn.setIcon(icon2)
        self.uiPreviousFilmBtn.setAutoDefault(False)
        self.uiPreviousFilmBtn.setObjectName(_fromUtf8("uiPreviousFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiPreviousFilmBtn)
        self.uiCurrentFilmCountEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCurrentFilmCountEdit.sizePolicy().hasHeightForWidth())
        self.uiCurrentFilmCountEdit.setSizePolicy(sizePolicy)
        self.uiCurrentFilmCountEdit.setObjectName(_fromUtf8("uiCurrentFilmCountEdit"))
        self.uiTopHorizontalLayout.addWidget(self.uiCurrentFilmCountEdit)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.uiTopHorizontalLayout.addWidget(self.label)
        self.uiTotalFilmCountLbl = QtGui.QLabel(self.horizontalLayoutWidget)
        self.uiTotalFilmCountLbl.setObjectName(_fromUtf8("uiTotalFilmCountLbl"))
        self.uiTopHorizontalLayout.addWidget(self.uiTotalFilmCountLbl)
        self.uiNextFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiNextFilmBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNextFilmBtn.setIcon(icon3)
        self.uiNextFilmBtn.setIconSize(QtCore.QSize(16, 16))
        self.uiNextFilmBtn.setAutoDefault(False)
        self.uiNextFilmBtn.setObjectName(_fromUtf8("uiNextFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiNextFilmBtn)
        self.uiLastFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiLastFilmBtn.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiLastFilmBtn.setIcon(icon4)
        self.uiLastFilmBtn.setAutoDefault(False)
        self.uiLastFilmBtn.setObjectName(_fromUtf8("uiLastFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiLastFilmBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uiTopHorizontalLayout.addItem(spacerItem1)
        self.uiNewFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNewFilmBtn.setIcon(icon5)
        self.uiNewFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiNewFilmBtn.setAutoDefault(False)
        self.uiNewFilmBtn.setObjectName(_fromUtf8("uiNewFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiNewFilmBtn)
        self.uiSearchFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSearchFilmBtn.setIcon(icon6)
        self.uiSearchFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiSearchFilmBtn.setAutoDefault(False)
        self.uiSearchFilmBtn.setObjectName(_fromUtf8("uiSearchFilmBtn"))
        self.uiTopHorizontalLayout.addWidget(self.uiSearchFilmBtn)
        self.layoutWidget = QtGui.QWidget(apisFilmDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 440, 851, 40))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.uiBottomHorizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.uiBottomHorizontalLayout.setMargin(0)
        self.uiBottomHorizontalLayout.setObjectName(_fromUtf8("uiBottomHorizontalLayout"))
        self.uiShowFlightPathBtn = QtGui.QPushButton(self.layoutWidget)
        self.uiShowFlightPathBtn.setWhatsThis(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/flightpath.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiShowFlightPathBtn.setIcon(icon7)
        self.uiShowFlightPathBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiShowFlightPathBtn.setAutoDefault(False)
        self.uiShowFlightPathBtn.setObjectName(_fromUtf8("uiShowFlightPathBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiShowFlightPathBtn)
        self.uiListSitesOfFilmBtn = QtGui.QPushButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sites.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListSitesOfFilmBtn.setIcon(icon8)
        self.uiListSitesOfFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListSitesOfFilmBtn.setAutoDefault(False)
        self.uiListSitesOfFilmBtn.setObjectName(_fromUtf8("uiListSitesOfFilmBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListSitesOfFilmBtn)
        self.uiListSitesByYearBtn = QtGui.QPushButton(self.layoutWidget)
        self.uiListSitesByYearBtn.setIcon(icon8)
        self.uiListSitesByYearBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListSitesByYearBtn.setAutoDefault(False)
        self.uiListSitesByYearBtn.setObjectName(_fromUtf8("uiListSitesByYearBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListSitesByYearBtn)
        self.uiListImagesOfFilmBtn = QtGui.QPushButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListImagesOfFilmBtn.setIcon(icon9)
        self.uiListImagesOfFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListImagesOfFilmBtn.setAutoDefault(False)
        self.uiListImagesOfFilmBtn.setObjectName(_fromUtf8("uiListImagesOfFilmBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListImagesOfFilmBtn)
        self.uiExtractGpsFromImagesBtn = QtGui.QPushButton(self.layoutWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/extractgps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExtractGpsFromImagesBtn.setIcon(icon10)
        self.uiExtractGpsFromImagesBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExtractGpsFromImagesBtn.setAutoDefault(False)
        self.uiExtractGpsFromImagesBtn.setObjectName(_fromUtf8("uiExtractGpsFromImagesBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiExtractGpsFromImagesBtn)
        self.uiExportPdfBtn = QtGui.QPushButton(self.layoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportPdfBtn.setIcon(icon11)
        self.uiExportPdfBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExportPdfBtn.setAutoDefault(False)
        self.uiExportPdfBtn.setObjectName(_fromUtf8("uiExportPdfBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiExportPdfBtn)
        self.gridLayoutWidget = QtGui.QWidget(apisFilmDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(619, 60, 241, 371))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.uiRightGridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.uiRightGridLayout.setMargin(0)
        self.uiRightGridLayout.setObjectName(_fromUtf8("uiRightGridLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.uiDepartureTimeLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiDepartureTimeLbl.setObjectName(_fromUtf8("uiDepartureTimeLbl"))
        self.gridLayout_4.addWidget(self.uiDepartureTimeLbl, 0, 0, 1, 1)
        self.uiDepartureTime = QtGui.QTimeEdit(self.gridLayoutWidget)
        self.uiDepartureTime.setCalendarPopup(True)
        self.uiDepartureTime.setObjectName(_fromUtf8("uiDepartureTime"))
        self.gridLayout_4.addWidget(self.uiDepartureTime, 0, 1, 1, 1)
        self.uiDepartureAirportLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiDepartureAirportLbl.setObjectName(_fromUtf8("uiDepartureAirportLbl"))
        self.gridLayout_4.addWidget(self.uiDepartureAirportLbl, 1, 0, 1, 1)
        self.uiDepartureAirportEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiDepartureAirportEdit.setObjectName(_fromUtf8("uiDepartureAirportEdit"))
        self.gridLayout_4.addWidget(self.uiDepartureAirportEdit, 1, 1, 1, 1)
        self.uiRightGridLayout.addLayout(self.gridLayout_4, 4, 1, 1, 1)
        self.uiArrivalLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiArrivalLbl.setObjectName(_fromUtf8("uiArrivalLbl"))
        self.uiRightGridLayout.addWidget(self.uiArrivalLbl, 5, 0, 1, 1)
        self.uiPilotEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiPilotEdit.setObjectName(_fromUtf8("uiPilotEdit"))
        self.uiRightGridLayout.addWidget(self.uiPilotEdit, 2, 1, 1, 1)
        self.uiPhotographerEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiPhotographerEdit.setObjectName(_fromUtf8("uiPhotographerEdit"))
        self.uiRightGridLayout.addWidget(self.uiPhotographerEdit, 0, 1, 1, 1)
        self.uiFlightDurationLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiFlightDurationLbl.setObjectName(_fromUtf8("uiFlightDurationLbl"))
        self.uiRightGridLayout.addWidget(self.uiFlightDurationLbl, 6, 0, 1, 1)
        self.uiAirplaneLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiAirplaneLbl.setObjectName(_fromUtf8("uiAirplaneLbl"))
        self.uiRightGridLayout.addWidget(self.uiAirplaneLbl, 3, 0, 1, 1)
        self.uiFlightDurationEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiFlightDurationEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFlightDurationEdit.setInputMask(_fromUtf8(""))
        self.uiFlightDurationEdit.setReadOnly(True)
        self.uiFlightDurationEdit.setObjectName(_fromUtf8("uiFlightDurationEdit"))
        self.uiRightGridLayout.addWidget(self.uiFlightDurationEdit, 6, 1, 1, 1)
        self.uiAirplaneEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiAirplaneEdit.setObjectName(_fromUtf8("uiAirplaneEdit"))
        self.uiRightGridLayout.addWidget(self.uiAirplaneEdit, 3, 1, 1, 1)
        self.uiPhotographerLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiPhotographerLbl.setObjectName(_fromUtf8("uiPhotographerLbl"))
        self.uiRightGridLayout.addWidget(self.uiPhotographerLbl, 0, 0, 1, 1)
        self.uiPilotLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiPilotLbl.setObjectName(_fromUtf8("uiPilotLbl"))
        self.uiRightGridLayout.addWidget(self.uiPilotLbl, 2, 0, 1, 1)
        self.uiDepartureLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiDepartureLbl.setObjectName(_fromUtf8("uiDepartureLbl"))
        self.uiRightGridLayout.addWidget(self.uiDepartureLbl, 4, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.uiArrivalTimeLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiArrivalTimeLbl.setObjectName(_fromUtf8("uiArrivalTimeLbl"))
        self.gridLayout_5.addWidget(self.uiArrivalTimeLbl, 0, 0, 1, 1)
        self.uiArrivalAirportLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiArrivalAirportLbl.setObjectName(_fromUtf8("uiArrivalAirportLbl"))
        self.gridLayout_5.addWidget(self.uiArrivalAirportLbl, 1, 0, 1, 1)
        self.uiArrivalTime = QtGui.QTimeEdit(self.gridLayoutWidget)
        self.uiArrivalTime.setObjectName(_fromUtf8("uiArrivalTime"))
        self.gridLayout_5.addWidget(self.uiArrivalTime, 0, 1, 1, 1)
        self.uiArrivalAirportEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiArrivalAirportEdit.setObjectName(_fromUtf8("uiArrivalAirportEdit"))
        self.gridLayout_5.addWidget(self.uiArrivalAirportEdit, 1, 1, 1, 1)
        self.uiRightGridLayout.addLayout(self.gridLayout_5, 5, 1, 1, 1)
        self.uiTargetCombo = QtGui.QComboBox(self.gridLayoutWidget)
        self.uiTargetCombo.setEditable(True)
        self.uiTargetCombo.setObjectName(_fromUtf8("uiTargetCombo"))
        self.uiRightGridLayout.addWidget(self.uiTargetCombo, 10, 1, 1, 1)
        self.uiTargetLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiTargetLbl.setObjectName(_fromUtf8("uiTargetLbl"))
        self.uiRightGridLayout.addWidget(self.uiTargetLbl, 10, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.uiRightGridLayout.addWidget(self.line_9, 7, 0, 1, 2)
        self.line_8 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.uiRightGridLayout.addWidget(self.line_8, 1, 0, 1, 2)
        self.uiWeatherCodeEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.uiWeatherCodeEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiWeatherCodeEdit.setReadOnly(True)
        self.uiWeatherCodeEdit.setObjectName(_fromUtf8("uiWeatherCodeEdit"))
        self.uiRightGridLayout.addWidget(self.uiWeatherCodeEdit, 8, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uiWeatherLbl = QtGui.QLabel(self.gridLayoutWidget)
        self.uiWeatherLbl.setObjectName(_fromUtf8("uiWeatherLbl"))
        self.horizontalLayout_5.addWidget(self.uiWeatherLbl)
        self.uiEditWeatherBtn = QtGui.QPushButton(self.gridLayoutWidget)
        self.uiEditWeatherBtn.setText(_fromUtf8(""))
        self.uiEditWeatherBtn.setIcon(icon10)
        self.uiEditWeatherBtn.setAutoDefault(False)
        self.uiEditWeatherBtn.setObjectName(_fromUtf8("uiEditWeatherBtn"))
        self.horizontalLayout_5.addWidget(self.uiEditWeatherBtn)
        self.uiRightGridLayout.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.uiWeatherPTxt = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.uiWeatherPTxt.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiWeatherPTxt.setReadOnly(True)
        self.uiWeatherPTxt.setObjectName(_fromUtf8("uiWeatherPTxt"))
        self.uiRightGridLayout.addWidget(self.uiWeatherPTxt, 9, 0, 1, 2)
        self.layoutWidget1 = QtGui.QWidget(apisFilmDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(330, 60, 271, 371))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.uiMiddleGridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.uiMiddleGridLayout.setMargin(0)
        self.uiMiddleGridLayout.setObjectName(_fromUtf8("uiMiddleGridLayout"))
        self.uiFilmModeLbl_2 = QtGui.QLabel(self.layoutWidget1)
        self.uiFilmModeLbl_2.setObjectName(_fromUtf8("uiFilmModeLbl_2"))
        self.uiMiddleGridLayout.addWidget(self.uiFilmModeLbl_2, 7, 0, 1, 1)
        self.uiCameraNumberEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiCameraNumberEdit.setObjectName(_fromUtf8("uiCameraNumberEdit"))
        self.uiMiddleGridLayout.addWidget(self.uiCameraNumberEdit, 2, 1, 1, 1)
        self.uiFilmMakeEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiFilmMakeEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFilmMakeEdit.setReadOnly(True)
        self.uiFilmMakeEdit.setObjectName(_fromUtf8("uiFilmMakeEdit"))
        self.uiMiddleGridLayout.addWidget(self.uiFilmMakeEdit, 7, 1, 1, 1)
        self.uiCalibratedFocalLengthEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiCalibratedFocalLengthEdit.setObjectName(_fromUtf8("uiCalibratedFocalLengthEdit"))
        self.uiMiddleGridLayout.addWidget(self.uiCalibratedFocalLengthEdit, 3, 1, 1, 1)
        self.uiCassetteLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiCassetteLbl.setObjectName(_fromUtf8("uiCassetteLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiCassetteLbl, 4, 0, 1, 1)
        self.uiCameraCombo = QtGui.QComboBox(self.layoutWidget1)
        self.uiCameraCombo.setEditable(True)
        self.uiCameraCombo.setObjectName(_fromUtf8("uiCameraCombo"))
        self.uiMiddleGridLayout.addWidget(self.uiCameraCombo, 0, 1, 1, 1)
        self.uiFormatLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiFormatLbl.setObjectName(_fromUtf8("uiFormatLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiFormatLbl, 1, 0, 1, 1)
        self.uiCameraLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiCameraLbl.setObjectName(_fromUtf8("uiCameraLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiCameraLbl, 0, 0, 1, 1)
        self.uiCameraNumberLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiCameraNumberLbl.setObjectName(_fromUtf8("uiCameraNumberLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiCameraNumberLbl, 2, 0, 1, 1)
        self.uiCalibratedFocalLengthLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiCalibratedFocalLengthLbl.setObjectName(_fromUtf8("uiCalibratedFocalLengthLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiCalibratedFocalLengthLbl, 3, 0, 1, 1)
        self.uiCassetteEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiCassetteEdit.setObjectName(_fromUtf8("uiCassetteEdit"))
        self.uiMiddleGridLayout.addWidget(self.uiCassetteEdit, 4, 1, 1, 1)
        self.uiFilmMakeLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiFilmMakeLbl.setObjectName(_fromUtf8("uiFilmMakeLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiFilmMakeLbl, 6, 0, 1, 1)
        self.uiFilmMakeCombo = QtGui.QComboBox(self.layoutWidget1)
        self.uiFilmMakeCombo.setEditable(True)
        self.uiFilmMakeCombo.setObjectName(_fromUtf8("uiFilmMakeCombo"))
        self.uiMiddleGridLayout.addWidget(self.uiFilmMakeCombo, 6, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiFormat1Edit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiFormat1Edit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFormat1Edit.setReadOnly(True)
        self.uiFormat1Edit.setObjectName(_fromUtf8("uiFormat1Edit"))
        self.horizontalLayout_2.addWidget(self.uiFormat1Edit)
        self.uiFormatXLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiFormatXLbl.setObjectName(_fromUtf8("uiFormatXLbl"))
        self.horizontalLayout_2.addWidget(self.uiFormatXLbl)
        self.uiFormat2Edit = QtGui.QLineEdit(self.layoutWidget1)
        self.uiFormat2Edit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFormat2Edit.setReadOnly(True)
        self.uiFormat2Edit.setObjectName(_fromUtf8("uiFormat2Edit"))
        self.horizontalLayout_2.addWidget(self.uiFormat2Edit)
        self.uiMiddleGridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.uiMiddleGridLayout.addWidget(self.line_7, 5, 0, 1, 2)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.uiMiddleGridLayout.addWidget(self.line, 8, 0, 1, 2)
        self.uiCommentsLbl = QtGui.QLabel(self.layoutWidget1)
        self.uiCommentsLbl.setObjectName(_fromUtf8("uiCommentsLbl"))
        self.uiMiddleGridLayout.addWidget(self.uiCommentsLbl, 9, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.layoutWidget1)
        self.label_38.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.uiMiddleGridLayout.addWidget(self.label_38, 6, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget1)
        self.label_37.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.uiMiddleGridLayout.addWidget(self.label_37, 0, 2, 1, 1)
        self.uiCommentsPTxt = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.uiCommentsPTxt.setObjectName(_fromUtf8("uiCommentsPTxt"))
        self.uiMiddleGridLayout.addWidget(self.uiCommentsPTxt, 10, 0, 1, 2)
        self.gridLayoutWidget_2 = QtGui.QWidget(apisFilmDialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 301, 371))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.uiLeftGridLayout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.uiLeftGridLayout.setMargin(0)
        self.uiLeftGridLayout.setObjectName(_fromUtf8("uiLeftGridLayout"))
        self.uiMilitaryNumberEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.uiMilitaryNumberEdit.setObjectName(_fromUtf8("uiMilitaryNumberEdit"))
        self.uiLeftGridLayout.addWidget(self.uiMilitaryNumberEdit, 6, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.uiLeftGridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.uiImageCountEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiImageCountEdit.sizePolicy().hasHeightForWidth())
        self.uiImageCountEdit.setSizePolicy(sizePolicy)
        self.uiImageCountEdit.setObjectName(_fromUtf8("uiImageCountEdit"))
        self.uiLeftGridLayout.addWidget(self.uiImageCountEdit, 3, 1, 1, 1)
        self.uiFlightDate = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.uiFlightDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFlightDate.setReadOnly(True)
        self.uiFlightDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiFlightDate.setObjectName(_fromUtf8("uiFlightDate"))
        self.uiLeftGridLayout.addWidget(self.uiFlightDate, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.uiLeftGridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.uiFilmModeCombo = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.uiFilmModeCombo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFilmModeCombo.sizePolicy().hasHeightForWidth())
        self.uiFilmModeCombo.setSizePolicy(sizePolicy)
        self.uiFilmModeCombo.setEditable(True)
        self.uiFilmModeCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiFilmModeCombo.setObjectName(_fromUtf8("uiFilmModeCombo"))
        self.uiFilmModeCombo.addItem(_fromUtf8(""))
        self.uiFilmModeCombo.addItem(_fromUtf8(""))
        self.uiLeftGridLayout.addWidget(self.uiFilmModeCombo, 4, 1, 1, 1)
        self.uiOldMilitaryNumberEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.uiOldMilitaryNumberEdit.setObjectName(_fromUtf8("uiOldMilitaryNumberEdit"))
        self.uiLeftGridLayout.addWidget(self.uiOldMilitaryNumberEdit, 7, 1, 1, 1)
        self.uiImageCountLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiImageCountLbl.setObjectName(_fromUtf8("uiImageCountLbl"))
        self.uiLeftGridLayout.addWidget(self.uiImageCountLbl, 3, 0, 1, 1)
        self.uiOldMilitaryNumberLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiOldMilitaryNumberLbl.setObjectName(_fromUtf8("uiOldMilitaryNumberLbl"))
        self.uiLeftGridLayout.addWidget(self.uiOldMilitaryNumberLbl, 7, 0, 1, 1)
        self.uiProducerLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiProducerLbl.setObjectName(_fromUtf8("uiProducerLbl"))
        self.uiLeftGridLayout.addWidget(self.uiProducerLbl, 1, 0, 1, 1)
        self.uiFilmModeLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiFilmModeLbl.setObjectName(_fromUtf8("uiFilmModeLbl"))
        self.uiLeftGridLayout.addWidget(self.uiFilmModeLbl, 4, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.uiLeftGridLayout.addWidget(self.line_2, 2, 0, 1, 2)
        self.uiFlightDateLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiFlightDateLbl.setObjectName(_fromUtf8("uiFlightDateLbl"))
        self.uiLeftGridLayout.addWidget(self.uiFlightDateLbl, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.uiLeftGridLayout.addWidget(self.line_3, 5, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.uiLeftGridLayout.addWidget(self.line_4, 8, 0, 1, 2)
        self.uiCopyrightCombo = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.uiCopyrightCombo.setEditable(True)
        self.uiCopyrightCombo.setObjectName(_fromUtf8("uiCopyrightCombo"))
        self.uiLeftGridLayout.addWidget(self.uiCopyrightCombo, 9, 1, 1, 1)
        self.uiMilitaryNumberLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiMilitaryNumberLbl.setObjectName(_fromUtf8("uiMilitaryNumberLbl"))
        self.uiLeftGridLayout.addWidget(self.uiMilitaryNumberLbl, 6, 0, 1, 1)
        self.uiProjectList = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.uiProjectList.setObjectName(_fromUtf8("uiProjectList"))
        self.uiLeftGridLayout.addWidget(self.uiProjectList, 12, 0, 2, 2)
        self.uiCopyrightLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiCopyrightLbl.setObjectName(_fromUtf8("uiCopyrightLbl"))
        self.uiLeftGridLayout.addWidget(self.uiCopyrightLbl, 9, 0, 1, 1)
        self.uiProjectLbl = QtGui.QLabel(self.gridLayoutWidget_2)
        self.uiProjectLbl.setObjectName(_fromUtf8("uiProjectLbl"))
        self.uiLeftGridLayout.addWidget(self.uiProjectLbl, 10, 0, 1, 1)
        self.uiProjectSelectionCombo = QtGui.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiProjectSelectionCombo.sizePolicy().hasHeightForWidth())
        self.uiProjectSelectionCombo.setSizePolicy(sizePolicy)
        self.uiProjectSelectionCombo.setEditable(True)
        self.uiProjectSelectionCombo.setObjectName(_fromUtf8("uiProjectSelectionCombo"))
        self.uiLeftGridLayout.addWidget(self.uiProjectSelectionCombo, 10, 1, 1, 1)
        self.uiAddProjectBtn = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.uiAddProjectBtn.setEnabled(False)
        self.uiAddProjectBtn.setIcon(icon5)
        self.uiAddProjectBtn.setObjectName(_fromUtf8("uiAddProjectBtn"))
        self.uiLeftGridLayout.addWidget(self.uiAddProjectBtn, 10, 2, 1, 1)
        self.uiRemoveProjectBtn = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.uiRemoveProjectBtn.setEnabled(False)
        self.uiRemoveProjectBtn.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiRemoveProjectBtn.setIcon(icon12)
        self.uiRemoveProjectBtn.setObjectName(_fromUtf8("uiRemoveProjectBtn"))
        self.uiLeftGridLayout.addWidget(self.uiRemoveProjectBtn, 12, 2, 1, 1)
        self.uiProducerEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.uiProducerEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiProducerEdit.setReadOnly(True)
        self.uiProducerEdit.setObjectName(_fromUtf8("uiProducerEdit"))
        self.uiLeftGridLayout.addWidget(self.uiProducerEdit, 1, 1, 1, 1)
        self.line_10 = QtGui.QFrame(apisFilmDialog)
        self.line_10.setGeometry(QtCore.QRect(310, 60, 20, 371))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(apisFilmDialog)
        self.line_11.setGeometry(QtCore.QRect(600, 60, 20, 371))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(apisFilmDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 490, 851, 25))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiInitalEntryLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiInitalEntryLbl.sizePolicy().hasHeightForWidth())
        self.uiInitalEntryLbl.setSizePolicy(sizePolicy)
        self.uiInitalEntryLbl.setObjectName(_fromUtf8("uiInitalEntryLbl"))
        self.horizontalLayout.addWidget(self.uiInitalEntryLbl)
        self.uiInitalEntryDate = QtGui.QDateEdit(self.horizontalLayoutWidget_2)
        self.uiInitalEntryDate.setEnabled(True)
        self.uiInitalEntryDate.setAutoFillBackground(False)
        self.uiInitalEntryDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiInitalEntryDate.setReadOnly(True)
        self.uiInitalEntryDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiInitalEntryDate.setObjectName(_fromUtf8("uiInitalEntryDate"))
        self.horizontalLayout.addWidget(self.uiInitalEntryDate)
        self.uiLastChangesLbl = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.uiLastChangesLbl.setObjectName(_fromUtf8("uiLastChangesLbl"))
        self.horizontalLayout.addWidget(self.uiLastChangesLbl)
        self.uiLastChangesDate = QtGui.QDateEdit(self.horizontalLayoutWidget_2)
        self.uiLastChangesDate.setEnabled(True)
        self.uiLastChangesDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiLastChangesDate.setReadOnly(True)
        self.uiLastChangesDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiLastChangesDate.setObjectName(_fromUtf8("uiLastChangesDate"))
        self.horizontalLayout.addWidget(self.uiLastChangesDate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.uiSaveBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.uiSaveBtn.setEnabled(False)
        self.uiSaveBtn.setAutoDefault(False)
        self.uiSaveBtn.setObjectName(_fromUtf8("uiSaveBtn"))
        self.horizontalLayout.addWidget(self.uiSaveBtn)
        self.uiCancelBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.uiCancelBtn.setEnabled(False)
        self.uiCancelBtn.setAutoDefault(False)
        self.uiCancelBtn.setObjectName(_fromUtf8("uiCancelBtn"))
        self.horizontalLayout.addWidget(self.uiCancelBtn)
        self.uiOkBtn = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.uiOkBtn.setAutoDefault(False)
        self.uiOkBtn.setObjectName(_fromUtf8("uiOkBtn"))
        self.horizontalLayout.addWidget(self.uiOkBtn)

        self.retranslateUi(apisFilmDialog)
        QtCore.QMetaObject.connectSlotsByName(apisFilmDialog)
        apisFilmDialog.setTabOrder(self.uiFilmMakeCombo, self.uiFilmMakeEdit)
        apisFilmDialog.setTabOrder(self.uiFilmMakeEdit, self.uiCassetteEdit)
        apisFilmDialog.setTabOrder(self.uiCassetteEdit, self.uiCameraCombo)
        apisFilmDialog.setTabOrder(self.uiCameraCombo, self.uiCameraNumberEdit)
        apisFilmDialog.setTabOrder(self.uiCameraNumberEdit, self.uiCalibratedFocalLengthEdit)
        apisFilmDialog.setTabOrder(self.uiCalibratedFocalLengthEdit, self.uiFormat1Edit)
        apisFilmDialog.setTabOrder(self.uiFormat1Edit, self.uiFormat2Edit)

    def retranslateUi(self, apisFilmDialog):
        apisFilmDialog.setWindowTitle(_translate("apisFilmDialog", "APIS Film", None))
        self.uiFilmSelectionBtn.setText(_translate("apisFilmDialog", "Filmnummer", None))
        self.uiCurrentFilmCountEdit.setText(_translate("apisFilmDialog", "1", None))
        self.label.setText(_translate("apisFilmDialog", "of", None))
        self.uiTotalFilmCountLbl.setText(_translate("apisFilmDialog", "9999", None))
        self.uiNewFilmBtn.setText(_translate("apisFilmDialog", "Neuer Film", None))
        self.uiSearchFilmBtn.setText(_translate("apisFilmDialog", "Film suchen", None))
        self.uiShowFlightPathBtn.setToolTip(_translate("apisFilmDialog", "Flugweg des Filmes in QGIS anzeigen", None))
        self.uiShowFlightPathBtn.setText(_translate("apisFilmDialog", "Flugweg anzeigen", None))
        self.uiListSitesOfFilmBtn.setText(_translate("apisFilmDialog", "Fundorte des Filmes", None))
        self.uiListSitesByYearBtn.setText(_translate("apisFilmDialog", "Fundorte eines Jahres", None))
        self.uiListImagesOfFilmBtn.setText(_translate("apisFilmDialog", "Bilder des Films", None))
        self.uiExtractGpsFromImagesBtn.setText(_translate("apisFilmDialog", "GPS extrahieren", None))
        self.uiExportPdfBtn.setText(_translate("apisFilmDialog", "PDF exportieren", None))
        self.uiDepartureTimeLbl.setText(_translate("apisFilmDialog", "Zeit:", None))
        self.uiDepartureTime.setDisplayFormat(_translate("apisFilmDialog", "h:mm", None))
        self.uiDepartureAirportLbl.setText(_translate("apisFilmDialog", "Flugplatz:", None))
        self.uiArrivalLbl.setText(_translate("apisFilmDialog", "Ankunft:", None))
        self.uiFlightDurationLbl.setText(_translate("apisFilmDialog", "Flugdauer:", None))
        self.uiAirplaneLbl.setText(_translate("apisFilmDialog", "Flugzeug:", None))
        self.uiPhotographerLbl.setText(_translate("apisFilmDialog", "Fotograf:", None))
        self.uiPilotLbl.setText(_translate("apisFilmDialog", "Pilot:", None))
        self.uiDepartureLbl.setText(_translate("apisFilmDialog", "Abflug:", None))
        self.uiArrivalTimeLbl.setText(_translate("apisFilmDialog", "Zeit:", None))
        self.uiArrivalAirportLbl.setText(_translate("apisFilmDialog", "Flugplatz:", None))
        self.uiArrivalTime.setDisplayFormat(_translate("apisFilmDialog", "h:mm", None))
        self.uiTargetLbl.setText(_translate("apisFilmDialog", "Target:", None))
        self.uiWeatherLbl.setText(_translate("apisFilmDialog", "Wetter:", None))
        self.uiFilmModeLbl_2.setText(_translate("apisFilmDialog", "Art:", None))
        self.uiCassetteLbl.setText(_translate("apisFilmDialog", "Kasette:", None))
        self.uiFormatLbl.setText(_translate("apisFilmDialog", "Format:", None))
        self.uiCameraLbl.setText(_translate("apisFilmDialog", "Kamera:", None))
        self.uiCameraNumberLbl.setText(_translate("apisFilmDialog", "Kamera-Nr.:", None))
        self.uiCalibratedFocalLengthLbl.setToolTip(_translate("apisFilmDialog", "Kammerkonstante \'5.7 mm\'", None))
        self.uiCalibratedFocalLengthLbl.setWhatsThis(_translate("apisFilmDialog", "<html><head/><body><p>Beschrreibung zu Kammerkonsante + Beispiele</p></body></html>", None))
        self.uiCalibratedFocalLengthLbl.setText(_translate("apisFilmDialog", "Kammerkonstante:", None))
        self.uiFilmMakeLbl.setText(_translate("apisFilmDialog", "Film:", None))
        self.uiFormatXLbl.setText(_translate("apisFilmDialog", "x", None))
        self.uiCommentsLbl.setText(_translate("apisFilmDialog", "Kommentar:", None))
        self.label_38.setText(_translate("apisFilmDialog", "*", None))
        self.label_37.setText(_translate("apisFilmDialog", "*", None))
        self.label_5.setText(_translate("apisFilmDialog", "*", None))
        self.uiFlightDate.setDisplayFormat(_translate("apisFilmDialog", "dd.MM.yyyy", None))
        self.label_3.setText(_translate("apisFilmDialog", "*", None))
        self.uiFilmModeCombo.setItemText(0, _translate("apisFilmDialog", "schräg", None))
        self.uiFilmModeCombo.setItemText(1, _translate("apisFilmDialog", "senk.", None))
        self.uiImageCountLbl.setText(_translate("apisFilmDialog", "Bildanzahl:", None))
        self.uiOldMilitaryNumberLbl.setText(_translate("apisFilmDialog", "Alte Mil. Nr.:", None))
        self.uiProducerLbl.setText(_translate("apisFilmDialog", "Hersteller:", None))
        self.uiFilmModeLbl.setText(_translate("apisFilmDialog", "Weise:", None))
        self.uiFlightDateLbl.setText(_translate("apisFilmDialog", "Flugdatum:", None))
        self.uiMilitaryNumberLbl.setText(_translate("apisFilmDialog", "Militär Nr.:", None))
        self.uiCopyrightLbl.setText(_translate("apisFilmDialog", "Copyright:", None))
        self.uiProjectLbl.setText(_translate("apisFilmDialog", "Projekt(e):", None))
        self.uiInitalEntryLbl.setText(_translate("apisFilmDialog", "Ersteintrag:", None))
        self.uiInitalEntryDate.setDisplayFormat(_translate("apisFilmDialog", "dd.MM.yyyy", None))
        self.uiLastChangesLbl.setText(_translate("apisFilmDialog", "Letzte Bearbeitung:", None))
        self.uiLastChangesDate.setDisplayFormat(_translate("apisFilmDialog", "dd.MM.yyyy", None))
        self.uiSaveBtn.setText(_translate("apisFilmDialog", "Speichern", None))
        self.uiCancelBtn.setText(_translate("apisFilmDialog", "Abbrechen", None))
        self.uiOkBtn.setText(_translate("apisFilmDialog", "OK", None))

import resource_rc
