# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_findspot_form.ui'
#
# Created: Wed Apr 27 09:52:17 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisFindSpotDialog(object):
    def setupUi(self, apisFindSpotDialog):
        apisFindSpotDialog.setObjectName(_fromUtf8("apisFindSpotDialog"))
        apisFindSpotDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisFindSpotDialog.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisFindSpotDialog.setWindowIcon(icon)
        apisFindSpotDialog.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(apisFindSpotDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiDatingSourceCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiDatingSourceCombo.setEditable(True)
        self.uiDatingSourceCombo.setObjectName(_fromUtf8("uiDatingSourceCombo"))
        self.gridLayout.addWidget(self.uiDatingSourceCombo, 18, 1, 1, 4)
        self.label_11 = QtGui.QLabel(apisFindSpotDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 18, 0, 1, 1)
        self.uiFineDatingToCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiFineDatingToCombo.setEditable(True)
        self.uiFineDatingToCombo.setObjectName(_fromUtf8("uiFineDatingToCombo"))
        self.gridLayout.addWidget(self.uiFineDatingToCombo, 17, 4, 1, 1)
        self.label_10 = QtGui.QLabel(apisFindSpotDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 17, 3, 1, 1)
        self.uiFineDatingFromCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiFineDatingFromCombo.setEditable(True)
        self.uiFineDatingFromCombo.setObjectName(_fromUtf8("uiFineDatingFromCombo"))
        self.gridLayout.addWidget(self.uiFineDatingFromCombo, 17, 2, 1, 1)
        self.label_9 = QtGui.QLabel(apisFindSpotDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 17, 1, 1, 1)
        self.label_8 = QtGui.QLabel(apisFindSpotDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 17, 0, 1, 1)
        self.label_27 = QtGui.QLabel(apisFindSpotDialog)
        self.label_27.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 16, 5, 1, 1)
        self.uiDatingCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiDatingCombo.setEditable(True)
        self.uiDatingCombo.setObjectName(_fromUtf8("uiDatingCombo"))
        self.gridLayout.addWidget(self.uiDatingCombo, 16, 1, 1, 4)
        self.label_26 = QtGui.QLabel(apisFindSpotDialog)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 16, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(433, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 6)
        self.uiAreaEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiAreaEdit.sizePolicy().hasHeightForWidth())
        self.uiAreaEdit.setSizePolicy(sizePolicy)
        self.uiAreaEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiAreaEdit.setReadOnly(True)
        self.uiAreaEdit.setObjectName(_fromUtf8("uiAreaEdit"))
        self.gridLayout.addWidget(self.uiAreaEdit, 14, 1, 1, 4)
        self.label_33 = QtGui.QLabel(apisFindSpotDialog)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 14, 0, 1, 1)
        self.uiCommentEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCommentEdit.sizePolicy().hasHeightForWidth())
        self.uiCommentEdit.setSizePolicy(sizePolicy)
        self.uiCommentEdit.setObjectName(_fromUtf8("uiCommentEdit"))
        self.gridLayout.addWidget(self.uiCommentEdit, 13, 1, 1, 4)
        self.uiCommentBtn = QtGui.QPushButton(apisFindSpotDialog)
        self.uiCommentBtn.setAutoDefault(False)
        self.uiCommentBtn.setObjectName(_fromUtf8("uiCommentBtn"))
        self.gridLayout.addWidget(self.uiCommentBtn, 13, 0, 1, 1)
        self.label_29 = QtGui.QLabel(apisFindSpotDialog)
        self.label_29.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 12, 5, 1, 1)
        self.label_31 = QtGui.QLabel(apisFindSpotDialog)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 10, 0, 1, 1)
        self.uiPlotNumberEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPlotNumberEdit.sizePolicy().hasHeightForWidth())
        self.uiPlotNumberEdit.setSizePolicy(sizePolicy)
        self.uiPlotNumberEdit.setObjectName(_fromUtf8("uiPlotNumberEdit"))
        self.gridLayout.addWidget(self.uiPlotNumberEdit, 9, 1, 1, 4)
        self.uiPlotNumberBtn = QtGui.QPushButton(apisFindSpotDialog)
        self.uiPlotNumberBtn.setAutoDefault(False)
        self.uiPlotNumberBtn.setObjectName(_fromUtf8("uiPlotNumberBtn"))
        self.gridLayout.addWidget(self.uiPlotNumberBtn, 9, 0, 1, 1)
        self.label_35 = QtGui.QLabel(apisFindSpotDialog)
        self.label_35.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 8, 5, 1, 1)
        self.uiCaseWorkerEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCaseWorkerEdit.sizePolicy().hasHeightForWidth())
        self.uiCaseWorkerEdit.setSizePolicy(sizePolicy)
        self.uiCaseWorkerEdit.setStyleSheet(_fromUtf8(""))
        self.uiCaseWorkerEdit.setReadOnly(False)
        self.uiCaseWorkerEdit.setObjectName(_fromUtf8("uiCaseWorkerEdit"))
        self.gridLayout.addWidget(self.uiCaseWorkerEdit, 4, 1, 1, 4)
        self.label_25 = QtGui.QLabel(apisFindSpotDialog)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 4, 0, 1, 1)
        self.uiFieldNameEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFieldNameEdit.sizePolicy().hasHeightForWidth())
        self.uiFieldNameEdit.setSizePolicy(sizePolicy)
        self.uiFieldNameEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFieldNameEdit.setReadOnly(True)
        self.uiFieldNameEdit.setObjectName(_fromUtf8("uiFieldNameEdit"))
        self.gridLayout.addWidget(self.uiFieldNameEdit, 3, 1, 1, 4)
        self.label_22 = QtGui.QLabel(apisFindSpotDialog)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)
        self.uiCadastralCommunityNumberEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCadastralCommunityNumberEdit.sizePolicy().hasHeightForWidth())
        self.uiCadastralCommunityNumberEdit.setSizePolicy(sizePolicy)
        self.uiCadastralCommunityNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCadastralCommunityNumberEdit.setReadOnly(True)
        self.uiCadastralCommunityNumberEdit.setObjectName(_fromUtf8("uiCadastralCommunityNumberEdit"))
        self.gridLayout.addWidget(self.uiCadastralCommunityNumberEdit, 2, 1, 1, 4)
        self.label_24 = QtGui.QLabel(apisFindSpotDialog)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 2, 0, 1, 1)
        self.uiCadastralCommunityEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCadastralCommunityEdit.sizePolicy().hasHeightForWidth())
        self.uiCadastralCommunityEdit.setSizePolicy(sizePolicy)
        self.uiCadastralCommunityEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCadastralCommunityEdit.setReadOnly(True)
        self.uiCadastralCommunityEdit.setObjectName(_fromUtf8("uiCadastralCommunityEdit"))
        self.gridLayout.addWidget(self.uiCadastralCommunityEdit, 1, 1, 1, 4)
        self.label_23 = QtGui.QLabel(apisFindSpotDialog)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 1, 0, 1, 1)
        self.uiCultureCombo = QtGui.QComboBox(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCultureCombo.sizePolicy().hasHeightForWidth())
        self.uiCultureCombo.setSizePolicy(sizePolicy)
        self.uiCultureCombo.setEditable(True)
        self.uiCultureCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.uiCultureCombo.setObjectName(_fromUtf8("uiCultureCombo"))
        self.gridLayout.addWidget(self.uiCultureCombo, 21, 1, 1, 4)
        self.uiPreservationStateEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPreservationStateEdit.sizePolicy().hasHeightForWidth())
        self.uiPreservationStateEdit.setSizePolicy(sizePolicy)
        self.uiPreservationStateEdit.setPlaceholderText(_fromUtf8(""))
        self.uiPreservationStateEdit.setObjectName(_fromUtf8("uiPreservationStateEdit"))
        self.gridLayout.addWidget(self.uiPreservationStateEdit, 6, 1, 1, 4)
        self.label_13 = QtGui.QLabel(apisFindSpotDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 19, 1, 1, 1)
        self.uiFindSpotCreationCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiFindSpotCreationCombo.setEditable(True)
        self.uiFindSpotCreationCombo.setObjectName(_fromUtf8("uiFindSpotCreationCombo"))
        self.gridLayout.addWidget(self.uiFindSpotCreationCombo, 12, 1, 1, 4)
        self.label_34 = QtGui.QLabel(apisFindSpotDialog)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 8, 0, 1, 1)
        self.label_37 = QtGui.QLabel(apisFindSpotDialog)
        self.label_37.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 18, 5, 1, 1)
        self.label_15 = QtGui.QLabel(apisFindSpotDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 21, 0, 1, 1)
        self.label_17 = QtGui.QLabel(apisFindSpotDialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 23, 0, 1, 1)
        self.label_30 = QtGui.QLabel(apisFindSpotDialog)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 6, 0, 1, 1)
        self.uiFindingTypeCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiFindingTypeCombo.setEditable(True)
        self.uiFindingTypeCombo.setObjectName(_fromUtf8("uiFindingTypeCombo"))
        self.gridLayout.addWidget(self.uiFindingTypeCombo, 22, 1, 1, 4)
        self.uiFindingTypeDetailCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiFindingTypeDetailCombo.setEditable(True)
        self.uiFindingTypeDetailCombo.setObjectName(_fromUtf8("uiFindingTypeDetailCombo"))
        self.gridLayout.addWidget(self.uiFindingTypeDetailCombo, 23, 1, 1, 4)
        self.label_32 = QtGui.QLabel(apisFindSpotDialog)
        self.label_32.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 22, 5, 1, 1)
        self.uiBdaNumberEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiBdaNumberEdit.sizePolicy().hasHeightForWidth())
        self.uiBdaNumberEdit.setSizePolicy(sizePolicy)
        self.uiBdaNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiBdaNumberEdit.setObjectName(_fromUtf8("uiBdaNumberEdit"))
        self.gridLayout.addWidget(self.uiBdaNumberEdit, 10, 1, 1, 4)
        self.label_12 = QtGui.QLabel(apisFindSpotDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 19, 0, 1, 1)
        self.label_36 = QtGui.QLabel(apisFindSpotDialog)
        self.label_36.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 4, 5, 1, 1)
        self.label_28 = QtGui.QLabel(apisFindSpotDialog)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 12, 0, 1, 1)
        self.label_7 = QtGui.QLabel(apisFindSpotDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.uiFirstReportYearEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFirstReportYearEdit.sizePolicy().hasHeightForWidth())
        self.uiFirstReportYearEdit.setSizePolicy(sizePolicy)
        self.uiFirstReportYearEdit.setMaxLength(4)
        self.uiFirstReportYearEdit.setObjectName(_fromUtf8("uiFirstReportYearEdit"))
        self.gridLayout.addWidget(self.uiFirstReportYearEdit, 5, 1, 1, 4)
        self.label_21 = QtGui.QLabel(apisFindSpotDialog)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.uiAbsoluteDatingToEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiAbsoluteDatingToEdit.sizePolicy().hasHeightForWidth())
        self.uiAbsoluteDatingToEdit.setSizePolicy(sizePolicy)
        self.uiAbsoluteDatingToEdit.setObjectName(_fromUtf8("uiAbsoluteDatingToEdit"))
        self.gridLayout.addWidget(self.uiAbsoluteDatingToEdit, 19, 4, 1, 1)
        self.uiAbsoluteDatingFromEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiAbsoluteDatingFromEdit.sizePolicy().hasHeightForWidth())
        self.uiAbsoluteDatingFromEdit.setSizePolicy(sizePolicy)
        self.uiAbsoluteDatingFromEdit.setObjectName(_fromUtf8("uiAbsoluteDatingFromEdit"))
        self.gridLayout.addWidget(self.uiAbsoluteDatingFromEdit, 19, 2, 1, 1)
        self.label_14 = QtGui.QLabel(apisFindSpotDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 19, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(433, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 6)
        spacerItem2 = QtGui.QSpacerItem(433, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 20, 0, 1, 6)
        self.label_16 = QtGui.QLabel(apisFindSpotDialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 22, 0, 1, 1)
        self.uiSiteReliabilityCombo = QtGui.QComboBox(apisFindSpotDialog)
        self.uiSiteReliabilityCombo.setEditable(True)
        self.uiSiteReliabilityCombo.setModelColumn(0)
        self.uiSiteReliabilityCombo.setObjectName(_fromUtf8("uiSiteReliabilityCombo"))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.uiSiteReliabilityCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiSiteReliabilityCombo, 8, 1, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 5)
        self.uiFindSpotNumberEdit = QtGui.QLineEdit(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFindSpotNumberEdit.sizePolicy().hasHeightForWidth())
        self.uiFindSpotNumberEdit.setSizePolicy(sizePolicy)
        self.uiFindSpotNumberEdit.setAutoFillBackground(False)
        self.uiFindSpotNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiFindSpotNumberEdit.setReadOnly(True)
        self.uiFindSpotNumberEdit.setObjectName(_fromUtf8("uiFindSpotNumberEdit"))
        self.gridLayout.addWidget(self.uiFindSpotNumberEdit, 0, 1, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(apisFindSpotDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.uiLiteraturePTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiLiteraturePTxt.setObjectName(_fromUtf8("uiLiteraturePTxt"))
        self.verticalLayout.addWidget(self.uiLiteraturePTxt)
        self.label_2 = QtGui.QLabel(apisFindSpotDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.uiFindingsPTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiFindingsPTxt.setObjectName(_fromUtf8("uiFindingsPTxt"))
        self.verticalLayout.addWidget(self.uiFindingsPTxt)
        self.label_3 = QtGui.QLabel(apisFindSpotDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.uiFindingsStoragePTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiFindingsStoragePTxt.setObjectName(_fromUtf8("uiFindingsStoragePTxt"))
        self.verticalLayout.addWidget(self.uiFindingsStoragePTxt)
        self.label_4 = QtGui.QLabel(apisFindSpotDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.uiMiscellaneousPTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiMiscellaneousPTxt.setObjectName(_fromUtf8("uiMiscellaneousPTxt"))
        self.verticalLayout.addWidget(self.uiMiscellaneousPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(apisFindSpotDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.uiFindingsHistoryPTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiFindingsHistoryPTxt.setObjectName(_fromUtf8("uiFindingsHistoryPTxt"))
        self.verticalLayout_2.addWidget(self.uiFindingsHistoryPTxt)
        self.label_6 = QtGui.QLabel(apisFindSpotDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.uiFindingsInterpretationPTxt = QtGui.QPlainTextEdit(apisFindSpotDialog)
        self.uiFindingsInterpretationPTxt.setObjectName(_fromUtf8("uiFindingsInterpretationPTxt"))
        self.verticalLayout_2.addWidget(self.uiFindingsInterpretationPTxt)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.uiBottomHorizontalLayout = QtGui.QHBoxLayout()
        self.uiBottomHorizontalLayout.setObjectName(_fromUtf8("uiBottomHorizontalLayout"))
        self.uiViewFindSpotBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/layer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiViewFindSpotBtn.setIcon(icon1)
        self.uiViewFindSpotBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiViewFindSpotBtn.setAutoDefault(False)
        self.uiViewFindSpotBtn.setObjectName(_fromUtf8("uiViewFindSpotBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiViewFindSpotBtn)
        self.uiChangeGeometryBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/edit_geometry_polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiChangeGeometryBtn.setIcon(icon2)
        self.uiChangeGeometryBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiChangeGeometryBtn.setAutoDefault(False)
        self.uiChangeGeometryBtn.setObjectName(_fromUtf8("uiChangeGeometryBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiChangeGeometryBtn)
        self.uiViewSiteBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/site.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiViewSiteBtn.setIcon(icon3)
        self.uiViewSiteBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiViewSiteBtn.setAutoDefault(False)
        self.uiViewSiteBtn.setObjectName(_fromUtf8("uiViewSiteBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiViewSiteBtn)
        self.uiListShardingsOfSiteBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/footprints.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListShardingsOfSiteBtn.setIcon(icon4)
        self.uiListShardingsOfSiteBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListShardingsOfSiteBtn.setAutoDefault(False)
        self.uiListShardingsOfSiteBtn.setObjectName(_fromUtf8("uiListShardingsOfSiteBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiListShardingsOfSiteBtn)
        self.uiExportPdfBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/pdf_export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportPdfBtn.setIcon(icon5)
        self.uiExportPdfBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExportPdfBtn.setAutoDefault(False)
        self.uiExportPdfBtn.setObjectName(_fromUtf8("uiExportPdfBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiExportPdfBtn)
        self.uiCloneFindSpotBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/findspot_clone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCloneFindSpotBtn.setIcon(icon6)
        self.uiCloneFindSpotBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiCloneFindSpotBtn.setAutoDefault(False)
        self.uiCloneFindSpotBtn.setObjectName(_fromUtf8("uiCloneFindSpotBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiCloneFindSpotBtn)
        self.uiDeleteFindSpotBtn = QtGui.QPushButton(apisFindSpotDialog)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/findspot_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiDeleteFindSpotBtn.setIcon(icon7)
        self.uiDeleteFindSpotBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiDeleteFindSpotBtn.setAutoDefault(False)
        self.uiDeleteFindSpotBtn.setObjectName(_fromUtf8("uiDeleteFindSpotBtn"))
        self.uiBottomHorizontalLayout.addWidget(self.uiDeleteFindSpotBtn)
        self.gridLayout_2.addLayout(self.uiBottomHorizontalLayout, 2, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiInitalEntryLbl = QtGui.QLabel(apisFindSpotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiInitalEntryLbl.sizePolicy().hasHeightForWidth())
        self.uiInitalEntryLbl.setSizePolicy(sizePolicy)
        self.uiInitalEntryLbl.setObjectName(_fromUtf8("uiInitalEntryLbl"))
        self.horizontalLayout.addWidget(self.uiInitalEntryLbl)
        self.uiInitalEntryDate = QtGui.QDateEdit(apisFindSpotDialog)
        self.uiInitalEntryDate.setEnabled(True)
        self.uiInitalEntryDate.setAutoFillBackground(False)
        self.uiInitalEntryDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiInitalEntryDate.setReadOnly(True)
        self.uiInitalEntryDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiInitalEntryDate.setObjectName(_fromUtf8("uiInitalEntryDate"))
        self.horizontalLayout.addWidget(self.uiInitalEntryDate)
        self.uiLastChangesLbl = QtGui.QLabel(apisFindSpotDialog)
        self.uiLastChangesLbl.setObjectName(_fromUtf8("uiLastChangesLbl"))
        self.horizontalLayout.addWidget(self.uiLastChangesLbl)
        self.uiLastChangesDate = QtGui.QDateEdit(apisFindSpotDialog)
        self.uiLastChangesDate.setEnabled(True)
        self.uiLastChangesDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiLastChangesDate.setReadOnly(True)
        self.uiLastChangesDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiLastChangesDate.setObjectName(_fromUtf8("uiLastChangesDate"))
        self.horizontalLayout.addWidget(self.uiLastChangesDate)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.uiSaveBtn = QtGui.QPushButton(apisFindSpotDialog)
        self.uiSaveBtn.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSaveBtn.setIcon(icon8)
        self.uiSaveBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiSaveBtn.setAutoDefault(False)
        self.uiSaveBtn.setObjectName(_fromUtf8("uiSaveBtn"))
        self.horizontalLayout.addWidget(self.uiSaveBtn)
        self.uiCancelBtn = QtGui.QPushButton(apisFindSpotDialog)
        self.uiCancelBtn.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCancelBtn.setIcon(icon9)
        self.uiCancelBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelBtn.setAutoDefault(False)
        self.uiCancelBtn.setObjectName(_fromUtf8("uiCancelBtn"))
        self.horizontalLayout.addWidget(self.uiCancelBtn)
        self.uiOkBtn = QtGui.QPushButton(apisFindSpotDialog)
        self.uiOkBtn.setIcon(icon8)
        self.uiOkBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiOkBtn.setAutoDefault(False)
        self.uiOkBtn.setObjectName(_fromUtf8("uiOkBtn"))
        self.horizontalLayout.addWidget(self.uiOkBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 3)

        self.retranslateUi(apisFindSpotDialog)
        self.uiSiteReliabilityCombo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(apisFindSpotDialog)
        apisFindSpotDialog.setTabOrder(self.uiFindSpotNumberEdit, self.uiCadastralCommunityEdit)
        apisFindSpotDialog.setTabOrder(self.uiCadastralCommunityEdit, self.uiCadastralCommunityNumberEdit)
        apisFindSpotDialog.setTabOrder(self.uiCadastralCommunityNumberEdit, self.uiFieldNameEdit)
        apisFindSpotDialog.setTabOrder(self.uiFieldNameEdit, self.uiCaseWorkerEdit)
        apisFindSpotDialog.setTabOrder(self.uiCaseWorkerEdit, self.uiFirstReportYearEdit)
        apisFindSpotDialog.setTabOrder(self.uiFirstReportYearEdit, self.uiPreservationStateEdit)
        apisFindSpotDialog.setTabOrder(self.uiPreservationStateEdit, self.uiSiteReliabilityCombo)
        apisFindSpotDialog.setTabOrder(self.uiSiteReliabilityCombo, self.uiPlotNumberBtn)
        apisFindSpotDialog.setTabOrder(self.uiPlotNumberBtn, self.uiPlotNumberEdit)
        apisFindSpotDialog.setTabOrder(self.uiPlotNumberEdit, self.uiBdaNumberEdit)
        apisFindSpotDialog.setTabOrder(self.uiBdaNumberEdit, self.uiFindSpotCreationCombo)
        apisFindSpotDialog.setTabOrder(self.uiFindSpotCreationCombo, self.uiCommentBtn)
        apisFindSpotDialog.setTabOrder(self.uiCommentBtn, self.uiCommentEdit)
        apisFindSpotDialog.setTabOrder(self.uiCommentEdit, self.uiAreaEdit)
        apisFindSpotDialog.setTabOrder(self.uiAreaEdit, self.uiDatingCombo)
        apisFindSpotDialog.setTabOrder(self.uiDatingCombo, self.uiFineDatingFromCombo)
        apisFindSpotDialog.setTabOrder(self.uiFineDatingFromCombo, self.uiFineDatingToCombo)
        apisFindSpotDialog.setTabOrder(self.uiFineDatingToCombo, self.uiDatingSourceCombo)
        apisFindSpotDialog.setTabOrder(self.uiDatingSourceCombo, self.uiAbsoluteDatingFromEdit)
        apisFindSpotDialog.setTabOrder(self.uiAbsoluteDatingFromEdit, self.uiAbsoluteDatingToEdit)
        apisFindSpotDialog.setTabOrder(self.uiAbsoluteDatingToEdit, self.uiCultureCombo)
        apisFindSpotDialog.setTabOrder(self.uiCultureCombo, self.uiFindingTypeCombo)
        apisFindSpotDialog.setTabOrder(self.uiFindingTypeCombo, self.uiFindingTypeDetailCombo)
        apisFindSpotDialog.setTabOrder(self.uiFindingTypeDetailCombo, self.uiLiteraturePTxt)
        apisFindSpotDialog.setTabOrder(self.uiLiteraturePTxt, self.uiFindingsPTxt)
        apisFindSpotDialog.setTabOrder(self.uiFindingsPTxt, self.uiFindingsStoragePTxt)
        apisFindSpotDialog.setTabOrder(self.uiFindingsStoragePTxt, self.uiMiscellaneousPTxt)
        apisFindSpotDialog.setTabOrder(self.uiMiscellaneousPTxt, self.uiFindingsHistoryPTxt)
        apisFindSpotDialog.setTabOrder(self.uiFindingsHistoryPTxt, self.uiFindingsInterpretationPTxt)
        apisFindSpotDialog.setTabOrder(self.uiFindingsInterpretationPTxt, self.uiViewFindSpotBtn)
        apisFindSpotDialog.setTabOrder(self.uiViewFindSpotBtn, self.uiChangeGeometryBtn)
        apisFindSpotDialog.setTabOrder(self.uiChangeGeometryBtn, self.uiViewSiteBtn)
        apisFindSpotDialog.setTabOrder(self.uiViewSiteBtn, self.uiListShardingsOfSiteBtn)
        apisFindSpotDialog.setTabOrder(self.uiListShardingsOfSiteBtn, self.uiExportPdfBtn)
        apisFindSpotDialog.setTabOrder(self.uiExportPdfBtn, self.uiCloneFindSpotBtn)
        apisFindSpotDialog.setTabOrder(self.uiCloneFindSpotBtn, self.uiDeleteFindSpotBtn)
        apisFindSpotDialog.setTabOrder(self.uiDeleteFindSpotBtn, self.uiInitalEntryDate)
        apisFindSpotDialog.setTabOrder(self.uiInitalEntryDate, self.uiLastChangesDate)
        apisFindSpotDialog.setTabOrder(self.uiLastChangesDate, self.uiSaveBtn)
        apisFindSpotDialog.setTabOrder(self.uiSaveBtn, self.uiCancelBtn)
        apisFindSpotDialog.setTabOrder(self.uiCancelBtn, self.uiOkBtn)

    def retranslateUi(self, apisFindSpotDialog):
        apisFindSpotDialog.setWindowTitle(_translate("apisFindSpotDialog", "APIS Funstelle", None))
        self.label_11.setText(_translate("apisFindSpotDialog", "Datierung Quelle:", None))
        self.label_10.setText(_translate("apisFindSpotDialog", "bis:", None))
        self.label_9.setText(_translate("apisFindSpotDialog", "von:", None))
        self.label_8.setText(_translate("apisFindSpotDialog", "Feindatierung", None))
        self.label_27.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_26.setText(_translate("apisFindSpotDialog", "Datierung:", None))
        self.label_33.setText(_translate("apisFindSpotDialog", "Fläche (ha):", None))
        self.uiCommentBtn.setText(_translate("apisFindSpotDialog", "Bemerkung:", None))
        self.label_29.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_31.setText(_translate("apisFindSpotDialog", "BDA Nummer:", None))
        self.uiPlotNumberBtn.setText(_translate("apisFindSpotDialog", "Parz. Nr:", None))
        self.label_35.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_25.setText(_translate("apisFindSpotDialog", "Bearbeiter:", None))
        self.label_22.setText(_translate("apisFindSpotDialog", "Flurname:", None))
        self.label_24.setText(_translate("apisFindSpotDialog", "KG Nummer:", None))
        self.label_23.setText(_translate("apisFindSpotDialog", "Katastralgemeinde:", None))
        self.label_13.setText(_translate("apisFindSpotDialog", "von:", None))
        self.label_34.setText(_translate("apisFindSpotDialog", "Fundstelle ist:", None))
        self.label_37.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_15.setText(_translate("apisFindSpotDialog", "Kultur:", None))
        self.label_17.setText(_translate("apisFindSpotDialog", "Fundart Detail:", None))
        self.label_30.setText(_translate("apisFindSpotDialog", "Erhaltung:", None))
        self.label_32.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_12.setText(_translate("apisFindSpotDialog", "Absolut Datierung:", None))
        self.label_36.setText(_translate("apisFindSpotDialog", "*", None))
        self.label_28.setText(_translate("apisFindSpotDialog", "Erstellt nach:", None))
        self.label_7.setText(_translate("apisFindSpotDialog", "Erstmeldung:", None))
        self.label_21.setText(_translate("apisFindSpotDialog", "Fundstelle Nummer:", None))
        self.label_14.setText(_translate("apisFindSpotDialog", "bis:", None))
        self.label_16.setText(_translate("apisFindSpotDialog", "Fundart:", None))
        self.uiSiteReliabilityCombo.setItemText(0, _translate("apisFindSpotDialog", "sicher", None))
        self.uiSiteReliabilityCombo.setItemText(1, _translate("apisFindSpotDialog", "wahrscheinlich", None))
        self.uiSiteReliabilityCombo.setItemText(2, _translate("apisFindSpotDialog", "fraglich", None))
        self.uiSiteReliabilityCombo.setItemText(3, _translate("apisFindSpotDialog", "kein Fundort", None))
        self.label.setText(_translate("apisFindSpotDialog", "Literatur:", None))
        self.label_2.setText(_translate("apisFindSpotDialog", "Funde:", None))
        self.label_3.setText(_translate("apisFindSpotDialog", "Verbleib:", None))
        self.label_4.setText(_translate("apisFindSpotDialog", "Sonstiges:", None))
        self.label_5.setText(_translate("apisFindSpotDialog", "Fundgeschichte:", None))
        self.label_6.setText(_translate("apisFindSpotDialog", "Befund:", None))
        self.uiViewFindSpotBtn.setText(_translate("apisFindSpotDialog", "Fundstelle in QGIS anzeigen", None))
        self.uiChangeGeometryBtn.setText(_translate("apisFindSpotDialog", "Geometrie ändern", None))
        self.uiViewSiteBtn.setText(_translate("apisFindSpotDialog", "Fundort Details öffnen", None))
        self.uiListShardingsOfSiteBtn.setText(_translate("apisFindSpotDialog", "Begehung", None))
        self.uiExportPdfBtn.setText(_translate("apisFindSpotDialog", "PDF exportieren", None))
        self.uiCloneFindSpotBtn.setText(_translate("apisFindSpotDialog", "Fundstelle klonen", None))
        self.uiDeleteFindSpotBtn.setText(_translate("apisFindSpotDialog", "Fundstelle löschen", None))
        self.uiInitalEntryLbl.setText(_translate("apisFindSpotDialog", "Ersteintrag:", None))
        self.uiInitalEntryDate.setDisplayFormat(_translate("apisFindSpotDialog", "dd.MM.yyyy", None))
        self.uiLastChangesLbl.setText(_translate("apisFindSpotDialog", "Letzte Bearbeitung:", None))
        self.uiLastChangesDate.setDisplayFormat(_translate("apisFindSpotDialog", "dd.MM.yyyy", None))
        self.uiSaveBtn.setText(_translate("apisFindSpotDialog", "Speichern", None))
        self.uiCancelBtn.setText(_translate("apisFindSpotDialog", "Abbrechen", None))
        self.uiOkBtn.setText(_translate("apisFindSpotDialog", "OK", None))

import resource_rc
