# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_search_form.ui'
#
# Created: Wed Apr 26 18:23:44 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSearchDialog(object):
    def setupUi(self, apisSearchDialog):
        apisSearchDialog.setObjectName(_fromUtf8("apisSearchDialog"))
        apisSearchDialog.resize(314, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisSearchDialog.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiSearchTab = QtGui.QTabWidget(self.dockWidgetContents)
        self.uiSearchTab.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchTab.sizePolicy().hasHeightForWidth())
        self.uiSearchTab.setSizePolicy(sizePolicy)
        self.uiSearchTab.setObjectName(_fromUtf8("uiSearchTab"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.uiSearchImageRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchImageRBtn.setChecked(True)
        self.uiSearchImageRBtn.setObjectName(_fromUtf8("uiSearchImageRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchImageRBtn)
        self.uiSearchSiteRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchSiteRBtn.setObjectName(_fromUtf8("uiSearchSiteRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchSiteRBtn)
        self.uiSearchFindspotRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchFindspotRBtn.setObjectName(_fromUtf8("uiSearchFindspotRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchFindspotRBtn)
        self.line_8 = QtGui.QFrame(self.tab_9)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_8.addWidget(self.line_8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.uiSpatialSearchBtn = QtGui.QPushButton(self.tab_9)
        self.uiSpatialSearchBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSpatialSearchBtn.setIcon(icon1)
        self.uiSpatialSearchBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiSpatialSearchBtn.setObjectName(_fromUtf8("uiSpatialSearchBtn"))
        self.horizontalLayout_8.addWidget(self.uiSpatialSearchBtn)
        self.label_13 = QtGui.QLabel(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.line_9 = QtGui.QFrame(self.tab_9)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_8.addWidget(self.line_9)
        self.label = QtGui.QLabel(self.tab_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiSearchByMapLayerCombo = QgsMapLayerComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByMapLayerCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByMapLayerCombo.setSizePolicy(sizePolicy)
        self.uiSearchByMapLayerCombo.setObjectName(_fromUtf8("uiSearchByMapLayerCombo"))
        self.horizontalLayout.addWidget(self.uiSearchByMapLayerCombo)
        self.uiSearchByMapLayerBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByMapLayerBtn.setEnabled(True)
        self.uiSearchByMapLayerBtn.setText(_fromUtf8(""))
        self.uiSearchByMapLayerBtn.setIcon(icon1)
        self.uiSearchByMapLayerBtn.setObjectName(_fromUtf8("uiSearchByMapLayerBtn"))
        self.horizontalLayout.addWidget(self.uiSearchByMapLayerBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.line_10 = QtGui.QFrame(self.tab_9)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_8.addWidget(self.line_10)
        self.label_7 = QtGui.QLabel(self.tab_9)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.uiSearchByCadastralCommunityCombo = QtGui.QComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByCadastralCommunityCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByCadastralCommunityCombo.setSizePolicy(sizePolicy)
        self.uiSearchByCadastralCommunityCombo.setEditable(True)
        self.uiSearchByCadastralCommunityCombo.setObjectName(_fromUtf8("uiSearchByCadastralCommunityCombo"))
        self.horizontalLayout_10.addWidget(self.uiSearchByCadastralCommunityCombo)
        self.uiSearchByCadastralCommunityBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByCadastralCommunityBtn.setText(_fromUtf8(""))
        self.uiSearchByCadastralCommunityBtn.setIcon(icon1)
        self.uiSearchByCadastralCommunityBtn.setObjectName(_fromUtf8("uiSearchByCadastralCommunityBtn"))
        self.horizontalLayout_10.addWidget(self.uiSearchByCadastralCommunityBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.line_7 = QtGui.QFrame(self.tab_9)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_8.addWidget(self.line_7)
        self.label_8 = QtGui.QLabel(self.tab_9)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.uiSearchByCountryCombo = QtGui.QComboBox(self.tab_9)
        self.uiSearchByCountryCombo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByCountryCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByCountryCombo.setSizePolicy(sizePolicy)
        self.uiSearchByCountryCombo.setEditable(True)
        self.uiSearchByCountryCombo.setObjectName(_fromUtf8("uiSearchByCountryCombo"))
        self.horizontalLayout_11.addWidget(self.uiSearchByCountryCombo)
        self.uiSearchByCountryBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByCountryBtn.setEnabled(False)
        self.uiSearchByCountryBtn.setText(_fromUtf8(""))
        self.uiSearchByCountryBtn.setIcon(icon1)
        self.uiSearchByCountryBtn.setObjectName(_fromUtf8("uiSearchByCountryBtn"))
        self.horizontalLayout_11.addWidget(self.uiSearchByCountryBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.uiSearchTab.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.tab_10)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.uiSiteTab = QtGui.QWidget()
        self.uiSiteTab.setObjectName(_fromUtf8("uiSiteTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiSiteTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.uiSiteTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.uiSearchSiteNumberCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchSiteNumberCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchSiteNumberCombo.setSizePolicy(sizePolicy)
        self.uiSearchSiteNumberCombo.setEditable(True)
        self.uiSearchSiteNumberCombo.setObjectName(_fromUtf8("uiSearchSiteNumberCombo"))
        self.horizontalLayout_6.addWidget(self.uiSearchSiteNumberCombo)
        self.uiSearchSiteNumberBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchSiteNumberBtn.setText(_fromUtf8(""))
        self.uiSearchSiteNumberBtn.setIcon(icon1)
        self.uiSearchSiteNumberBtn.setObjectName(_fromUtf8("uiSearchSiteNumberBtn"))
        self.horizontalLayout_6.addWidget(self.uiSearchSiteNumberBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_4 = QtGui.QFrame(self.uiSiteTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        self.label_5 = QtGui.QLabel(self.uiSiteTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.uiSearchFilmNumberCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchFilmNumberCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchFilmNumberCombo.setSizePolicy(sizePolicy)
        self.uiSearchFilmNumberCombo.setEditable(True)
        self.uiSearchFilmNumberCombo.setObjectName(_fromUtf8("uiSearchFilmNumberCombo"))
        self.horizontalLayout_7.addWidget(self.uiSearchFilmNumberCombo)
        self.uiSearchFilmNumberBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchFilmNumberBtn.setText(_fromUtf8(""))
        self.uiSearchFilmNumberBtn.setIcon(icon1)
        self.uiSearchFilmNumberBtn.setObjectName(_fromUtf8("uiSearchFilmNumberBtn"))
        self.horizontalLayout_7.addWidget(self.uiSearchFilmNumberBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_5 = QtGui.QFrame(self.uiSiteTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_4.addWidget(self.line_5)
        self.label_2 = QtGui.QLabel(self.uiSiteTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiSearchYearDate = QtGui.QDateEdit(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchYearDate.sizePolicy().hasHeightForWidth())
        self.uiSearchYearDate.setSizePolicy(sizePolicy)
        self.uiSearchYearDate.setDate(QtCore.QDate(2016, 1, 1))
        self.uiSearchYearDate.setObjectName(_fromUtf8("uiSearchYearDate"))
        self.horizontalLayout_2.addWidget(self.uiSearchYearDate)
        self.uiSearchYearBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchYearBtn.setText(_fromUtf8(""))
        self.uiSearchYearBtn.setIcon(icon1)
        self.uiSearchYearBtn.setObjectName(_fromUtf8("uiSearchYearBtn"))
        self.horizontalLayout_2.addWidget(self.uiSearchYearBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.uiSiteTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.label_6 = QtGui.QLabel(self.uiSiteTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.uiSearchProjectNameCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchProjectNameCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchProjectNameCombo.setSizePolicy(sizePolicy)
        self.uiSearchProjectNameCombo.setEditable(True)
        self.uiSearchProjectNameCombo.setObjectName(_fromUtf8("uiSearchProjectNameCombo"))
        self.horizontalLayout_9.addWidget(self.uiSearchProjectNameCombo)
        self.uiSearchProjectNameBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchProjectNameBtn.setText(_fromUtf8(""))
        self.uiSearchProjectNameBtn.setIcon(icon1)
        self.uiSearchProjectNameBtn.setObjectName(_fromUtf8("uiSearchProjectNameBtn"))
        self.horizontalLayout_9.addWidget(self.uiSearchProjectNameBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.uiSiteTab, _fromUtf8(""))
        self.uiFindspotTab = QtGui.QWidget()
        self.uiFindspotTab.setObjectName(_fromUtf8("uiFindspotTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.uiFindspotTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.uiDatingGrp = QtGui.QGroupBox(self.uiFindspotTab)
        self.uiDatingGrp.setEnabled(True)
        self.uiDatingGrp.setCheckable(True)
        self.uiDatingGrp.setChecked(False)
        self.uiDatingGrp.setObjectName(_fromUtf8("uiDatingGrp"))
        self.gridLayout_3 = QtGui.QGridLayout(self.uiDatingGrp)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.uiPeriodDetailsChk = QtGui.QCheckBox(self.uiDatingGrp)
        self.uiPeriodDetailsChk.setObjectName(_fromUtf8("uiPeriodDetailsChk"))
        self.gridLayout_3.addWidget(self.uiPeriodDetailsChk, 2, 0, 1, 1)
        self.uiPeriodChk = QtGui.QCheckBox(self.uiDatingGrp)
        self.uiPeriodChk.setObjectName(_fromUtf8("uiPeriodChk"))
        self.gridLayout_3.addWidget(self.uiPeriodChk, 1, 0, 1, 1)
        self.uiTimeCombo = QtGui.QComboBox(self.uiDatingGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTimeCombo.sizePolicy().hasHeightForWidth())
        self.uiTimeCombo.setSizePolicy(sizePolicy)
        self.uiTimeCombo.setObjectName(_fromUtf8("uiTimeCombo"))
        self.gridLayout_3.addWidget(self.uiTimeCombo, 0, 1, 1, 1)
        self.uiPeriodCombo = QtGui.QComboBox(self.uiDatingGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPeriodCombo.sizePolicy().hasHeightForWidth())
        self.uiPeriodCombo.setSizePolicy(sizePolicy)
        self.uiPeriodCombo.setObjectName(_fromUtf8("uiPeriodCombo"))
        self.gridLayout_3.addWidget(self.uiPeriodCombo, 1, 1, 1, 1)
        self.uiPeriodDetailsCombo = QtGui.QComboBox(self.uiDatingGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPeriodDetailsCombo.sizePolicy().hasHeightForWidth())
        self.uiPeriodDetailsCombo.setSizePolicy(sizePolicy)
        self.uiPeriodDetailsCombo.setObjectName(_fromUtf8("uiPeriodDetailsCombo"))
        self.gridLayout_3.addWidget(self.uiPeriodDetailsCombo, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.uiDatingGrp)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.uiDatingGrp)
        self.uiCultureGrp = QtGui.QGroupBox(self.uiFindspotTab)
        self.uiCultureGrp.setEnabled(True)
        self.uiCultureGrp.setCheckable(True)
        self.uiCultureGrp.setChecked(False)
        self.uiCultureGrp.setObjectName(_fromUtf8("uiCultureGrp"))
        self.gridLayout_4 = QtGui.QGridLayout(self.uiCultureGrp)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.uiCultureCombo = QtGui.QComboBox(self.uiCultureGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCultureCombo.sizePolicy().hasHeightForWidth())
        self.uiCultureCombo.setSizePolicy(sizePolicy)
        self.uiCultureCombo.setObjectName(_fromUtf8("uiCultureCombo"))
        self.gridLayout_4.addWidget(self.uiCultureCombo, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.uiCultureGrp)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.uiCultureGrp)
        self.uiFindTypeGrp = QtGui.QGroupBox(self.uiFindspotTab)
        self.uiFindTypeGrp.setEnabled(True)
        self.uiFindTypeGrp.setCheckable(True)
        self.uiFindTypeGrp.setChecked(False)
        self.uiFindTypeGrp.setObjectName(_fromUtf8("uiFindTypeGrp"))
        self.gridLayout_5 = QtGui.QGridLayout(self.uiFindTypeGrp)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_11 = QtGui.QLabel(self.uiFindTypeGrp)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.uiFindTypeCombo = QtGui.QComboBox(self.uiFindTypeGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFindTypeCombo.sizePolicy().hasHeightForWidth())
        self.uiFindTypeCombo.setSizePolicy(sizePolicy)
        self.uiFindTypeCombo.setObjectName(_fromUtf8("uiFindTypeCombo"))
        self.gridLayout_5.addWidget(self.uiFindTypeCombo, 0, 1, 1, 1)
        self.uiFindTypeDetailsCombo = QtGui.QComboBox(self.uiFindTypeGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFindTypeDetailsCombo.sizePolicy().hasHeightForWidth())
        self.uiFindTypeDetailsCombo.setSizePolicy(sizePolicy)
        self.uiFindTypeDetailsCombo.setObjectName(_fromUtf8("uiFindTypeDetailsCombo"))
        self.gridLayout_5.addWidget(self.uiFindTypeDetailsCombo, 1, 1, 1, 1)
        self.uiFindTypeDetailsChk = QtGui.QCheckBox(self.uiFindTypeGrp)
        self.uiFindTypeDetailsChk.setObjectName(_fromUtf8("uiFindTypeDetailsChk"))
        self.gridLayout_5.addWidget(self.uiFindTypeDetailsChk, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.uiFindTypeGrp)
        self.uiSpatialFilterGrp = QtGui.QGroupBox(self.uiFindspotTab)
        self.uiSpatialFilterGrp.setEnabled(True)
        self.uiSpatialFilterGrp.setFlat(False)
        self.uiSpatialFilterGrp.setCheckable(True)
        self.uiSpatialFilterGrp.setChecked(False)
        self.uiSpatialFilterGrp.setObjectName(_fromUtf8("uiSpatialFilterGrp"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.uiSpatialFilterGrp)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_12 = QtGui.QLabel(self.uiSpatialFilterGrp)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_14.addWidget(self.label_12)
        self.uiFilterByMapLayerCombo = QgsMapLayerComboBox(self.uiSpatialFilterGrp)
        self.uiFilterByMapLayerCombo.setObjectName(_fromUtf8("uiFilterByMapLayerCombo"))
        self.verticalLayout_14.addWidget(self.uiFilterByMapLayerCombo)
        self.verticalLayout_5.addWidget(self.uiSpatialFilterGrp)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.uiSearchFindSpotBtn = QtGui.QPushButton(self.uiFindspotTab)
        self.uiSearchFindSpotBtn.setEnabled(False)
        self.uiSearchFindSpotBtn.setIcon(icon1)
        self.uiSearchFindSpotBtn.setObjectName(_fromUtf8("uiSearchFindSpotBtn"))
        self.horizontalLayout_12.addWidget(self.uiSearchFindSpotBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.uiFindspotTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.uiSearchTab.addTab(self.tab_10, _fromUtf8(""))
        self.verticalLayout.addWidget(self.uiSearchTab)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        apisSearchDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(apisSearchDialog)
        self.uiSearchTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(apisSearchDialog)

    def retranslateUi(self, apisSearchDialog):
        apisSearchDialog.setWindowTitle(_translate("apisSearchDialog", "APIS Suche", None))
        self.uiSearchImageRBtn.setText(_translate("apisSearchDialog", "Luftbilder", None))
        self.uiSearchSiteRBtn.setText(_translate("apisSearchDialog", "Fundorte", None))
        self.uiSearchFindspotRBtn.setText(_translate("apisSearchDialog", "Fundstellen", None))
        self.label_13.setText(_translate("apisSearchDialog", "Suche (Rechteck oder Punkt)", None))
        self.label.setText(_translate("apisSearchDialog", "Suche mit Vektor Feature (Selektion) aus Layer:", None))
        self.label_7.setText(_translate("apisSearchDialog", "KG-Name oder KG-Nummer (Österreich):", None))
        self.label_8.setText(_translate("apisSearchDialog", "Land (englisch):", None))
        self.uiSearchTab.setTabText(self.uiSearchTab.indexOf(self.tab_9), _translate("apisSearchDialog", "Räumliche Suche", None))
        self.label_4.setText(_translate("apisSearchDialog", "Fundort Nummer:", None))
        self.label_5.setText(_translate("apisSearchDialog", "Film Nummer:", None))
        self.label_2.setText(_translate("apisSearchDialog", "Jahr (Fundorte in Filmen eines Jahres):", None))
        self.uiSearchYearDate.setDisplayFormat(_translate("apisSearchDialog", "yyyy", None))
        self.label_6.setText(_translate("apisSearchDialog", "Projekt Bezeichnung:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uiSiteTab), _translate("apisSearchDialog", "Fundort", None))
        self.uiDatingGrp.setTitle(_translate("apisSearchDialog", "Datierung", None))
        self.uiPeriodDetailsChk.setText(_translate("apisSearchDialog", "Detail:", None))
        self.uiPeriodChk.setText(_translate("apisSearchDialog", "Periode:", None))
        self.label_3.setText(_translate("apisSearchDialog", "Zeit:", None))
        self.uiCultureGrp.setTitle(_translate("apisSearchDialog", "Kultur", None))
        self.label_9.setText(_translate("apisSearchDialog", "Kultur:", None))
        self.uiFindTypeGrp.setTitle(_translate("apisSearchDialog", "Fundart", None))
        self.label_11.setText(_translate("apisSearchDialog", "Fundart:", None))
        self.uiFindTypeDetailsChk.setText(_translate("apisSearchDialog", "Detail:", None))
        self.uiSpatialFilterGrp.setTitle(_translate("apisSearchDialog", "Räumlicher Filter", None))
        self.label_12.setText(_translate("apisSearchDialog", "Suche mit Vektor Feature (Selektion) aus Layer:", None))
        self.uiSearchFindSpotBtn.setText(_translate("apisSearchDialog", "Suche", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uiFindspotTab), _translate("apisSearchDialog", "Fundstelle", None))
        self.uiSearchTab.setTabText(self.uiSearchTab.indexOf(self.tab_10), _translate("apisSearchDialog", "Attribut Suche", None))

from qgis.gui import QgsMapLayerComboBox
import resource_rc
