# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_site_mapping_form.ui'
#
# Created: Wed Jul 20 10:05:22 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSiteMappingDialog(object):
    def setupUi(self, apisSiteMappingDialog):
        apisSiteMappingDialog.setObjectName(_fromUtf8("apisSiteMappingDialog"))
        apisSiteMappingDialog.resize(316, 723)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisSiteMappingDialog.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiNewSiteGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiNewSiteGrp.setObjectName(_fromUtf8("uiNewSiteGrp"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.uiNewSiteGrp)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiNewSiteYesRBtn = QtGui.QRadioButton(self.uiNewSiteGrp)
        self.uiNewSiteYesRBtn.setChecked(True)
        self.uiNewSiteYesRBtn.setObjectName(_fromUtf8("uiNewSiteYesRBtn"))
        self.horizontalLayout.addWidget(self.uiNewSiteYesRBtn)
        self.uiNewSiteNoRBtn = QtGui.QRadioButton(self.uiNewSiteGrp)
        self.uiNewSiteNoRBtn.setObjectName(_fromUtf8("uiNewSiteNoRBtn"))
        self.horizontalLayout.addWidget(self.uiNewSiteNoRBtn)
        self.uiEditGeometryRBtn = QtGui.QRadioButton(self.uiNewSiteGrp)
        self.uiEditGeometryRBtn.setObjectName(_fromUtf8("uiEditGeometryRBtn"))
        self.horizontalLayout.addWidget(self.uiEditGeometryRBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.uiNewSiteGrp)
        self.uiNewSiteInterpretationGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiNewSiteInterpretationGrp.setObjectName(_fromUtf8("uiNewSiteInterpretationGrp"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiNewSiteInterpretationGrp)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.uiNewSiteInterpretationGrp)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiFilmOrProjectEdit = QtGui.QLineEdit(self.uiNewSiteInterpretationGrp)
        self.uiFilmOrProjectEdit.setObjectName(_fromUtf8("uiFilmOrProjectEdit"))
        self.horizontalLayout_2.addWidget(self.uiFilmOrProjectEdit)
        self.uiCheckIfFilmBtn = QtGui.QPushButton(self.uiNewSiteInterpretationGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCheckIfFilmBtn.sizePolicy().hasHeightForWidth())
        self.uiCheckIfFilmBtn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCheckIfFilmBtn.setIcon(icon1)
        self.uiCheckIfFilmBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCheckIfFilmBtn.setObjectName(_fromUtf8("uiCheckIfFilmBtn"))
        self.horizontalLayout_2.addWidget(self.uiCheckIfFilmBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.uiNewSiteInterpretationGrp)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiImageNumberEdit = QtGui.QLineEdit(self.uiNewSiteInterpretationGrp)
        self.uiImageNumberEdit.setEnabled(False)
        self.uiImageNumberEdit.setPlaceholderText(_fromUtf8(""))
        self.uiImageNumberEdit.setObjectName(_fromUtf8("uiImageNumberEdit"))
        self.horizontalLayout_3.addWidget(self.uiImageNumberEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.uiNewSiteInterpretationGrp)
        self.uiSiteMappingModesGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiSiteMappingModesGrp.setObjectName(_fromUtf8("uiSiteMappingModesGrp"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.uiSiteMappingModesGrp)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uiMapPointAndSquareBtn = QtGui.QPushButton(self.uiSiteMappingModesGrp)
        self.uiMapPointAndSquareBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/edit_geometry_square.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiMapPointAndSquareBtn.setIcon(icon2)
        self.uiMapPointAndSquareBtn.setIconSize(QtCore.QSize(20, 24))
        self.uiMapPointAndSquareBtn.setObjectName(_fromUtf8("uiMapPointAndSquareBtn"))
        self.horizontalLayout_4.addWidget(self.uiMapPointAndSquareBtn)
        self.label_4 = QtGui.QLabel(self.uiSiteMappingModesGrp)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.uiDiagonalSpn = QtGui.QSpinBox(self.uiSiteMappingModesGrp)
        self.uiDiagonalSpn.setMinimum(1)
        self.uiDiagonalSpn.setMaximum(9999)
        self.uiDiagonalSpn.setProperty("value", 200)
        self.uiDiagonalSpn.setObjectName(_fromUtf8("uiDiagonalSpn"))
        self.horizontalLayout_4.addWidget(self.uiDiagonalSpn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uiMapPolygonAndPointBtn = QtGui.QPushButton(self.uiSiteMappingModesGrp)
        self.uiMapPolygonAndPointBtn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/edit_geometry_polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiMapPolygonAndPointBtn.setIcon(icon3)
        self.uiMapPolygonAndPointBtn.setIconSize(QtCore.QSize(20, 24))
        self.uiMapPolygonAndPointBtn.setObjectName(_fromUtf8("uiMapPolygonAndPointBtn"))
        self.horizontalLayout_5.addWidget(self.uiMapPolygonAndPointBtn)
        self.label_5 = QtGui.QLabel(self.uiSiteMappingModesGrp)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.uiSiteMappingModesGrp)
        self.uiAddToSiteManuallyGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiAddToSiteManuallyGrp.setEnabled(True)
        self.uiAddToSiteManuallyGrp.setAutoFillBackground(False)
        self.uiAddToSiteManuallyGrp.setObjectName(_fromUtf8("uiAddToSiteManuallyGrp"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.uiAddToSiteManuallyGrp)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.uiAddToSiteManuallyGrp)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.uiProvidedSiteNumberEdit = QtGui.QLineEdit(self.uiAddToSiteManuallyGrp)
        self.uiProvidedSiteNumberEdit.setObjectName(_fromUtf8("uiProvidedSiteNumberEdit"))
        self.horizontalLayout_9.addWidget(self.uiProvidedSiteNumberEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.uiReplaceProvidedSiteBtn = QtGui.QPushButton(self.uiAddToSiteManuallyGrp)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/replace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiReplaceProvidedSiteBtn.setIcon(icon4)
        self.uiReplaceProvidedSiteBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiReplaceProvidedSiteBtn.setObjectName(_fromUtf8("uiReplaceProvidedSiteBtn"))
        self.horizontalLayout_8.addWidget(self.uiReplaceProvidedSiteBtn)
        self.uiCancelManuallyEditingBtn = QtGui.QPushButton(self.uiAddToSiteManuallyGrp)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCancelManuallyEditingBtn.setIcon(icon5)
        self.uiCancelManuallyEditingBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelManuallyEditingBtn.setObjectName(_fromUtf8("uiCancelManuallyEditingBtn"))
        self.horizontalLayout_8.addWidget(self.uiCancelManuallyEditingBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.uiAddToSiteManuallyGrp)
        self.uiAddToSiteByIntersectionGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiAddToSiteByIntersectionGrp.setObjectName(_fromUtf8("uiAddToSiteByIntersectionGrp"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiAddToSiteByIntersectionGrp)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.uiAddToSiteByIntersectionGrp)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.uiIntersectingSitesCombo = QtGui.QComboBox(self.uiAddToSiteByIntersectionGrp)
        self.uiIntersectingSitesCombo.setObjectName(_fromUtf8("uiIntersectingSitesCombo"))
        self.horizontalLayout_6.addWidget(self.uiIntersectingSitesCombo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.uiAddToSelectedSiteBtn = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAddToSelectedSiteBtn.setIcon(icon6)
        self.uiAddToSelectedSiteBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiAddToSelectedSiteBtn.setObjectName(_fromUtf8("uiAddToSelectedSiteBtn"))
        self.horizontalLayout_7.addWidget(self.uiAddToSelectedSiteBtn)
        self.uiReplaceSelectedSiteBtn = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.uiReplaceSelectedSiteBtn.setIcon(icon4)
        self.uiReplaceSelectedSiteBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiReplaceSelectedSiteBtn.setObjectName(_fromUtf8("uiReplaceSelectedSiteBtn"))
        self.horizontalLayout_7.addWidget(self.uiReplaceSelectedSiteBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.uiProvideSiteManuallyBtn = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.uiProvideSiteManuallyBtn.setIcon(icon6)
        self.uiProvideSiteManuallyBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiProvideSiteManuallyBtn.setObjectName(_fromUtf8("uiProvideSiteManuallyBtn"))
        self.horizontalLayout_10.addWidget(self.uiProvideSiteManuallyBtn)
        self.uiCancelSelectedEditingBtn = QtGui.QPushButton(self.uiAddToSiteByIntersectionGrp)
        self.uiCancelSelectedEditingBtn.setIcon(icon5)
        self.uiCancelSelectedEditingBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelSelectedEditingBtn.setObjectName(_fromUtf8("uiCancelSelectedEditingBtn"))
        self.horizontalLayout_10.addWidget(self.uiCancelSelectedEditingBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.uiAddToSiteByIntersectionGrp)
        self.uiEditGeometryGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiEditGeometryGrp.setObjectName(_fromUtf8("uiEditGeometryGrp"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.uiEditGeometryGrp)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label = QtGui.QLabel(self.uiEditGeometryGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/site.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_11.addWidget(self.label)
        self.uiEditGeometryStartBtn = QtGui.QPushButton(self.uiEditGeometryGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEditGeometryStartBtn.sizePolicy().hasHeightForWidth())
        self.uiEditGeometryStartBtn.setSizePolicy(sizePolicy)
        self.uiEditGeometryStartBtn.setIcon(icon3)
        self.uiEditGeometryStartBtn.setObjectName(_fromUtf8("uiEditGeometryStartBtn"))
        self.horizontalLayout_11.addWidget(self.uiEditGeometryStartBtn)
        self.uiEditGeometryCancelBtn = QtGui.QPushButton(self.uiEditGeometryGrp)
        self.uiEditGeometryCancelBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEditGeometryCancelBtn.sizePolicy().hasHeightForWidth())
        self.uiEditGeometryCancelBtn.setSizePolicy(sizePolicy)
        self.uiEditGeometryCancelBtn.setIcon(icon5)
        self.uiEditGeometryCancelBtn.setObjectName(_fromUtf8("uiEditGeometryCancelBtn"))
        self.horizontalLayout_11.addWidget(self.uiEditGeometryCancelBtn)
        self.verticalLayout.addWidget(self.uiEditGeometryGrp)
        self.uiEditFindSpotGeometryGrp = QtGui.QGroupBox(self.dockWidgetContents)
        self.uiEditFindSpotGeometryGrp.setObjectName(_fromUtf8("uiEditFindSpotGeometryGrp"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.uiEditFindSpotGeometryGrp)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_8 = QtGui.QLabel(self.uiEditFindSpotGeometryGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/findspot.png")))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_12.addWidget(self.label_8)
        self.uiEditFindSpotGeometryStartBtn = QtGui.QPushButton(self.uiEditFindSpotGeometryGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEditFindSpotGeometryStartBtn.sizePolicy().hasHeightForWidth())
        self.uiEditFindSpotGeometryStartBtn.setSizePolicy(sizePolicy)
        self.uiEditFindSpotGeometryStartBtn.setIcon(icon3)
        self.uiEditFindSpotGeometryStartBtn.setObjectName(_fromUtf8("uiEditFindSpotGeometryStartBtn"))
        self.horizontalLayout_12.addWidget(self.uiEditFindSpotGeometryStartBtn)
        self.uiEditFindSpotGeometryCancelBtn = QtGui.QPushButton(self.uiEditFindSpotGeometryGrp)
        self.uiEditFindSpotGeometryCancelBtn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEditFindSpotGeometryCancelBtn.sizePolicy().hasHeightForWidth())
        self.uiEditFindSpotGeometryCancelBtn.setSizePolicy(sizePolicy)
        self.uiEditFindSpotGeometryCancelBtn.setIcon(icon5)
        self.uiEditFindSpotGeometryCancelBtn.setObjectName(_fromUtf8("uiEditFindSpotGeometryCancelBtn"))
        self.horizontalLayout_12.addWidget(self.uiEditFindSpotGeometryCancelBtn)
        self.verticalLayout.addWidget(self.uiEditFindSpotGeometryGrp)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        apisSiteMappingDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(apisSiteMappingDialog)
        QtCore.QMetaObject.connectSlotsByName(apisSiteMappingDialog)

    def retranslateUi(self, apisSiteMappingDialog):
        apisSiteMappingDialog.setWindowTitle(_translate("apisSiteMappingDialog", "APIS Fundort Kartierung", None))
        self.uiNewSiteGrp.setTitle(_translate("apisSiteMappingDialog", "Neuer Fundort", None))
        self.uiNewSiteYesRBtn.setText(_translate("apisSiteMappingDialog", "ja", None))
        self.uiNewSiteNoRBtn.setText(_translate("apisSiteMappingDialog", "nein", None))
        self.uiEditGeometryRBtn.setText(_translate("apisSiteMappingDialog", "Geometrie Editieren", None))
        self.uiNewSiteInterpretationGrp.setTitle(_translate("apisSiteMappingDialog", "Interpretation", None))
        self.label_2.setText(_translate("apisSiteMappingDialog", "Filmnummer oder Projektbezeichnung:", None))
        self.uiCheckIfFilmBtn.setText(_translate("apisSiteMappingDialog", "Check", None))
        self.label_3.setText(_translate("apisSiteMappingDialog", "Bildnummer(n) (-1 für kein Bild):", None))
        self.uiImageNumberEdit.setText(_translate("apisSiteMappingDialog", "-1", None))
        self.uiSiteMappingModesGrp.setTitle(_translate("apisSiteMappingDialog", "Kartierung", None))
        self.label_4.setText(_translate("apisSiteMappingDialog", "Quadrat mit Diagonale [m]:", None))
        self.label_5.setText(_translate("apisSiteMappingDialog", "Polygon", None))
        self.uiAddToSiteManuallyGrp.setTitle(_translate("apisSiteMappingDialog", "Fundort Manuell Angeben", None))
        self.label_7.setText(_translate("apisSiteMappingDialog", "Bestehende Fundortnummer (z.B. AUT.12):", None))
        self.uiProvidedSiteNumberEdit.setText(_translate("apisSiteMappingDialog", "AUT.", None))
        self.uiProvidedSiteNumberEdit.setPlaceholderText(_translate("apisSiteMappingDialog", "AUT.", None))
        self.uiReplaceProvidedSiteBtn.setText(_translate("apisSiteMappingDialog", "Ersetzen", None))
        self.uiCancelManuallyEditingBtn.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))
        self.uiAddToSiteByIntersectionGrp.setTitle(_translate("apisSiteMappingDialog", "Bestehende Fundorte im kartierten Bereich", None))
        self.label_6.setText(_translate("apisSiteMappingDialog", "Kartierung zu Fundort hinzufügen:", None))
        self.uiAddToSelectedSiteBtn.setText(_translate("apisSiteMappingDialog", "Hinzufügen", None))
        self.uiReplaceSelectedSiteBtn.setText(_translate("apisSiteMappingDialog", "Ersetzen", None))
        self.uiProvideSiteManuallyBtn.setText(_translate("apisSiteMappingDialog", "Manuelle Eingabe", None))
        self.uiCancelSelectedEditingBtn.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))
        self.uiEditGeometryGrp.setTitle(_translate("apisSiteMappingDialog", "Geometrie Editieren Fundorte (mit QGIS)", None))
        self.uiEditGeometryStartBtn.setText(_translate("apisSiteMappingDialog", "Starten", None))
        self.uiEditGeometryCancelBtn.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))
        self.uiEditFindSpotGeometryGrp.setTitle(_translate("apisSiteMappingDialog", "Geometrie Editieren Fundstellen (mit QGIS)", None))
        self.uiEditFindSpotGeometryStartBtn.setText(_translate("apisSiteMappingDialog", "Starten", None))
        self.uiEditFindSpotGeometryCancelBtn.setText(_translate("apisSiteMappingDialog", "Abbrechen", None))

import resource_rc
