# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_image_mapping_form.ui'
#
# Created: Wed Apr 27 09:52:16 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisImageMappingDialog(object):
    def setupUi(self, apisImageMappingDialog):
        apisImageMappingDialog.setObjectName(_fromUtf8("apisImageMappingDialog"))
        apisImageMappingDialog.resize(285, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisImageMappingDialog.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.uiFilmSelectionHorizontalLayout = QtGui.QHBoxLayout()
        self.uiFilmSelectionHorizontalLayout.setObjectName(_fromUtf8("uiFilmSelectionHorizontalLayout"))
        self.uiFilmSelectionBtn = QtGui.QPushButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/film_selection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFilmSelectionBtn.setIcon(icon1)
        self.uiFilmSelectionBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiFilmSelectionBtn.setAutoDefault(False)
        self.uiFilmSelectionBtn.setObjectName(_fromUtf8("uiFilmSelectionBtn"))
        self.uiFilmSelectionHorizontalLayout.addWidget(self.uiFilmSelectionBtn)
        self.uiCurrentFilmNumberEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.uiCurrentFilmNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCurrentFilmNumberEdit.setFrame(True)
        self.uiCurrentFilmNumberEdit.setReadOnly(True)
        self.uiCurrentFilmNumberEdit.setObjectName(_fromUtf8("uiCurrentFilmNumberEdit"))
        self.uiFilmSelectionHorizontalLayout.addWidget(self.uiCurrentFilmNumberEdit)
        self.verticalLayout.addLayout(self.uiFilmSelectionHorizontalLayout)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.uiMappingGridLayout = QtGui.QGridLayout()
        self.uiMappingGridLayout.setObjectName(_fromUtf8("uiMappingGridLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.uiMappingGridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.uiYCoordinateLbl = QtGui.QLabel(self.dockWidgetContents)
        self.uiYCoordinateLbl.setObjectName(_fromUtf8("uiYCoordinateLbl"))
        self.uiMappingGridLayout.addWidget(self.uiYCoordinateLbl, 2, 2, 1, 1)
        self.uiXCoordinateLbl = QtGui.QLabel(self.dockWidgetContents)
        self.uiXCoordinateLbl.setObjectName(_fromUtf8("uiXCoordinateLbl"))
        self.uiMappingGridLayout.addWidget(self.uiXCoordinateLbl, 1, 2, 1, 1)
        self.uiSetCenterPointBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.uiSetCenterPointBtn.setMaximumSize(QtCore.QSize(32, 32))
        self.uiSetCenterPointBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/center_point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSetCenterPointBtn.setIcon(icon2)
        self.uiSetCenterPointBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiSetCenterPointBtn.setCheckable(True)
        self.uiSetCenterPointBtn.setChecked(False)
        self.uiSetCenterPointBtn.setFlat(False)
        self.uiSetCenterPointBtn.setObjectName(_fromUtf8("uiSetCenterPointBtn"))
        self.uiMappingGridLayout.addWidget(self.uiSetCenterPointBtn, 1, 0, 2, 1)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.uiMappingGridLayout.addWidget(self.label_15, 4, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.uiMappingGridLayout.addWidget(self.label_5, 0, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.uiMappingGridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.uiAddCenterPointBtn = QtGui.QPushButton(self.dockWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAddCenterPointBtn.setIcon(icon3)
        self.uiAddCenterPointBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiAddCenterPointBtn.setObjectName(_fromUtf8("uiAddCenterPointBtn"))
        self.uiMappingGridLayout.addWidget(self.uiAddCenterPointBtn, 3, 0, 1, 3)
        self.uiGenerateFootprintsBtn = QtGui.QPushButton(self.dockWidgetContents)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/footprints.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiGenerateFootprintsBtn.setIcon(icon4)
        self.uiGenerateFootprintsBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiGenerateFootprintsBtn.setObjectName(_fromUtf8("uiGenerateFootprintsBtn"))
        self.uiMappingGridLayout.addWidget(self.uiGenerateFootprintsBtn, 5, 0, 1, 3)
        self.verticalLayout.addLayout(self.uiMappingGridLayout)
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.uiMappingDetailsGridLayout = QtGui.QGridLayout()
        self.uiMappingDetailsGridLayout.setObjectName(_fromUtf8("uiMappingDetailsGridLayout"))
        self.uiCancelCenterPointBtn = QtGui.QPushButton(self.dockWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCancelCenterPointBtn.setIcon(icon5)
        self.uiCancelCenterPointBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelCenterPointBtn.setObjectName(_fromUtf8("uiCancelCenterPointBtn"))
        self.uiMappingDetailsGridLayout.addWidget(self.uiCancelCenterPointBtn, 1, 1, 1, 1)
        self.uiSaveCenterPointBtn = QtGui.QPushButton(self.dockWidgetContents)
        self.uiSaveCenterPointBtn.setIcon(icon3)
        self.uiSaveCenterPointBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiSaveCenterPointBtn.setObjectName(_fromUtf8("uiSaveCenterPointBtn"))
        self.uiMappingDetailsGridLayout.addWidget(self.uiSaveCenterPointBtn, 1, 0, 1, 1)
        self.uiMappingDetailsTBox = QtGui.QToolBox(self.dockWidgetContents)
        self.uiMappingDetailsTBox.setEnabled(True)
        self.uiMappingDetailsTBox.setObjectName(_fromUtf8("uiMappingDetailsTBox"))
        self.pageOblique = QtGui.QWidget()
        self.pageOblique.setGeometry(QtCore.QRect(0, 0, 265, 231))
        self.pageOblique.setObjectName(_fromUtf8("pageOblique"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.pageOblique)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 261, 231))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.uiImageNumberToSpn = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.uiImageNumberToSpn.setMinimum(1)
        self.uiImageNumberToSpn.setMaximum(999)
        self.uiImageNumberToSpn.setObjectName(_fromUtf8("uiImageNumberToSpn"))
        self.gridLayout_3.addWidget(self.uiImageNumberToSpn, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.uiFlightHeightObliqueSpn = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.uiFlightHeightObliqueSpn.setMaximum(99999)
        self.uiFlightHeightObliqueSpn.setObjectName(_fromUtf8("uiFlightHeightObliqueSpn"))
        self.gridLayout_3.addWidget(self.uiFlightHeightObliqueSpn, 1, 3, 1, 1)
        self.uiImageDiameterSpn = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.uiImageDiameterSpn.setMinimum(150)
        self.uiImageDiameterSpn.setMaximum(3000)
        self.uiImageDiameterSpn.setProperty("value", 350)
        self.uiImageDiameterSpn.setObjectName(_fromUtf8("uiImageDiameterSpn"))
        self.gridLayout_3.addWidget(self.uiImageDiameterSpn, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.uiImageNumberFromSpn = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.uiImageNumberFromSpn.setMinimum(1)
        self.uiImageNumberFromSpn.setMaximum(999)
        self.uiImageNumberFromSpn.setObjectName(_fromUtf8("uiImageNumberFromSpn"))
        self.gridLayout_3.addWidget(self.uiImageNumberFromSpn, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.uiProjectObliqueCombo = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.uiProjectObliqueCombo.setObjectName(_fromUtf8("uiProjectObliqueCombo"))
        self.gridLayout_3.addWidget(self.uiProjectObliqueCombo, 4, 1, 1, 3)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.uiImageDescriptionEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.uiImageDescriptionEdit.setObjectName(_fromUtf8("uiImageDescriptionEdit"))
        self.gridLayout_3.addWidget(self.uiImageDescriptionEdit, 3, 1, 1, 3)
        self.uiImageKeywordEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.uiImageKeywordEdit.setObjectName(_fromUtf8("uiImageKeywordEdit"))
        self.gridLayout_3.addWidget(self.uiImageKeywordEdit, 2, 1, 1, 3)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.uiAddProjectObliqueBtn = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.uiAddProjectObliqueBtn.setText(_fromUtf8(""))
        self.uiAddProjectObliqueBtn.setIcon(icon3)
        self.uiAddProjectObliqueBtn.setObjectName(_fromUtf8("uiAddProjectObliqueBtn"))
        self.gridLayout_3.addWidget(self.uiAddProjectObliqueBtn, 4, 4, 1, 1)
        self.uiRemoveProjectObliqueBtn = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.uiRemoveProjectObliqueBtn.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiRemoveProjectObliqueBtn.setIcon(icon6)
        self.uiRemoveProjectObliqueBtn.setObjectName(_fromUtf8("uiRemoveProjectObliqueBtn"))
        self.gridLayout_3.addWidget(self.uiRemoveProjectObliqueBtn, 6, 4, 1, 1)
        self.uiProjectObliqueList = QtGui.QListWidget(self.gridLayoutWidget_3)
        self.uiProjectObliqueList.setObjectName(_fromUtf8("uiProjectObliqueList"))
        self.gridLayout_3.addWidget(self.uiProjectObliqueList, 6, 0, 1, 4)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/kartierung_schraeg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiMappingDetailsTBox.addItem(self.pageOblique, icon7, _fromUtf8(""))
        self.pageVertical = QtGui.QWidget()
        self.pageVertical.setGeometry(QtCore.QRect(0, 0, 265, 231))
        self.pageVertical.setObjectName(_fromUtf8("pageVertical"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.pageVertical)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 261, 157))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiProjectVerticalCombo = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.uiProjectVerticalCombo.setObjectName(_fromUtf8("uiProjectVerticalCombo"))
        self.gridLayout_2.addWidget(self.uiProjectVerticalCombo, 3, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.uiImageNumberSpn = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.uiImageNumberSpn.setMinimum(1)
        self.uiImageNumberSpn.setMaximum(999)
        self.uiImageNumberSpn.setObjectName(_fromUtf8("uiImageNumberSpn"))
        self.gridLayout_2.addWidget(self.uiImageNumberSpn, 0, 1, 1, 2)
        self.uiFlightHeightVerticalSpn = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.uiFlightHeightVerticalSpn.setMinimum(1)
        self.uiFlightHeightVerticalSpn.setMaximum(99999)
        self.uiFlightHeightVerticalSpn.setProperty("value", 100)
        self.uiFlightHeightVerticalSpn.setObjectName(_fromUtf8("uiFlightHeightVerticalSpn"))
        self.gridLayout_2.addWidget(self.uiFlightHeightVerticalSpn, 1, 1, 1, 2)
        self.uiAddProjectVerticalBtn = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.uiAddProjectVerticalBtn.setText(_fromUtf8(""))
        self.uiAddProjectVerticalBtn.setIcon(icon3)
        self.uiAddProjectVerticalBtn.setObjectName(_fromUtf8("uiAddProjectVerticalBtn"))
        self.gridLayout_2.addWidget(self.uiAddProjectVerticalBtn, 3, 3, 1, 1)
        self.uiRemoveProjectVerticalBtn = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.uiRemoveProjectVerticalBtn.setText(_fromUtf8(""))
        self.uiRemoveProjectVerticalBtn.setIcon(icon6)
        self.uiRemoveProjectVerticalBtn.setObjectName(_fromUtf8("uiRemoveProjectVerticalBtn"))
        self.gridLayout_2.addWidget(self.uiRemoveProjectVerticalBtn, 4, 3, 1, 1)
        self.uiProjectVerticalList = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.uiProjectVerticalList.setObjectName(_fromUtf8("uiProjectVerticalList"))
        self.gridLayout_2.addWidget(self.uiProjectVerticalList, 4, 0, 1, 3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/kartierung_senkrecht.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiMappingDetailsTBox.addItem(self.pageVertical, icon8, _fromUtf8(""))
        self.uiMappingDetailsGridLayout.addWidget(self.uiMappingDetailsTBox, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.uiMappingDetailsGridLayout)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.uiMonoplotHorizontalLayout = QtGui.QHBoxLayout()
        self.uiMonoplotHorizontalLayout.setObjectName(_fromUtf8("uiMonoplotHorizontalLayout"))
        self.uiMonoplotImportBtn = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiMonoplotImportBtn.sizePolicy().hasHeightForWidth())
        self.uiMonoplotImportBtn.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/monoplot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiMonoplotImportBtn.setIcon(icon9)
        self.uiMonoplotImportBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiMonoplotImportBtn.setObjectName(_fromUtf8("uiMonoplotImportBtn"))
        self.uiMonoplotHorizontalLayout.addWidget(self.uiMonoplotImportBtn)
        self.verticalLayout.addLayout(self.uiMonoplotHorizontalLayout)
        apisImageMappingDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(apisImageMappingDialog)
        self.uiMappingDetailsTBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(apisImageMappingDialog)

    def retranslateUi(self, apisImageMappingDialog):
        apisImageMappingDialog.setWindowTitle(_translate("apisImageMappingDialog", "Bilder kartieren", None))
        self.label_4.setText(_translate("apisImageMappingDialog", "1. Film auswählen", None))
        self.uiFilmSelectionBtn.setText(_translate("apisImageMappingDialog", "Filmnummer", None))
        self.label.setText(_translate("apisImageMappingDialog", "X:", None))
        self.uiYCoordinateLbl.setText(_translate("apisImageMappingDialog", "---", None))
        self.uiXCoordinateLbl.setText(_translate("apisImageMappingDialog", "---", None))
        self.label_15.setText(_translate("apisImageMappingDialog", "3. Footprints erstellen", None))
        self.label_5.setText(_translate("apisImageMappingDialog", "2. Bildmittelpunkt(e) setzen", None))
        self.label_3.setText(_translate("apisImageMappingDialog", "Y:", None))
        self.uiAddCenterPointBtn.setText(_translate("apisImageMappingDialog", "Hinzufügen", None))
        self.uiGenerateFootprintsBtn.setText(_translate("apisImageMappingDialog", "Footprints erstellen", None))
        self.uiCancelCenterPointBtn.setText(_translate("apisImageMappingDialog", "Abbrechen", None))
        self.uiSaveCenterPointBtn.setText(_translate("apisImageMappingDialog", "Hinzufügen", None))
        self.label_8.setText(_translate("apisImageMappingDialog", "Bildnummer von:", None))
        self.label_9.setText(_translate("apisImageMappingDialog", "bis:", None))
        self.label_11.setText(_translate("apisImageMappingDialog", "Höhe:", None))
        self.label_10.setText(_translate("apisImageMappingDialog", "Durchmesser:", None))
        self.label_13.setText(_translate("apisImageMappingDialog", "Beschreibung:", None))
        self.label_14.setText(_translate("apisImageMappingDialog", "Projekt(e):", None))
        self.label_12.setText(_translate("apisImageMappingDialog", "Schlüsselwort:", None))
        self.uiMappingDetailsTBox.setItemText(self.uiMappingDetailsTBox.indexOf(self.pageOblique), _translate("apisImageMappingDialog", "schräg", None))
        self.label_6.setText(_translate("apisImageMappingDialog", "Bildnummer:", None))
        self.label_7.setText(_translate("apisImageMappingDialog", "Höhe:", None))
        self.label_16.setText(_translate("apisImageMappingDialog", "Projekt(e):", None))
        self.uiMappingDetailsTBox.setItemText(self.uiMappingDetailsTBox.indexOf(self.pageVertical), _translate("apisImageMappingDialog", "senkrecht", None))
        self.uiMonoplotImportBtn.setText(_translate("apisImageMappingDialog", "Import von MONOPLOT Daten", None))

import resource_rc
