# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_search_form.ui'
#
# Created: Wed Mar 30 18:24:50 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisSearchDialog(object):
    def setupUi(self, apisSearchDialog):
        apisSearchDialog.setObjectName(_fromUtf8("apisSearchDialog"))
        apisSearchDialog.resize(314, 557)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_6 = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_6.sizePolicy().hasHeightForWidth())
        self.tabWidget_6.setSizePolicy(sizePolicy)
        self.tabWidget_6.setObjectName(_fromUtf8("tabWidget_6"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.uiSearchImageRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchImageRBtn.setChecked(True)
        self.uiSearchImageRBtn.setObjectName(_fromUtf8("uiSearchImageRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchImageRBtn)
        self.uiSearchSiteRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchSiteRBtn.setObjectName(_fromUtf8("uiSearchSiteRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchSiteRBtn)
        self.uiSearchFindspotRBtn = QtGui.QRadioButton(self.tab_9)
        self.uiSearchFindspotRBtn.setObjectName(_fromUtf8("uiSearchFindspotRBtn"))
        self.verticalLayout_8.addWidget(self.uiSearchFindspotRBtn)
        self.line_8 = QtGui.QFrame(self.tab_9)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_8.addWidget(self.line_8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.uiSpatialSearchBtn = QtGui.QPushButton(self.tab_9)
        self.uiSpatialSearchBtn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSpatialSearchBtn.setIcon(icon)
        self.uiSpatialSearchBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiSpatialSearchBtn.setObjectName(_fromUtf8("uiSpatialSearchBtn"))
        self.horizontalLayout_8.addWidget(self.uiSpatialSearchBtn)
        self.label_13 = QtGui.QLabel(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.line_9 = QtGui.QFrame(self.tab_9)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_8.addWidget(self.line_9)
        self.label = QtGui.QLabel(self.tab_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiSearchByMapLayerCombo = QgsMapLayerComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByMapLayerCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByMapLayerCombo.setSizePolicy(sizePolicy)
        self.uiSearchByMapLayerCombo.setObjectName(_fromUtf8("uiSearchByMapLayerCombo"))
        self.horizontalLayout.addWidget(self.uiSearchByMapLayerCombo)
        self.uiSearchByMapLayerBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByMapLayerBtn.setEnabled(True)
        self.uiSearchByMapLayerBtn.setText(_fromUtf8(""))
        self.uiSearchByMapLayerBtn.setIcon(icon)
        self.uiSearchByMapLayerBtn.setObjectName(_fromUtf8("uiSearchByMapLayerBtn"))
        self.horizontalLayout.addWidget(self.uiSearchByMapLayerBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.line_10 = QtGui.QFrame(self.tab_9)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_8.addWidget(self.line_10)
        self.label_7 = QtGui.QLabel(self.tab_9)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.uiSearchByCadastralCommunityCombo = QtGui.QComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByCadastralCommunityCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByCadastralCommunityCombo.setSizePolicy(sizePolicy)
        self.uiSearchByCadastralCommunityCombo.setEditable(True)
        self.uiSearchByCadastralCommunityCombo.setObjectName(_fromUtf8("uiSearchByCadastralCommunityCombo"))
        self.horizontalLayout_10.addWidget(self.uiSearchByCadastralCommunityCombo)
        self.uiSearchByCadastralCommunityBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByCadastralCommunityBtn.setText(_fromUtf8(""))
        self.uiSearchByCadastralCommunityBtn.setIcon(icon)
        self.uiSearchByCadastralCommunityBtn.setObjectName(_fromUtf8("uiSearchByCadastralCommunityBtn"))
        self.horizontalLayout_10.addWidget(self.uiSearchByCadastralCommunityBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.line_7 = QtGui.QFrame(self.tab_9)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_8.addWidget(self.line_7)
        self.label_8 = QtGui.QLabel(self.tab_9)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.uiSearchByCountryCombo = QtGui.QComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchByCountryCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchByCountryCombo.setSizePolicy(sizePolicy)
        self.uiSearchByCountryCombo.setEditable(True)
        self.uiSearchByCountryCombo.setObjectName(_fromUtf8("uiSearchByCountryCombo"))
        self.horizontalLayout_11.addWidget(self.uiSearchByCountryCombo)
        self.uiSearchByCountryBtn = QtGui.QPushButton(self.tab_9)
        self.uiSearchByCountryBtn.setText(_fromUtf8(""))
        self.uiSearchByCountryBtn.setIcon(icon)
        self.uiSearchByCountryBtn.setObjectName(_fromUtf8("uiSearchByCountryBtn"))
        self.horizontalLayout_11.addWidget(self.uiSearchByCountryBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.tabWidget_6.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.tab_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.uiFilmTab = QtGui.QWidget()
        self.uiFilmTab.setObjectName(_fromUtf8("uiFilmTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uiFilmTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.uiFilmTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.uiSearchDate = QtGui.QDateEdit(self.tab)
        self.uiSearchDate.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.uiSearchDate.setCalendarPopup(True)
        self.uiSearchDate.setObjectName(_fromUtf8("uiSearchDate"))
        self.verticalLayout_15.addWidget(self.uiSearchDate)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiYearOnlyRBtn = QtGui.QRadioButton(self.tab)
        self.uiYearOnlyRBtn.setObjectName(_fromUtf8("uiYearOnlyRBtn"))
        self.gridLayout.addWidget(self.uiYearOnlyRBtn, 0, 0, 1, 1)
        self.uiYearMonthRBtn = QtGui.QRadioButton(self.tab)
        self.uiYearMonthRBtn.setObjectName(_fromUtf8("uiYearMonthRBtn"))
        self.gridLayout.addWidget(self.uiYearMonthRBtn, 0, 1, 1, 1)
        self.uiMonthOnlyRBtn = QtGui.QRadioButton(self.tab)
        self.uiMonthOnlyRBtn.setChecked(False)
        self.uiMonthOnlyRBtn.setObjectName(_fromUtf8("uiMonthOnlyRBtn"))
        self.gridLayout.addWidget(self.uiMonthOnlyRBtn, 1, 0, 1, 1)
        self.uiDateRBtn = QtGui.QRadioButton(self.tab)
        self.uiDateRBtn.setChecked(True)
        self.uiDateRBtn.setObjectName(_fromUtf8("uiDateRBtn"))
        self.gridLayout.addWidget(self.uiDateRBtn, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 2, 1)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiToLbl_3 = QtGui.QLabel(self.tab_2)
        self.uiToLbl_3.setObjectName(_fromUtf8("uiToLbl_3"))
        self.gridLayout_2.addWidget(self.uiToLbl_3, 1, 0, 1, 1)
        self.uiFromChk = QtGui.QCheckBox(self.tab_2)
        self.uiFromChk.setText(_fromUtf8(""))
        self.uiFromChk.setChecked(True)
        self.uiFromChk.setObjectName(_fromUtf8("uiFromChk"))
        self.gridLayout_2.addWidget(self.uiFromChk, 0, 1, 1, 1)
        self.uiToDate_3 = QtGui.QDateEdit(self.tab_2)
        self.uiToDate_3.setDate(QtCore.QDate(2000, 2, 1))
        self.uiToDate_3.setCalendarPopup(True)
        self.uiToDate_3.setObjectName(_fromUtf8("uiToDate_3"))
        self.gridLayout_2.addWidget(self.uiToDate_3, 1, 2, 1, 1)
        self.uiFromDate = QtGui.QDateEdit(self.tab_2)
        self.uiFromDate.setDate(QtCore.QDate(1900, 1, 1))
        self.uiFromDate.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.uiFromDate.setCalendarPopup(True)
        self.uiFromDate.setObjectName(_fromUtf8("uiFromDate"))
        self.gridLayout_2.addWidget(self.uiFromDate, 0, 2, 1, 1)
        self.uiToChk_3 = QtGui.QCheckBox(self.tab_2)
        self.uiToChk_3.setText(_fromUtf8(""))
        self.uiToChk_3.setChecked(True)
        self.uiToChk_3.setObjectName(_fromUtf8("uiToChk_3"))
        self.gridLayout_2.addWidget(self.uiToChk_3, 1, 1, 1, 1)
        self.uiFromLbl = QtGui.QLabel(self.tab_2)
        self.uiFromLbl.setObjectName(_fromUtf8("uiFromLbl"))
        self.gridLayout_2.addWidget(self.uiFromLbl, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 3, 2, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_2)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.uiMilitaryNumberLbl = QtGui.QLabel(self.tab_3)
        self.uiMilitaryNumberLbl.setObjectName(_fromUtf8("uiMilitaryNumberLbl"))
        self.verticalLayout_17.addWidget(self.uiMilitaryNumberLbl)
        self.uiMilitaryNumberEdit = QtGui.QLineEdit(self.tab_3)
        self.uiMilitaryNumberEdit.setObjectName(_fromUtf8("uiMilitaryNumberEdit"))
        self.verticalLayout_17.addWidget(self.uiMilitaryNumberEdit)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uiFilmModeLbl = QtGui.QLabel(self.uiFilmTab)
        self.uiFilmModeLbl.setObjectName(_fromUtf8("uiFilmModeLbl"))
        self.horizontalLayout_4.addWidget(self.uiFilmModeLbl)
        self.uiVerticalChk = QtGui.QCheckBox(self.uiFilmTab)
        self.uiVerticalChk.setEnabled(True)
        self.uiVerticalChk.setChecked(False)
        self.uiVerticalChk.setTristate(True)
        self.uiVerticalChk.setObjectName(_fromUtf8("uiVerticalChk"))
        self.horizontalLayout_4.addWidget(self.uiVerticalChk)
        self.uiObliqueChk = QtGui.QCheckBox(self.uiFilmTab)
        self.uiObliqueChk.setChecked(False)
        self.uiObliqueChk.setTristate(True)
        self.uiObliqueChk.setObjectName(_fromUtf8("uiObliqueChk"))
        self.horizontalLayout_4.addWidget(self.uiObliqueChk)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_7 = QtGui.QPushButton(self.uiFilmTab)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tabWidget.addTab(self.uiFilmTab, _fromUtf8(""))
        self.uiSiteTab = QtGui.QWidget()
        self.uiSiteTab.setObjectName(_fromUtf8("uiSiteTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.uiSiteTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.uiSiteTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.uiSearchSiteNumberCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchSiteNumberCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchSiteNumberCombo.setSizePolicy(sizePolicy)
        self.uiSearchSiteNumberCombo.setEditable(True)
        self.uiSearchSiteNumberCombo.setObjectName(_fromUtf8("uiSearchSiteNumberCombo"))
        self.horizontalLayout_6.addWidget(self.uiSearchSiteNumberCombo)
        self.uiSearchSiteNumberBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchSiteNumberBtn.setText(_fromUtf8(""))
        self.uiSearchSiteNumberBtn.setIcon(icon)
        self.uiSearchSiteNumberBtn.setObjectName(_fromUtf8("uiSearchSiteNumberBtn"))
        self.horizontalLayout_6.addWidget(self.uiSearchSiteNumberBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_4 = QtGui.QFrame(self.uiSiteTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        self.label_5 = QtGui.QLabel(self.uiSiteTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.uiSearchFilmNumberCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchFilmNumberCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchFilmNumberCombo.setSizePolicy(sizePolicy)
        self.uiSearchFilmNumberCombo.setEditable(True)
        self.uiSearchFilmNumberCombo.setObjectName(_fromUtf8("uiSearchFilmNumberCombo"))
        self.horizontalLayout_7.addWidget(self.uiSearchFilmNumberCombo)
        self.uiSearchFilmNumberBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchFilmNumberBtn.setText(_fromUtf8(""))
        self.uiSearchFilmNumberBtn.setIcon(icon)
        self.uiSearchFilmNumberBtn.setObjectName(_fromUtf8("uiSearchFilmNumberBtn"))
        self.horizontalLayout_7.addWidget(self.uiSearchFilmNumberBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_5 = QtGui.QFrame(self.uiSiteTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_4.addWidget(self.line_5)
        self.label_2 = QtGui.QLabel(self.uiSiteTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiSearchYearDate = QtGui.QDateEdit(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchYearDate.sizePolicy().hasHeightForWidth())
        self.uiSearchYearDate.setSizePolicy(sizePolicy)
        self.uiSearchYearDate.setDate(QtCore.QDate(2016, 1, 1))
        self.uiSearchYearDate.setObjectName(_fromUtf8("uiSearchYearDate"))
        self.horizontalLayout_2.addWidget(self.uiSearchYearDate)
        self.uiSearchYearBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchYearBtn.setText(_fromUtf8(""))
        self.uiSearchYearBtn.setIcon(icon)
        self.uiSearchYearBtn.setObjectName(_fromUtf8("uiSearchYearBtn"))
        self.horizontalLayout_2.addWidget(self.uiSearchYearBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.uiSiteTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.label_6 = QtGui.QLabel(self.uiSiteTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.uiSearchProjectNameCombo = QtGui.QComboBox(self.uiSiteTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiSearchProjectNameCombo.sizePolicy().hasHeightForWidth())
        self.uiSearchProjectNameCombo.setSizePolicy(sizePolicy)
        self.uiSearchProjectNameCombo.setEditable(True)
        self.uiSearchProjectNameCombo.setObjectName(_fromUtf8("uiSearchProjectNameCombo"))
        self.horizontalLayout_9.addWidget(self.uiSearchProjectNameCombo)
        self.uiSearchProjectNameBtn = QtGui.QPushButton(self.uiSiteTab)
        self.uiSearchProjectNameBtn.setText(_fromUtf8(""))
        self.uiSearchProjectNameBtn.setIcon(icon)
        self.uiSearchProjectNameBtn.setObjectName(_fromUtf8("uiSearchProjectNameBtn"))
        self.horizontalLayout_9.addWidget(self.uiSearchProjectNameBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.tabWidget.addTab(self.uiSiteTab, _fromUtf8(""))
        self.uiFindspotTab = QtGui.QWidget()
        self.uiFindspotTab.setObjectName(_fromUtf8("uiFindspotTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.uiFindspotTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.uiFindspotTab)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_3.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_3.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_3.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.gridLayout_3.addWidget(self.comboBox_6, 1, 1, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.gridLayout_3.addWidget(self.comboBox_7, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.uiFindspotTab)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.gridLayout_4.addWidget(self.comboBox_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.uiFindspotTab)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.gridLayout_5.addWidget(self.comboBox_9, 0, 1, 1, 1)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_10.sizePolicy().hasHeightForWidth())
        self.comboBox_10.setSizePolicy(sizePolicy)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.gridLayout_5.addWidget(self.comboBox_10, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.uiFindspotTab)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_14.addWidget(self.label_12)
        self.mMapLayerComboBox_4 = QgsMapLayerComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mMapLayerComboBox_4.sizePolicy().hasHeightForWidth())
        self.mMapLayerComboBox_4.setSizePolicy(sizePolicy)
        self.mMapLayerComboBox_4.setObjectName(_fromUtf8("mMapLayerComboBox_4"))
        self.verticalLayout_14.addWidget(self.mMapLayerComboBox_4)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.pushButton_14 = QtGui.QPushButton(self.uiFindspotTab)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_12.addWidget(self.pushButton_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.uiFindspotTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.tabWidget_6.addTab(self.tab_10, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_6)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        apisSearchDialog.setWidget(self.dockWidgetContents)

        self.retranslateUi(apisSearchDialog)
        self.tabWidget_6.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(apisSearchDialog)

    def retranslateUi(self, apisSearchDialog):
        apisSearchDialog.setWindowTitle(_translate("apisSearchDialog", "APIS Suche", None))
        self.uiSearchImageRBtn.setText(_translate("apisSearchDialog", "Luftbilder", None))
        self.uiSearchSiteRBtn.setText(_translate("apisSearchDialog", "Fundorte", None))
        self.uiSearchFindspotRBtn.setText(_translate("apisSearchDialog", "Fundstellen", None))
        self.label_13.setText(_translate("apisSearchDialog", "Suche (Rechteck oder Punkt)", None))
        self.label.setText(_translate("apisSearchDialog", "Suche mit Vektor Feature (Selektion) aus Layer:", None))
        self.label_7.setText(_translate("apisSearchDialog", "KG-Name oder KG-Nummer (Österreich):", None))
        self.label_8.setText(_translate("apisSearchDialog", "Land:", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_9), _translate("apisSearchDialog", "Räumliche Suche", None))
        self.uiSearchDate.setDisplayFormat(_translate("apisSearchDialog", "dd.MM.yyyy", None))
        self.uiYearOnlyRBtn.setText(_translate("apisSearchDialog", "nur Jahr", None))
        self.uiYearMonthRBtn.setText(_translate("apisSearchDialog", "Jahr und Monat", None))
        self.uiMonthOnlyRBtn.setText(_translate("apisSearchDialog", "nur Monat", None))
        self.uiDateRBtn.setText(_translate("apisSearchDialog", "Datum", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("apisSearchDialog", "Datum", None))
        self.uiToLbl_3.setText(_translate("apisSearchDialog", "bis:", None))
        self.uiToDate_3.setDisplayFormat(_translate("apisSearchDialog", "dd.MM.yyyy", None))
        self.uiFromDate.setDisplayFormat(_translate("apisSearchDialog", "dd.MM.yyyy", None))
        self.uiFromLbl.setText(_translate("apisSearchDialog", "von:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("apisSearchDialog", "Zeitspanne", None))
        self.uiMilitaryNumberLbl.setText(_translate("apisSearchDialog", "Neue oder Alte Militär Nr.:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("apisSearchDialog", "Militär Nummer", None))
        self.uiFilmModeLbl.setText(_translate("apisSearchDialog", "Aufnahmerichtung:", None))
        self.uiVerticalChk.setText(_translate("apisSearchDialog", "senkrecht", None))
        self.uiObliqueChk.setText(_translate("apisSearchDialog", "schräg", None))
        self.pushButton_7.setText(_translate("apisSearchDialog", "Suche", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uiFilmTab), _translate("apisSearchDialog", "Film", None))
        self.label_4.setText(_translate("apisSearchDialog", "Fundort Nummer:", None))
        self.label_5.setText(_translate("apisSearchDialog", "Film Nummer:", None))
        self.label_2.setText(_translate("apisSearchDialog", "Jahr (Fundorte in Filmen eines Jahres):", None))
        self.uiSearchYearDate.setDisplayFormat(_translate("apisSearchDialog", "yyyy", None))
        self.label_6.setText(_translate("apisSearchDialog", "Projekt Bezeichnung:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uiSiteTab), _translate("apisSearchDialog", "Fundort", None))
        self.groupBox.setTitle(_translate("apisSearchDialog", "Datierung", None))
        self.checkBox_3.setText(_translate("apisSearchDialog", "Pperiode:", None))
        self.checkBox_2.setText(_translate("apisSearchDialog", "Periode:", None))
        self.checkBox.setText(_translate("apisSearchDialog", "Zeit:", None))
        self.groupBox_2.setTitle(_translate("apisSearchDialog", "Kultur", None))
        self.label_9.setText(_translate("apisSearchDialog", "Kultur:", None))
        self.groupBox_3.setTitle(_translate("apisSearchDialog", "Fundart", None))
        self.label_10.setText(_translate("apisSearchDialog", "Details:", None))
        self.label_11.setText(_translate("apisSearchDialog", "Fundart:", None))
        self.groupBox_4.setTitle(_translate("apisSearchDialog", "Räumlicher Filter", None))
        self.label_12.setText(_translate("apisSearchDialog", "Suche mit Vektor Feature (Selektion) aus Layer:", None))
        self.pushButton_14.setText(_translate("apisSearchDialog", "Suche", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uiFindspotTab), _translate("apisSearchDialog", "Fundstelle", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_10), _translate("apisSearchDialog", "Attribut Suche", None))

from qgis.gui import QgsMapLayerComboBox
import resource_rc
