# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_sharding_form.ui'
#
# Created: Thu May 19 16:22:35 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisShardingDialog(object):
    def setupUi(self, apisShardingDialog):
        apisShardingDialog.setObjectName(_fromUtf8("apisShardingDialog"))
        apisShardingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisShardingDialog.resize(800, 566)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/apis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisShardingDialog.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(apisShardingDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiViewPicturesBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiViewPicturesBtn.setMinimumSize(QtCore.QSize(150, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiViewPicturesBtn.setIcon(icon1)
        self.uiViewPicturesBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiViewPicturesBtn.setAutoDefault(False)
        self.uiViewPicturesBtn.setObjectName(_fromUtf8("uiViewPicturesBtn"))
        self.horizontalLayout.addWidget(self.uiViewPicturesBtn)
        self.uiViewSketchesBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiViewSketchesBtn.setMinimumSize(QtCore.QSize(150, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sketch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiViewSketchesBtn.setIcon(icon2)
        self.uiViewSketchesBtn.setIconSize(QtCore.QSize(24, 24))
        self.uiViewSketchesBtn.setAutoDefault(False)
        self.uiViewSketchesBtn.setObjectName(_fromUtf8("uiViewSketchesBtn"))
        self.horizontalLayout.addWidget(self.uiViewSketchesBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiSaveBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiSaveBtn.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiSaveBtn.setIcon(icon3)
        self.uiSaveBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiSaveBtn.setAutoDefault(False)
        self.uiSaveBtn.setObjectName(_fromUtf8("uiSaveBtn"))
        self.horizontalLayout.addWidget(self.uiSaveBtn)
        self.uiCancelBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiCancelBtn.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiCancelBtn.setIcon(icon4)
        self.uiCancelBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiCancelBtn.setAutoDefault(False)
        self.uiCancelBtn.setObjectName(_fromUtf8("uiCancelBtn"))
        self.horizontalLayout.addWidget(self.uiCancelBtn)
        self.uiOkBtn = QtGui.QPushButton(apisShardingDialog)
        self.uiOkBtn.setIcon(icon3)
        self.uiOkBtn.setIconSize(QtCore.QSize(11, 11))
        self.uiOkBtn.setAutoDefault(False)
        self.uiOkBtn.setObjectName(_fromUtf8("uiOkBtn"))
        self.horizontalLayout.addWidget(self.uiOkBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uiShardingDate = QtGui.QDateEdit(apisShardingDialog)
        self.uiShardingDate.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiShardingDate.setReadOnly(True)
        self.uiShardingDate.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.uiShardingDate.setCalendarPopup(True)
        self.uiShardingDate.setObjectName(_fromUtf8("uiShardingDate"))
        self.gridLayout.addWidget(self.uiShardingDate, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(apisShardingDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.uiShardingTypeCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiShardingTypeCombo.setEditable(True)
        self.uiShardingTypeCombo.setObjectName(_fromUtf8("uiShardingTypeCombo"))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.uiShardingTypeCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiShardingTypeCombo, 5, 1, 1, 1)
        self.label = QtGui.QLabel(apisShardingDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.uiPlotPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiPlotPTxt.setObjectName(_fromUtf8("uiPlotPTxt"))
        self.gridLayout.addWidget(self.uiPlotPTxt, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(apisShardingDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(apisShardingDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.uiWhereaboutsEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiWhereaboutsEdit.setObjectName(_fromUtf8("uiWhereaboutsEdit"))
        self.gridLayout.addWidget(self.uiWhereaboutsEdit, 7, 1, 1, 1)
        self.uiSiteNumberEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiSiteNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiSiteNumberEdit.setReadOnly(True)
        self.uiSiteNumberEdit.setObjectName(_fromUtf8("uiSiteNumberEdit"))
        self.gridLayout.addWidget(self.uiSiteNumberEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(apisShardingDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(apisShardingDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(apisShardingDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.uiVisibilityEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiVisibilityEdit.setObjectName(_fromUtf8("uiVisibilityEdit"))
        self.gridLayout.addWidget(self.uiVisibilityEdit, 6, 1, 1, 1)
        self.uiNameEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiNameEdit.setObjectName(_fromUtf8("uiNameEdit"))
        self.gridLayout.addWidget(self.uiNameEdit, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(apisShardingDialog)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 55, 55);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(apisShardingDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.uiShardingNumberEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiShardingNumberEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiShardingNumberEdit.setReadOnly(True)
        self.uiShardingNumberEdit.setObjectName(_fromUtf8("uiShardingNumberEdit"))
        self.gridLayout.addWidget(self.uiShardingNumberEdit, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(apisShardingDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_13 = QtGui.QLabel(apisShardingDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.label_15 = QtGui.QLabel(apisShardingDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 13, 0, 1, 1)
        self.uiConditionRainCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiConditionRainCombo.setEditable(True)
        self.uiConditionRainCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiConditionRainCombo.setObjectName(_fromUtf8("uiConditionRainCombo"))
        self.uiConditionRainCombo.addItem(_fromUtf8(""))
        self.uiConditionRainCombo.addItem(_fromUtf8(""))
        self.uiConditionRainCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiConditionRainCombo, 14, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 2)
        self.uiConditionSoilCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiConditionSoilCombo.setEditable(True)
        self.uiConditionSoilCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiConditionSoilCombo.setObjectName(_fromUtf8("uiConditionSoilCombo"))
        self.uiConditionSoilCombo.addItem(_fromUtf8(""))
        self.uiConditionSoilCombo.addItem(_fromUtf8(""))
        self.uiConditionSoilCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiConditionSoilCombo, 12, 1, 1, 1)
        self.uiConditionMoistureCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiConditionMoistureCombo.setEditable(True)
        self.uiConditionMoistureCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiConditionMoistureCombo.setObjectName(_fromUtf8("uiConditionMoistureCombo"))
        self.uiConditionMoistureCombo.addItem(_fromUtf8(""))
        self.uiConditionMoistureCombo.addItem(_fromUtf8(""))
        self.uiConditionMoistureCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiConditionMoistureCombo, 13, 1, 1, 1)
        self.label_17 = QtGui.QLabel(apisShardingDialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 14, 0, 1, 1)
        self.uiConditionLightCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiConditionLightCombo.setEditable(True)
        self.uiConditionLightCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiConditionLightCombo.setObjectName(_fromUtf8("uiConditionLightCombo"))
        self.uiConditionLightCombo.addItem(_fromUtf8(""))
        self.uiConditionLightCombo.addItem(_fromUtf8(""))
        self.uiConditionLightCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiConditionLightCombo, 11, 1, 1, 1)
        self.label_14 = QtGui.QLabel(apisShardingDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.uiConditionPlantCoverCombo = QtGui.QComboBox(apisShardingDialog)
        self.uiConditionPlantCoverCombo.setEditable(True)
        self.uiConditionPlantCoverCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.uiConditionPlantCoverCombo.setObjectName(_fromUtf8("uiConditionPlantCoverCombo"))
        self.uiConditionPlantCoverCombo.addItem(_fromUtf8(""))
        self.uiConditionPlantCoverCombo.addItem(_fromUtf8(""))
        self.uiConditionPlantCoverCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uiConditionPlantCoverCombo, 10, 1, 1, 1)
        self.label_18 = QtGui.QLabel(apisShardingDialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 9, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_19 = QtGui.QLabel(apisShardingDialog)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.uiCadastralCommunityEdit = QtGui.QLineEdit(apisShardingDialog)
        self.uiCadastralCommunityEdit.setStyleSheet(_fromUtf8("background-color: rgb(218, 218, 218);"))
        self.uiCadastralCommunityEdit.setReadOnly(True)
        self.uiCadastralCommunityEdit.setObjectName(_fromUtf8("uiCadastralCommunityEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.uiCadastralCommunityEdit)
        self.label_8 = QtGui.QLabel(apisShardingDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.label_8)
        self.uiFindsPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiFindsPTxt.setObjectName(_fromUtf8("uiFindsPTxt"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.uiFindsPTxt)
        self.label_9 = QtGui.QLabel(apisShardingDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.label_9)
        self.uiMorphologyPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiMorphologyPTxt.setObjectName(_fromUtf8("uiMorphologyPTxt"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.uiMorphologyPTxt)
        self.label_10 = QtGui.QLabel(apisShardingDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.label_10)
        self.uiMiscellaneousPTxt = QtGui.QPlainTextEdit(apisShardingDialog)
        self.uiMiscellaneousPTxt.setObjectName(_fromUtf8("uiMiscellaneousPTxt"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.uiMiscellaneousPTxt)
        self.gridLayout_2.addLayout(self.formLayout, 0, 1, 2, 1)

        self.retranslateUi(apisShardingDialog)
        self.uiShardingTypeCombo.setCurrentIndex(-1)
        self.uiConditionRainCombo.setCurrentIndex(-1)
        self.uiConditionSoilCombo.setCurrentIndex(-1)
        self.uiConditionMoistureCombo.setCurrentIndex(-1)
        self.uiConditionLightCombo.setCurrentIndex(-1)
        self.uiConditionPlantCoverCombo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(apisShardingDialog)
        apisShardingDialog.setTabOrder(self.uiShardingDate, self.uiNameEdit)
        apisShardingDialog.setTabOrder(self.uiNameEdit, self.uiPlotPTxt)
        apisShardingDialog.setTabOrder(self.uiPlotPTxt, self.uiShardingTypeCombo)
        apisShardingDialog.setTabOrder(self.uiShardingTypeCombo, self.uiVisibilityEdit)
        apisShardingDialog.setTabOrder(self.uiVisibilityEdit, self.uiWhereaboutsEdit)
        apisShardingDialog.setTabOrder(self.uiWhereaboutsEdit, self.uiConditionPlantCoverCombo)
        apisShardingDialog.setTabOrder(self.uiConditionPlantCoverCombo, self.uiConditionLightCombo)
        apisShardingDialog.setTabOrder(self.uiConditionLightCombo, self.uiConditionSoilCombo)
        apisShardingDialog.setTabOrder(self.uiConditionSoilCombo, self.uiConditionMoistureCombo)
        apisShardingDialog.setTabOrder(self.uiConditionMoistureCombo, self.uiConditionRainCombo)
        apisShardingDialog.setTabOrder(self.uiConditionRainCombo, self.uiSaveBtn)
        apisShardingDialog.setTabOrder(self.uiSaveBtn, self.uiCancelBtn)
        apisShardingDialog.setTabOrder(self.uiCancelBtn, self.uiOkBtn)
        apisShardingDialog.setTabOrder(self.uiOkBtn, self.uiSiteNumberEdit)
        apisShardingDialog.setTabOrder(self.uiSiteNumberEdit, self.uiShardingNumberEdit)

    def retranslateUi(self, apisShardingDialog):
        apisShardingDialog.setWindowTitle(_translate("apisShardingDialog", "APIS Begehung", None))
        self.uiViewPicturesBtn.setText(_translate("apisShardingDialog", "Fotos Anzeigen", None))
        self.uiViewSketchesBtn.setText(_translate("apisShardingDialog", "Skizzen Anzeigen", None))
        self.uiSaveBtn.setText(_translate("apisShardingDialog", "Speichern", None))
        self.uiCancelBtn.setText(_translate("apisShardingDialog", "Abbrechen", None))
        self.uiOkBtn.setText(_translate("apisShardingDialog", "OK", None))
        self.uiShardingDate.setDisplayFormat(_translate("apisShardingDialog", "dd.MM.yyyy", None))
        self.label_2.setText(_translate("apisShardingDialog", "Datum der Begehung:", None))
        self.uiShardingTypeCombo.setItemText(0, _translate("apisShardingDialog", "unsystematisch", None))
        self.uiShardingTypeCombo.setItemText(1, _translate("apisShardingDialog", "intensiver Survey", None))
        self.uiShardingTypeCombo.setItemText(2, _translate("apisShardingDialog", "extensiver Survey", None))
        self.uiShardingTypeCombo.setItemText(3, _translate("apisShardingDialog", "keine Angabe", None))
        self.label.setText(_translate("apisShardingDialog", "Fundort Nummer:", None))
        self.label_3.setText(_translate("apisShardingDialog", "Name BearbeiterIn:", None))
        self.label_4.setText(_translate("apisShardingDialog", "Parzelle:", None))
        self.label_7.setText(_translate("apisShardingDialog", "Verbleib:", None))
        self.label_6.setText(_translate("apisShardingDialog", "Sichtbarkeit:", None))
        self.label_5.setText(_translate("apisShardingDialog", "Begehtyp:", None))
        self.label_16.setText(_translate("apisShardingDialog", "*", None))
        self.label_11.setText(_translate("apisShardingDialog", "Begehung:", None))
        self.label_12.setText(_translate("apisShardingDialog", "Bewuchs:", None))
        self.label_13.setText(_translate("apisShardingDialog", "Licht:", None))
        self.label_15.setText(_translate("apisShardingDialog", "Feuchtigkeit:", None))
        self.uiConditionRainCombo.setItemText(0, _translate("apisShardingDialog", "gut abgeregnet", None))
        self.uiConditionRainCombo.setItemText(1, _translate("apisShardingDialog", "mittel abgeregnet", None))
        self.uiConditionRainCombo.setItemText(2, _translate("apisShardingDialog", "schlecht abgeregnet", None))
        self.uiConditionSoilCombo.setItemText(0, _translate("apisShardingDialog", "Boden geeggt", None))
        self.uiConditionSoilCombo.setItemText(1, _translate("apisShardingDialog", "Boden gepflügt", None))
        self.uiConditionSoilCombo.setItemText(2, _translate("apisShardingDialog", "Boden ungepflügt", None))
        self.uiConditionMoistureCombo.setItemText(0, _translate("apisShardingDialog", "feucht", None))
        self.uiConditionMoistureCombo.setItemText(1, _translate("apisShardingDialog", "trocken", None))
        self.uiConditionMoistureCombo.setItemText(2, _translate("apisShardingDialog", "staubig", None))
        self.label_17.setText(_translate("apisShardingDialog", "Abgeregnet:", None))
        self.uiConditionLightCombo.setItemText(0, _translate("apisShardingDialog", "Sonne", None))
        self.uiConditionLightCombo.setItemText(1, _translate("apisShardingDialog", "Schatten", None))
        self.uiConditionLightCombo.setItemText(2, _translate("apisShardingDialog", "wechselndes Licht", None))
        self.label_14.setText(_translate("apisShardingDialog", "Boden:", None))
        self.uiConditionPlantCoverCombo.setItemText(0, _translate("apisShardingDialog", "kein Bewuchs", None))
        self.uiConditionPlantCoverCombo.setItemText(1, _translate("apisShardingDialog", "wenig Bewuchs", None))
        self.uiConditionPlantCoverCombo.setItemText(2, _translate("apisShardingDialog", "dichter Bewuchs", None))
        self.label_18.setText(_translate("apisShardingDialog", "Zustand:", None))
        self.label_19.setText(_translate("apisShardingDialog", "Katastralgemeinde:", None))
        self.label_8.setText(_translate("apisShardingDialog", "Funde:", None))
        self.label_9.setText(_translate("apisShardingDialog", "Morphologie:", None))
        self.label_10.setText(_translate("apisShardingDialog", "Sonstiges:", None))

import resource_rc
