# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/apis_film_form.ui'
#
# Created: Thu Apr 23 22:33:33 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_apisFilmDialog(object):
    def setupUi(self, apisFilmDialog):
        apisFilmDialog.setObjectName(_fromUtf8("apisFilmDialog"))
        apisFilmDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisFilmDialog.resize(819, 649)
        apisFilmDialog.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Austria))
        apisFilmDialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(apisFilmDialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 550, 318, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(apisFilmDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiFirstTBtn = QtGui.QToolButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiFirstTBtn.setIcon(icon)
        self.uiFirstTBtn.setIconSize(QtCore.QSize(16, 16))
        self.uiFirstTBtn.setObjectName(_fromUtf8("uiFirstTBtn"))
        self.horizontalLayout.addWidget(self.uiFirstTBtn)
        self.uiPreviousTBtn = QtGui.QToolButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPreviousTBtn.setIcon(icon1)
        self.uiPreviousTBtn.setObjectName(_fromUtf8("uiPreviousTBtn"))
        self.horizontalLayout.addWidget(self.uiPreviousTBtn)
        self.line_6 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.uiNextTBtn = QtGui.QToolButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNextTBtn.setIcon(icon2)
        self.uiNextTBtn.setObjectName(_fromUtf8("uiNextTBtn"))
        self.horizontalLayout.addWidget(self.uiNextTBtn)
        self.uiLastTBtn = QtGui.QToolButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiLastTBtn.setIcon(icon3)
        self.uiLastTBtn.setObjectName(_fromUtf8("uiLastTBtn"))
        self.horizontalLayout.addWidget(self.uiLastTBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uiNewFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/newfilm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNewFilmBtn.setIcon(icon4)
        self.uiNewFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiNewFilmBtn.setObjectName(_fromUtf8("uiNewFilmBtn"))
        self.horizontalLayout.addWidget(self.uiNewFilmBtn)
        self.uiSearchFilmBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uiSearchFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiSearchFilmBtn.setObjectName(_fromUtf8("uiSearchFilmBtn"))
        self.horizontalLayout.addWidget(self.uiSearchFilmBtn)
        self.line_5 = QtGui.QFrame(apisFilmDialog)
        self.line_5.setGeometry(QtCore.QRect(10, 580, 801, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.layoutWidget = QtGui.QWidget(apisFilmDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 600, 801, 40))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uiShowFlightPathBtn = QtGui.QPushButton(self.layoutWidget)
        self.uiShowFlightPathBtn.setWhatsThis(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/flightpath.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiShowFlightPathBtn.setIcon(icon5)
        self.uiShowFlightPathBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiShowFlightPathBtn.setObjectName(_fromUtf8("uiShowFlightPathBtn"))
        self.horizontalLayout_3.addWidget(self.uiShowFlightPathBtn)
        self.uiListSitesOfFilmBtn = QtGui.QPushButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/sites.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListSitesOfFilmBtn.setIcon(icon6)
        self.uiListSitesOfFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListSitesOfFilmBtn.setObjectName(_fromUtf8("uiListSitesOfFilmBtn"))
        self.horizontalLayout_3.addWidget(self.uiListSitesOfFilmBtn)
        self.uiListSitesByYearBtn = QtGui.QPushButton(self.layoutWidget)
        self.uiListSitesByYearBtn.setIcon(icon6)
        self.uiListSitesByYearBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListSitesByYearBtn.setObjectName(_fromUtf8("uiListSitesByYearBtn"))
        self.horizontalLayout_3.addWidget(self.uiListSitesByYearBtn)
        self.uiListImagesOfFilmBtn = QtGui.QPushButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiListImagesOfFilmBtn.setIcon(icon7)
        self.uiListImagesOfFilmBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiListImagesOfFilmBtn.setObjectName(_fromUtf8("uiListImagesOfFilmBtn"))
        self.horizontalLayout_3.addWidget(self.uiListImagesOfFilmBtn)
        self.uiExtractGpsFromImagesBtn = QtGui.QPushButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/extractgps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExtractGpsFromImagesBtn.setIcon(icon8)
        self.uiExtractGpsFromImagesBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExtractGpsFromImagesBtn.setObjectName(_fromUtf8("uiExtractGpsFromImagesBtn"))
        self.horizontalLayout_3.addWidget(self.uiExtractGpsFromImagesBtn)
        self.uiExportPdfBtn = QtGui.QPushButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/APIS/icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiExportPdfBtn.setIcon(icon9)
        self.uiExportPdfBtn.setIconSize(QtCore.QSize(30, 30))
        self.uiExportPdfBtn.setObjectName(_fromUtf8("uiExportPdfBtn"))
        self.horizontalLayout_3.addWidget(self.uiExportPdfBtn)
        self.layoutWidget1 = QtGui.QWidget(apisFilmDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 801, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.toolButton = QtGui.QToolButton(self.layoutWidget1)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.line_3 = QtGui.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_4.addWidget(self.line_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.line_9 = QtGui.QFrame(self.layoutWidget1)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_4.addWidget(self.line_9)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget1)
        self.dateEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_4.addWidget(self.line_4)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.uiInitalEntryDate = QtGui.QDateEdit(self.layoutWidget1)
        self.uiInitalEntryDate.setEnabled(True)
        self.uiInitalEntryDate.setReadOnly(True)
        self.uiInitalEntryDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiInitalEntryDate.setObjectName(_fromUtf8("uiInitalEntryDate"))
        self.horizontalLayout_4.addWidget(self.uiInitalEntryDate)
        self.label_23 = QtGui.QLabel(self.layoutWidget1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_4.addWidget(self.label_23)
        self.uiLastChangesDate = QtGui.QDateEdit(self.layoutWidget1)
        self.uiLastChangesDate.setEnabled(True)
        self.uiLastChangesDate.setReadOnly(True)
        self.uiLastChangesDate.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.uiLastChangesDate.setObjectName(_fromUtf8("uiLastChangesDate"))
        self.horizontalLayout_4.addWidget(self.uiLastChangesDate)
        self.line_8 = QtGui.QFrame(apisFilmDialog)
        self.line_8.setGeometry(QtCore.QRect(10, 50, 801, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.textEdit = QtGui.QTextEdit(apisFilmDialog)
        self.textEdit.setGeometry(QtCore.QRect(480, 440, 321, 81))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.line_10 = QtGui.QFrame(apisFilmDialog)
        self.line_10.setGeometry(QtCore.QRect(10, 90, 801, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.widget = QtGui.QWidget(apisFilmDialog)
        self.widget.setGeometry(QtCore.QRect(10, 330, 311, 191))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.widget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 7, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.widget)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 7, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_2.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 6, 2, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.widget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_2.addWidget(self.lineEdit_11, 4, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 6, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.widget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_2.addWidget(self.comboBox_4, 6, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_7 = QtGui.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.lineEdit_8 = QtGui.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_2.addWidget(self.lineEdit_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.widget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 5, 0, 1, 2)
        self.widget1 = QtGui.QWidget(apisFilmDialog)
        self.widget1.setGeometry(QtCore.QRect(11, 101, 311, 217))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_5 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 6, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.widget1)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 7, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.widget1)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout.addWidget(self.toolButton_3, 4, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.listView = QtGui.QListView(self.widget1)
        self.listView.setProperty("isWrapping", False)
        self.listView.setViewMode(QtGui.QListView.ListMode)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout.addWidget(self.listView, 4, 1, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.widget1)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 3)

        self.retranslateUi(apisFilmDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), apisFilmDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), apisFilmDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(apisFilmDialog)
        apisFilmDialog.setTabOrder(self.comboBox_4, self.lineEdit_12)
        apisFilmDialog.setTabOrder(self.lineEdit_12, self.lineEdit_11)
        apisFilmDialog.setTabOrder(self.lineEdit_11, self.lineEdit_2)
        apisFilmDialog.setTabOrder(self.lineEdit_2, self.comboBox)
        apisFilmDialog.setTabOrder(self.comboBox, self.lineEdit_5)
        apisFilmDialog.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        apisFilmDialog.setTabOrder(self.lineEdit_6, self.comboBox_3)
        apisFilmDialog.setTabOrder(self.comboBox_3, self.lineEdit_9)
        apisFilmDialog.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        apisFilmDialog.setTabOrder(self.lineEdit_10, self.buttonBox)
        apisFilmDialog.setTabOrder(self.buttonBox, self.textEdit)
        apisFilmDialog.setTabOrder(self.textEdit, self.lineEdit_7)
        apisFilmDialog.setTabOrder(self.lineEdit_7, self.lineEdit_8)

    def retranslateUi(self, apisFilmDialog):
        apisFilmDialog.setWindowTitle(_translate("apisFilmDialog", "APIS Film", None))
        self.uiFirstTBtn.setText(_translate("apisFilmDialog", "first", None))
        self.uiPreviousTBtn.setText(_translate("apisFilmDialog", "previous", None))
        self.lineEdit.setText(_translate("apisFilmDialog", "1", None))
        self.label.setText(_translate("apisFilmDialog", "of 9999", None))
        self.uiNextTBtn.setText(_translate("apisFilmDialog", "next", None))
        self.uiLastTBtn.setText(_translate("apisFilmDialog", "last", None))
        self.uiNewFilmBtn.setText(_translate("apisFilmDialog", "Neuer Film", None))
        self.uiSearchFilmBtn.setText(_translate("apisFilmDialog", "Film suchen", None))
        self.uiShowFlightPathBtn.setToolTip(_translate("apisFilmDialog", "Flugweg des Filmes in QGIS anzeigen", None))
        self.uiShowFlightPathBtn.setText(_translate("apisFilmDialog", "Flugweg anzeigen", None))
        self.uiListSitesOfFilmBtn.setText(_translate("apisFilmDialog", "Fundorte des Filmes", None))
        self.uiListSitesByYearBtn.setText(_translate("apisFilmDialog", "Fundorte eines Jahres", None))
        self.uiListImagesOfFilmBtn.setText(_translate("apisFilmDialog", "Bilder des Films", None))
        self.uiExtractGpsFromImagesBtn.setText(_translate("apisFilmDialog", "GPS extrahieren", None))
        self.uiExportPdfBtn.setText(_translate("apisFilmDialog", "PDF exportieren", None))
        self.toolButton.setText(_translate("apisFilmDialog", "Filmnummer", None))
        self.label_7.setText(_translate("apisFilmDialog", "Flugdatum", None))
        self.label_9.setText(_translate("apisFilmDialog", "Archiv", None))
        self.label_8.setText(_translate("apisFilmDialog", "Ersteintrag:", None))
        self.label_23.setText(_translate("apisFilmDialog", "Letzte Bearbeitung:", None))
        self.uiLastChangesDate.setDisplayFormat(_translate("apisFilmDialog", "MM/dd/yyyy", None))
        self.label_21.setText(_translate("apisFilmDialog", "Art", None))
        self.label_19.setText(_translate("apisFilmDialog", "Kasette", None))
        self.label_22.setText(_translate("apisFilmDialog", "*", None))
        self.label_14.setText(_translate("apisFilmDialog", "Format", None))
        self.label_13.setText(_translate("apisFilmDialog", "Kamera", None))
        self.label_17.setText(_translate("apisFilmDialog", "Kamera-Nr.", None))
        self.label_18.setText(_translate("apisFilmDialog", "Kammerkonstante", None))
        self.label_16.setText(_translate("apisFilmDialog", "*", None))
        self.label_20.setText(_translate("apisFilmDialog", "Film", None))
        self.label_15.setText(_translate("apisFilmDialog", "x", None))
        self.label_2.setText(_translate("apisFilmDialog", "Bildanzahl", None))
        self.label_5.setText(_translate("apisFilmDialog", "*", None))
        self.label_4.setText(_translate("apisFilmDialog", "Weise", None))
        self.comboBox.setItemText(0, _translate("apisFilmDialog", "schräg", None))
        self.comboBox.setItemText(1, _translate("apisFilmDialog", "senkrecht", None))
        self.label_3.setText(_translate("apisFilmDialog", "*", None))
        self.label_6.setText(_translate("apisFilmDialog", "Copyright", None))
        self.label_10.setText(_translate("apisFilmDialog", "Projekt(e)", None))
        self.label_11.setText(_translate("apisFilmDialog", "Militär Nr.", None))
        self.label_12.setText(_translate("apisFilmDialog", "Alte Mil. Nr.", None))
        self.toolButton_3.setText(_translate("apisFilmDialog", "...", None))
        self.toolButton_2.setText(_translate("apisFilmDialog", "...", None))

import resource_rc
